// Code generated by zigo. DO NOT EDIT.

package event_queue

import (
	"strconv"

	lifecycle "example.com/zigo/event-queue-purego/internal/lifecycle"
	raw "example.com/zigo/event-queue-purego/internal/native"
)

var (
	// ErrInvalidHandle identifies a nil or closed handle.
	ErrInvalidHandle = lifecycle.ErrInvalidHandle
	// ErrHandleInUse identifies a handle with open children.
	ErrHandleInUse = lifecycle.ErrHandleInUse
	// ErrNativePanic identifies a panic crossing the native boundary.
	ErrNativePanic = lifecycle.ErrNativePanic
	// ErrNativeStatus identifies an unknown native status.
	ErrNativeStatus = lifecycle.ErrNativeStatus
	// ErrCallbackPanic identifies a panic recovered from a callback.
	ErrCallbackPanic = lifecycle.ErrCallbackPanic
	// ErrCallbackFailed identifies a callback-reported failure.
	ErrCallbackFailed = lifecycle.ErrCallbackFailed
	// ErrOutOfRange identifies an argument outside its Zig range.
	ErrOutOfRange = lifecycle.ErrOutOfRange
	// ErrNilStream identifies a nil stream argument.
	ErrNilStream = lifecycle.ErrNilStream
)

// HandleError reports a nil or closed handle.
type HandleError = lifecycle.HandleError

// HandleInUseError reports a handle with open children.
type HandleInUseError = lifecycle.HandleInUseError

// NativePanicError reports a Zig panic at the native boundary.
type NativePanicError = lifecycle.NativePanicError

// RangeError reports an argument outside its Zig range.
type RangeError = lifecycle.RangeError

// StreamError reports an error returned by a Go stream.
type StreamError = lifecycle.StreamError

// CallbackError reports an error returned by a Go callback.
type CallbackError = lifecycle.CallbackError

// StatusError reports an unrecognized native status.
type StatusError = lifecycle.StatusError

// CallbackPanicError reports a panic recovered from a Go callback.
type CallbackPanicError = lifecycle.CallbackPanicError

// Error reports a named Zig error code.
type Error = lifecycle.Error

// ErrLibraryLoad identifies a native library loading failure.
var ErrLibraryLoad = raw.ErrLibraryLoad

// ErrOutOfMemory represents Zig error.OutOfMemory.
var ErrOutOfMemory = &Error{Code: 1, Name: "OutOfMemory"}

// ErrInvalidName represents Zig error.InvalidName.
var ErrInvalidName = &Error{Code: 2, Name: "InvalidName"}

// ErrInvalidCapacity represents Zig error.InvalidCapacity.
var ErrInvalidCapacity = &Error{Code: 3, Name: "InvalidCapacity"}

// ErrFull represents Zig error.Full.
var ErrFull = &Error{Code: 4, Name: "Full"}

// ErrEmpty represents Zig error.Empty.
var ErrEmpty = &Error{Code: 5, Name: "Empty"}

// ErrInvalidLimit represents Zig error.InvalidLimit.
var ErrInvalidLimit = &Error{Code: 6, Name: "InvalidLimit"}

// ErrObserverPanicked represents Zig error.ObserverPanicked.
var ErrObserverPanicked = &Error{Code: 7, Name: "ObserverPanicked"}

// ErrInvalidInterval represents Zig error.InvalidInterval.
var ErrInvalidInterval = &Error{Code: 8, Name: "InvalidInterval"}

func errorForCode(operation string, code int32) error {
	switch code {
	case -2:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	case 1:
		return &Error{Code: 1, Name: "OutOfMemory", Operation: operation}
	case 2:
		return &Error{Code: 2, Name: "InvalidName", Operation: operation}
	case 3:
		return &Error{Code: 3, Name: "InvalidCapacity", Operation: operation}
	case 4:
		return &Error{Code: 4, Name: "Full", Operation: operation}
	case 5:
		return &Error{Code: 5, Name: "Empty", Operation: operation}
	case 6:
		return &Error{Code: 6, Name: "InvalidLimit", Operation: operation}
	case 7:
		return &Error{Code: 7, Name: "ObserverPanicked", Operation: operation}
	case 8:
		return &Error{Code: 8, Name: "InvalidInterval", Operation: operation}
	default:
		return &Error{Code: code, Name: "Unknown(" + strconv.Itoa(int(code)) + ")", Operation: operation}
	}
}
