// Code generated by zigo. DO NOT EDIT.

// Package event_queue queues events natively and hands the results to Go.
//
// The doc body comes from the `go_package_doc` build option rather than from a
// `//!` block in the bindings file.
package event_queue

import (
	"runtime"
	"unsafe"

	raw "example.com/zigo/event-queue-purego/internal/native"
)

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName

// EchoQueueSignal calls the Zig function echoQueueSignal.
func EchoQueueSignal(signal QueueSignal) QueueSignal {
	return QueueSignal(raw.EchoQueueSignal(uint8(signal)))
}

// NewEventQueue creates a caller-owned EventQueue.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func NewEventQueue(name string, capacity uint, policy Policy, observer EventQueueCreateObserver) (*EventQueue, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	observerHandle := newEventQueueCreateObserverHandle(observer)
	result, code := raw.EventQueueCreate([]byte(name), capacity, uint32(policy), raw.CallbackPointer0(), uintptr(observerHandle))
	zigoRethrowCallbackPanic("NewEventQueue", observerHandle)
	if code != 0 {
		deleteCallbackHandle(observerHandle)
		return nil, errorForCode("NewEventQueue", code)
	}
	return newEventQueue(result, []zigoCallbackHandle{observerHandle}), nil
}

// Clone copies the queued events, name and limits into an independent
// queue that the caller owns and must close. The copy takes its own
// observer instead of sharing the original's, so closing either queue
// never strands the other's callback.
// The caller must call Close on the returned handle.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Clone(observer EventQueueCloneObserver) (*EventQueue, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Clone receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	observerHandle := newEventQueueCloneObserverHandle(observer)
	result, code := raw.EventQueueClone(ptr, raw.CallbackPointer0(), uintptr(observerHandle))
	zigoRethrowCallbackPanic("EventQueue.Clone", observerHandle)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Clone", handle)
	}
	if code != 0 {
		deleteCallbackHandle(observerHandle)
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.Clone", code), e)
	}
	return newEventQueue(result, []zigoCallbackHandle{observerHandle}), nil
}

// NewStream
// Opens a stream owned by the caller. The allocator is injected before
// the receiver, matching APIs where one handle constructs another.
// The caller must call Close on the returned handle.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) NewStream() (*Stream, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.NewStream receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueNewStream(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.NewStream", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.NewStream", code), e)
	}
	return newStream(result), nil
}

// Capacity calls the Zig function Stream.capacity.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (s *Stream) Capacity() (uint32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Stream.Capacity receiver", s)
	if err != nil {
		return 0, err
	}
	defer s.zigoRelease()
	result, code := raw.StreamCapacity(ptr)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Stream.Capacity", code), s)
	}
	return result, nil
}

// Enqueue calls the Zig function EventQueue.enqueue.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Enqueue(id uint64, value int32) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Enqueue receiver", e)
	if err != nil {
		return err
	}
	defer e.zigoRelease()
	code := raw.EventQueueEnqueue(ptr, id, value)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Enqueue", handle)
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("EventQueue.Enqueue", code), e)
	}
	return nil
}

// MergeFrom appends another queue's events to this one under the current
// policy and reports how many were taken. A null source is not an error:
// it merges nothing, which is what makes the parameter optional.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) MergeFrom(source *EventQueue) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.MergeFrom receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	sourcePtr, err := zigoOptionalPointer("EventQueue.MergeFrom parameter source", source == nil, source)
	if err != nil {
		return 0, err
	}
	defer source.zigoRelease()
	result, code := raw.EventQueueMergeFrom(ptr, sourcePtr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.MergeFrom", handle)
	}
	if source != nil {
		for _, handle := range source.callbackHandles {
			zigoRethrowCallbackPanic("EventQueue.MergeFrom", handle)
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.MergeFrom", code), e, source)
	}
	return result, nil
}

// Process calls the Zig function EventQueue.process.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Process(limit uint) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Process receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueProcess(ptr, limit)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Process", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Process", code), e)
	}
	return result, nil
}

// Name calls the Zig function EventQueue.name.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Name() (string, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Name receiver", e)
	if err != nil {
		return "", err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueName(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Name", handle)
	}
	if code != 0 {
		return "", zigoPoisonAfterPanic(errorForCode("EventQueue.Name", code), e)
	}
	return string(result), nil
}

// SampleValues
// A numeric slice return intentionally points at native storage. The Go
// binding must copy it before returning so a caller cannot alias it.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) SampleValues() ([]float32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.SampleValues receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueSampleValues(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.SampleValues", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.SampleValues", code), e)
	}
	return result, nil
}

// SampleValuesChecked returns the same samples as `sampleValues`, but an
// empty queue has nothing to sample and fails instead. The generated
// binding must report that error without reading the slice output
// parameters the shim never wrote.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) SampleValuesChecked() ([]float32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.SampleValuesChecked receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueSampleValuesChecked(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.SampleValuesChecked", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.SampleValuesChecked", code), e)
	}
	return result, nil
}

// EchoCString
// Sentinel byte pointers use the C string lowering and surface as Go
// strings without a separate length parameter.
func EchoCString(text string) string {
	return raw.EventQueueEchoCString(text)
}

// SampleCString calls the Zig function sampleCString.
func SampleCString() string {
	return raw.EventQueueSampleCString()
}

// ExtractPaths calls the Zig function extractPaths.
func ExtractPaths(paths []string) uint {
	return raw.EventQueueExtractPaths(paths)
}

// ExtractSentinelSlices calls the Zig function extractSentinelSlices.
func ExtractSentinelSlices(paths []string) uint {
	return raw.EventQueueExtractSentinelSlices(paths)
}

// ExtractSentinelPointers calls the Zig function extractSentinelPointers.
func ExtractSentinelPointers(paths []string) uint {
	return raw.EventQueueExtractSentinelPointers(paths)
}

// ExtractSamples
// Hands the caller a freshly allocated buffer. Ownership moves with the
// return value, so the generated binding must copy it and then call
// `freeSamples` before handing the slice to Go.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) ExtractSamples() ([]float32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.ExtractSamples receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueExtractSamples(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.ExtractSamples", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.ExtractSamples", code), e)
	}
	return result, nil
}

// ExtractSamplesChecked hands over a buffer exactly like `extractSamples`,
// but an empty queue fails before allocating anything. Nothing is handed
// over on that path, so the generated binding must not call `freeSamples`.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) ExtractSamplesChecked() ([]float32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.ExtractSamplesChecked receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueExtractSamplesChecked(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.ExtractSamplesChecked", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.ExtractSamplesChecked", code), e)
	}
	return result, nil
}

// ExtractLimits
// Caller-owned limit rows. `Limits` has no bool field, so the generated
// binding copies the buffer once, releases it, and reinterprets that copy
// as `[]Limits` instead of converting every row again.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) ExtractLimits() ([]Limits, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.ExtractLimits receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueExtractLimits(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.ExtractLimits", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.ExtractLimits", code), e)
	}
	return zigoLimitsSliceView(result), nil
}

// AcceptStats
// Accepts a batch of value snapshots so both backends exercise their
// struct-slice input conversion path.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) AcceptStats(values []Stats) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.AcceptStats receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	valuesRaw := zigoStatsSliceToRaw(values)
	result, code := raw.EventQueueAcceptStats(ptr, valuesRaw)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.AcceptStats", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.AcceptStats", code), e)
	}
	return result, nil
}

// ExtractSamplesInto
// The same samples as `extractSamples`, written into a buffer the caller
// already has. Nothing is allocated and nothing has to be released: the
// result says how many entries were filled, and everything past that is
// still whatever the caller left there.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) ExtractSamplesInto(dst []float32) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.ExtractSamplesInto receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueExtractSamplesInto(ptr, dst)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.ExtractSamplesInto", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.ExtractSamplesInto", code), e)
	}
	return result, nil
}

// LimitsInto
// One `Limits` row per queued event, up to what the buffer holds. `Limits`
// has no bool field, so both backends hand the buffer's address straight
// to the native call and neither direction copies.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) LimitsInto(dst []Limits) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.LimitsInto receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	var dstRaw []raw.LimitsData
	if len(dst) != 0 {
		dstRaw = unsafe.Slice((*raw.LimitsData)(unsafe.Pointer(&dst[0])), len(dst))
	}
	result, code := raw.EventQueueLimitsInto(ptr, dstRaw)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.LimitsInto", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.LimitsInto", code), e)
	}
	return result, nil
}

// Estimate
// Fills one value snapshot per queued event. The return value is the
// number of output entries written, while the explicit out metadata keeps
// the slice capacity visible in the C ABI.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Estimate(output []Stats) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Estimate receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	outputRaw := make([]raw.StatsData, len(output))
	result, code := raw.EventQueueEstimate(ptr, outputRaw)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Estimate", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Estimate", code), e)
	}
	zigoStatsSliceCopyFromRaw(output, outputRaw, int(result))
	return result, nil
}

// SampleStats
// Returns value snapshots from native storage; the generated Go binding
// must copy each struct before exposing the slice.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) SampleStats() ([]Stats, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.SampleStats receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueSampleStats(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.SampleStats", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.SampleStats", code), e)
	}
	return zigoStatsSliceFromRaw(result), nil
}

// SampleLimits
// Borrowed limit rows from native storage. The raw layer still copies
// them out of native memory; only the public layer's second copy is gone.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) SampleLimits() ([]Limits, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.SampleLimits receiver", e)
	if err != nil {
		return nil, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueSampleLimits(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.SampleLimits", handle)
	}
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("EventQueue.SampleLimits", code), e)
	}
	return zigoLimitsSliceView(result), nil
}

// Len calls the Zig function EventQueue.len.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Len() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Len receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueLen(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Len", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Len", code), e)
	}
	return result, nil
}

// Capacity calls the Zig function EventQueue.capacity.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Capacity() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Capacity receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueCapacity(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Capacity", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Capacity", code), e)
	}
	return result, nil
}

// Policy calls the Zig function EventQueue.policy.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Policy() (Policy, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Policy receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueuePolicy(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Policy", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Policy", code), e)
	}
	return Policy(result), nil
}

// Dropped calls the Zig function EventQueue.dropped.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Dropped() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Dropped receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueDropped(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Dropped", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Dropped", code), e)
	}
	return result, nil
}

// Processed calls the Zig function EventQueue.processed.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Processed() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Processed receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueProcessed(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Processed", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Processed", code), e)
	}
	return result, nil
}

// Stats calls the Zig function EventQueue.stats.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Stats() (Stats, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Stats receiver", e)
	if err != nil {
		return Stats{}, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueStats(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Stats", handle)
	}
	if code != 0 {
		return Stats{}, zigoPoisonAfterPanic(errorForCode("EventQueue.Stats", code), e)
	}
	return zigoStatsFromRaw(result), nil
}

// Limits calls the Zig function EventQueue.limits.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Limits() (Limits, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Limits receiver", e)
	if err != nil {
		return Limits{}, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueLimits(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Limits", handle)
	}
	if code != 0 {
		return Limits{}, zigoPoisonAfterPanic(errorForCode("EventQueue.Limits", code), e)
	}
	return zigoLimitsFromRaw(result), nil
}

// ApplyLimits calls the Zig function EventQueue.applyLimits.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) ApplyLimits(updated Limits) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.ApplyLimits receiver", e)
	if err != nil {
		return err
	}
	defer e.zigoRelease()
	code := raw.EventQueueApplyLimits(ptr, zigoLimitsToRaw(updated))
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.ApplyLimits", handle)
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("EventQueue.ApplyLimits", code), e)
	}
	return nil
}

// Clear calls the Zig function EventQueue.clear.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (e *EventQueue) Clear() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("EventQueue.Clear receiver", e)
	if err != nil {
		return 0, err
	}
	defer e.zigoRelease()
	result, code := raw.EventQueueClear(ptr)
	for _, handle := range e.callbackHandles {
		zigoRethrowCallbackPanic("EventQueue.Clear", handle)
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("EventQueue.Clear", code), e)
	}
	return result, nil
}

// NewTicker
// Opens a ticker the caller owns.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewTicker(interval uint32) (*Ticker, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.NewTicker(interval)
	if code != 0 {
		return nil, errorForCode("NewTicker", code)
	}
	return newTicker(result), nil
}

// Advance calls the Zig function Ticker.advance.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Ticker) Advance(steps uint32) (uint32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Ticker.Advance receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TickerAdvance(ptr, steps)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Ticker.Advance", code), t)
	}
	return result, nil
}

// LiveTickers
// Tickers still owned by the library.
func LiveTickers() uint {
	return raw.LiveTickers()
}

// LiveStreams calls the Zig function liveStreams.
func LiveStreams() uint {
	return raw.LiveStreams()
}

// LiveQueues calls the Zig function liveQueues.
func LiveQueues() uint {
	return raw.LiveQueues()
}

// LiveSamples
// Sample buffers still owned by the library. A correct binding returns this to
// zero after every `extractSamples` call.
func LiveSamples() uint {
	return raw.LiveSamples()
}

// LiveLimits calls the Zig function liveLimits.
func LiveLimits() uint {
	return raw.LiveLimits()
}
