// Code generated by zigo. DO NOT EDIT.
package event_queue

import raw "example.com/zigo/event-queue-purego/internal/native"

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

type zigoCallbackHandle = uintptr

func newEventQueueObserverHandle(value EventQueueObserver) zigoCallbackHandle {
	return raw.NewCallbackHandle((func(uint64, int32) int32)(value))
}

func deleteCallbackHandle(handle zigoCallbackHandle) { raw.DeleteCallbackHandle(handle) }

func activeCallbackHandleCount() int64 { return raw.ActiveCallbackHandleCount() }
func callbackDispatcherCount() int     { return raw.CallbackDispatcherCount() }
