const zigo = @import("zigo");
const library = @import("event_queue");

pub const bindings = zigo.define(.{
    // `freeLimits` takes its allocator as a parameter; naming it here is what
    // lets the shim fill it in rather than exposing it to Go.
    .allocator = .page_allocator,
    .root = library,
    .packages = .{.{
        .path = "types",
        .doc = "Package types contains event-queue values and the standalone Ticker handle.",
        .types = .{ "QueueSignal", "Ticker", "TickerInfo" },
        .functions = .{"root.liveTickers"},
    }},
    .types = .{
        .{ .type = library.EventQueue, .repr = .@"opaque" },
        .{ .type = library.Stats, .repr = .value },
        .{ .type = library.Limits, .repr = .value },
        .{ .type = library.QueueSignal, .repr = .enumeration, .exhaustive = false },
        .{ .type = library.Ticker, .repr = .@"opaque" },
        .{ .type = library.TickerInfo, .repr = .value },
        .{ .type = library.Stream, .repr = .@"opaque" },
        .{ .type = library.BorrowBox, .repr = .@"opaque" },
        .{ .type = library.BorrowView, .repr = .@"opaque" },
        .{ .type = library.BorrowChild, .repr = .@"opaque" },
    },
    .functions = .{
        .{ .path = "root.echoQueueSignal", .params = .{"signal"} },
        .{
            .path = "EventQueue.create",
            .params = .{ "name", "capacity", "policy", "observer", "userdata" },
            .param_meta = .{
                .name = .{ .semantic = .utf8_string },
                .observer = .{ .retention = .retained },
            },
        },
        .{
            .path = "EventQueue.clone",
            .params = .{ "observer", "userdata" },
            .param_meta = .{ .observer = .{ .retention = .retained } },
            .returns = .caller,
        },
        .{ .path = "EventQueue.newStream", .constructs = "Stream", .child_of_receiver = true },
        .{ .path = "BorrowBox.create", .params = .{"value"} },
        .{ .path = "BorrowBox.view", .returns = .borrowed },
        .{ .path = "BorrowBox.deinit" },
        .{ .path = "BorrowView.view", .returns = .borrowed },
        .{ .path = "BorrowView.newChild", .constructs = "BorrowChild", .child_of_receiver = true },
        .{ .path = "BorrowView.get" },
        .{ .path = "BorrowView.explode" },
        .{ .path = "BorrowChild.get" },
        .{ .path = "BorrowChild.deinit", .destroys = "BorrowChild" },
        .{ .path = "root.liveBorrowChildren" },
        .{ .path = "Stream.capacity" },
        .{ .path = "root.freeStream", .destroys = "Stream" },
        .{ .path = "EventQueue.enqueue", .params = .{ "id", "value" } },
        .{ .path = "EventQueue.mergeFrom", .params = .{"source"} },
        .{ .path = "EventQueue.process", .params = .{"limit"} },
        .{ .path = "EventQueue.name", .semantic = .utf8_string },
        .{ .path = "EventQueue.sampleValues" },
        .{ .path = "EventQueue.sampleValuesChecked" },
        .{ .path = "EventQueue.echoCString", .params = .{"text"} },
        .{ .path = "EventQueue.sampleCString" },
        .{
            .path = "EventQueue.extractPaths",
            .params = .{"paths"},
            .param_meta = .{ .paths = .{ .semantic = .utf8_string } },
        },
        .{ .path = "EventQueue.extractSentinelSlices", .params = .{"paths"} },
        .{ .path = "EventQueue.extractSentinelPointers", .params = .{"paths"} },
        .{
            .path = "EventQueue.extractSamples",
            .returns = .caller,
            .release = "EventQueue.freeSamples",
        },
        .{
            .path = "EventQueue.extractSamplesChecked",
            .returns = .caller,
            .release = "EventQueue.freeSamples",
        },
        .{ .path = "EventQueue.freeSamples", .params = .{"samples"} },
        .{
            .path = "EventQueue.extractLimits",
            .returns = .caller,
            .release = "EventQueue.freeLimits",
        },
        .{ .path = "EventQueue.freeLimits", .params = .{"rows"} },
        .{ .path = "EventQueue.acceptStats", .params = .{"values"} },
        // The `...Into(dst)` shape: the caller owns the buffer, and the result
        // says how much of it was filled.
        .{
            .path = "EventQueue.extractSamplesInto",
            .params = .{"dst"},
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },
        .{
            .path = "EventQueue.limitsInto",
            .params = .{"dst"},
            .param_meta = .{ .dst = .{ .direction = .out, .written = .@"return" } },
        },
        .{
            .path = "EventQueue.estimate",
            .params = .{"output"},
            .param_meta = .{ .output = .{ .direction = .out, .written = .@"return" } },
        },
        .{ .path = "EventQueue.sampleStats" },
        .{ .path = "EventQueue.sampleLimits" },
        .{ .path = "EventQueue.len" },
        .{ .path = "EventQueue.capacity" },
        .{ .path = "EventQueue.policy" },
        .{ .path = "EventQueue.dropped" },
        .{ .path = "EventQueue.processed" },
        .{ .path = "EventQueue.stats" },
        .{ .path = "EventQueue.limits" },
        .{ .path = "EventQueue.applyLimits", .params = .{"updated"} },
        .{ .path = "EventQueue.clear" },
        .{ .path = "EventQueue.deinit" },
        // A constructor and destructor declared beside their type rather than
        // inside it, paired by naming the type instead of by their spelling.
        .{ .path = "root.newTicker", .params = .{"interval"}, .constructs = "Ticker" },
        .{ .path = "root.freeTicker", .destroys = "Ticker" },
        .{ .path = "root.tickerAdvance", .name = "advance", .params = .{"steps"} },
        .{ .path = "root.inspectTicker", .params = .{ "info", "ticker" } },
        .{ .path = "root.liveTickers" },
        .{ .path = "root.liveStreams" },
        .{ .path = "root.liveQueues" },
        .{ .path = "root.liveSamples" },
        .{ .path = "root.liveLimits" },
    },
});
