const zigo = @import("zigo");
const library = @import("event_queue");

const api = zigo.scope(library);

pub const bindings = zigo.define(.{
    .root = library,
    .allocator = .page_allocator,
    .declarations = &.{
        api.handle("EventQueue", .{}),
        api.value("Stats", .{}),
        api.value("Limits", .{}),
        api.handle("Stream", .{}),
        api.handle("BorrowBox", .{}),
        api.handle("BorrowView", .{}),
        api.handle("BorrowChild", .{}),
        api.handle("Terminal", .{}),
        api.function("echoQueueSignal", .{ .params = &.{.{ .index = 0, .go_name = "signal" }} }),
        api.in("EventQueue").function("create", .{ .params = &.{
            .{ .index = 0, .go_name = "name", .semantic = .utf8_string }, .{ .index = 1, .go_name = "capacity" }, .{ .index = 2, .go_name = "policy" }, .{ .index = 3, .go_name = "observer", .contract = .{ .callback = .{ .retention = .retained } } }, .{ .index = 4, .go_name = "userdata" },
        } }),
        api.in("EventQueue").function("clone", .{ .returns = .{ .lifetime = .{ .owned = .{} } }, .params = &.{
            .{ .index = 1, .go_name = "observer", .contract = .{ .callback = .{ .retention = .retained } } }, .{ .index = 2, .go_name = "userdata" },
        } }),
        api.in("EventQueue").function("newStream", .{ .role = .{
            .constructor = .{ .type = api.typeRef("Stream"), .parent = .receiver, .receiver = .{ .type = api.typeRef("EventQueue") } },
        } }),
        api.in("BorrowBox").function("create", .{ .params = &.{.{ .index = 0, .go_name = "value" }} }),
        api.in("BorrowBox").function("view", .{ .returns = .{ .lifetime = .{ .borrowed = .receiver } } }),
        api.in("BorrowBox").function("deinit", .{}),
        api.in("BorrowView").function("view", .{ .returns = .{ .lifetime = .{ .borrowed = .receiver } } }),
        api.in("BorrowView").function("newChild", .{ .role = .{
            .constructor = .{ .type = api.typeRef("BorrowChild"), .parent = .receiver, .receiver = .{ .type = api.typeRef("BorrowView") } },
        } }),
        api.in("BorrowView").function("get", .{}),
        api.in("BorrowView").function("explode", .{}),
        api.in("BorrowChild").function("get", .{}),
        api.in("BorrowChild").function("deinit", .{ .role = .{ .destructor = api.typeRef("BorrowChild") } }),
        api.function("liveBorrowChildren", .{}),
        api.in("Terminal").function("init", .{ .params = &.{.{
            .index = 1,
            .go_name = "options",
            .contract = .{ .flatten = &.{ "cols", "rows", "max_scrollback_bytes" } },
        }} }),
        api.in("Terminal").function("cols", .{}),
        api.in("Terminal").function("rows", .{}),
        api.in("Terminal").function("maxScrollbackBytes", .{}),
        api.in("Terminal").function("deinit", .{}),
        api.in("Stream").function("capacity", .{}),
        api.function("freeStream", .{ .role = .{ .destructor = api.typeRef("Stream") } }),
        api.in("EventQueue").function("enqueue", .{ .params = &.{ .{ .index = 1, .go_name = "id" }, .{ .index = 2, .go_name = "value" } } }),
        api.in("EventQueue").function("mergeFrom", .{ .params = &.{.{ .index = 1, .go_name = "source" }} }),
        api.in("EventQueue").function("process", .{ .params = &.{.{ .index = 1, .go_name = "limit" }} }),
        api.in("EventQueue").function("setObserver", .{ .params = &.{
            .{ .index = 1, .go_name = "observer", .contract = .{ .callback = .{ .retention = .retained } } }, .{ .index = 2, .go_name = "userdata" },
        } }),
        api.in("EventQueue").function("name", .{ .returns = .{ .semantic = .utf8_string } }),
        api.in("EventQueue").function("sampleValues", .{}),
        api.in("EventQueue").function("sampleValuesChecked", .{}),
        api.in("EventQueue").function("selectionString", .{
            .returns = .{ .lifetime = .{ .owned = .{ .release = api.in("EventQueue").ref("freeSelectionString") } } },
        }),
        api.in("EventQueue").function("freeSelectionString", .{ .params = &.{.{ .index = 2, .go_name = "value" }} }),
        api.in("EventQueue").function("echoCString", .{ .params = &.{.{ .index = 0, .go_name = "text" }} }),
        api.in("EventQueue").function("sampleCString", .{}),
        api.in("EventQueue").function("extractPaths", .{ .params = &.{.{ .index = 0, .go_name = "paths", .semantic = .utf8_string }} }),
        api.in("EventQueue").function("extractSentinelSlices", .{ .params = &.{.{ .index = 0, .go_name = "paths" }} }),
        api.in("EventQueue").function("extractSentinelPointers", .{ .params = &.{.{ .index = 0, .go_name = "paths" }} }),
        api.in("EventQueue").function("extractSamples", .{ .returns = .{ .lifetime = .{ .owned = .{ .release = api.in("EventQueue").ref("freeSamples") } } } }),
        api.in("EventQueue").function("extractSamplesChecked", .{ .returns = .{ .lifetime = .{ .owned = .{ .release = api.in("EventQueue").ref("freeSamples") } } } }),
        api.in("EventQueue").function("freeSamples", .{ .params = &.{.{ .index = 1, .go_name = "samples" }} }),
        api.in("EventQueue").function("extractLimits", .{ .returns = .{ .lifetime = .{ .owned = .{ .release = api.in("EventQueue").ref("freeLimits") } } } }),
        api.in("EventQueue").function("freeLimits", .{ .params = &.{.{ .index = 2, .go_name = "rows" }} }),
        api.in("EventQueue").function("acceptStats", .{ .params = &.{.{ .index = 1, .go_name = "values" }} }),
        api.in("EventQueue").function("extractSamplesInto", .{
            .params = &.{.{ .index = 1, .go_name = "dst", .contract = .{ .buffer = .{ .output = .{ .written = .result } } } }},
        }),
        api.in("EventQueue").function("limitsInto", .{
            .params = &.{.{ .index = 1, .go_name = "dst", .contract = .{ .buffer = .{ .output = .{ .written = .result } } } }},
        }),
        api.in("EventQueue").function("estimate", .{ .params = &.{
            .{ .index = 1, .go_name = "output", .contract = .{ .buffer = .{ .output = .{ .written = .result } } } },
        } }),
        api.in("EventQueue").function("sampleStats", .{}),
        api.in("EventQueue").function("sampleLimits", .{}),
        api.in("EventQueue").function("len", .{}),
        api.in("EventQueue").function("capacity", .{}),
        api.in("EventQueue").function("policy", .{}),
        api.in("EventQueue").function("dropped", .{}),
        api.in("EventQueue").function("processed", .{}),
        api.in("EventQueue").function("stats", .{}),
        api.in("EventQueue").function("limits", .{}),
        api.in("EventQueue").function("applyLimits", .{ .params = &.{.{ .index = 1, .go_name = "updated" }} }),
        api.in("EventQueue").function("clear", .{}),
        api.in("EventQueue").function("deinit", .{}),
        api.function("inspectTicker", .{ .params = &.{ .{ .index = 0, .go_name = "info" }, .{ .index = 1, .go_name = "ticker" } } }),
        api.function("liveStreams", .{}),
        api.function("liveQueues", .{}),
        api.function("liveSamples", .{}),
        api.function("liveLimits", .{}),
        api.function("liveSelectionStrings", .{}),
        zigo.package(.{ .path = "types", .doc = "Package types contains event-queue values and the standalone Ticker handle.", .declarations = &.{ api.enumeration("QueueSignal", .{ .exhaustive = false }).use(zigo.features.text, .{}), api.handle("Ticker", .{}), api.value("TickerInfo", .{}), api.function("newTicker", .{
            .params = &.{.{ .index = 0, .go_name = "interval" }},
            .role = .{ .constructor = .{ .type = api.typeRef("Ticker") } },
        }), api.function("freeTicker", .{ .role = .{ .destructor = api.typeRef("Ticker") } }), api.function("liveTickers", .{}), api.function("tickerAdvance", .{
            .name = "advance",
            .params = &.{.{ .index = 1, .go_name = "steps" }},
            .role = .{ .method = api.typeRef("Ticker") },
        }), api.function("tickerElapsed", .{ .name = "elapsed", .role = .{ .method = api.typeRef("Ticker") } }) } }),
    },
});
