const zigo = @import("zigo");
const library = @import("telemetry_hub");

pub const bindings = zigo.define(.{
    .types = .{
        .{ .type = library.TelemetryHub, .repr = .@"opaque" },
    },
    .functions = .{
        .{
            .name = "create",
            .@"fn" = library.TelemetryHub.create,
            .params = .{ "name", "capacity", "mode", "overflow_policy", "observer", "userdata" },
            .param_meta = .{
                .name = .{ .semantic = .utf8_string },
                .observer = .{ .retention = .retained },
            },
        },
        .{
            .name = "rename",
            .@"fn" = library.TelemetryHub.rename,
            .params = .{"name"},
            .param_meta = .{ .name = .{ .semantic = .utf8_string } },
        },
        .{ .name = "name", .@"fn" = library.TelemetryHub.name, .semantic = .utf8_string },
        .{ .name = "capacity", .@"fn" = library.TelemetryHub.capacity },
        .{ .name = "len", .@"fn" = library.TelemetryHub.len },
        .{ .name = "isEmpty", .@"fn" = library.TelemetryHub.isEmpty },
        .{ .name = "isFull", .@"fn" = library.TelemetryHub.isFull },
        .{ .name = "mode", .@"fn" = library.TelemetryHub.mode },
        .{ .name = "setMode", .@"fn" = library.TelemetryHub.setMode, .params = .{"mode"} },
        .{ .name = "overflowPolicy", .@"fn" = library.TelemetryHub.overflowPolicy },
        .{ .name = "setOverflowPolicy", .@"fn" = library.TelemetryHub.setOverflowPolicy, .params = .{"policy"} },
        .{ .name = "enabled", .@"fn" = library.TelemetryHub.enabled },
        .{ .name = "setEnabled", .@"fn" = library.TelemetryHub.setEnabled, .params = .{"enabled"} },
        .{ .name = "threshold", .@"fn" = library.TelemetryHub.threshold },
        .{ .name = "setThreshold", .@"fn" = library.TelemetryHub.setThreshold, .params = .{"threshold"} },
        .{ .name = "scaleFactor", .@"fn" = library.TelemetryHub.scaleFactor },
        .{ .name = "setScaleFactor", .@"fn" = library.TelemetryHub.setScaleFactor, .params = .{"factor"} },
        .{ .name = "offset", .@"fn" = library.TelemetryHub.offset },
        .{ .name = "setOffset", .@"fn" = library.TelemetryHub.setOffset, .params = .{"offset"} },
        .{ .name = "push", .@"fn" = library.TelemetryHub.push, .params = .{ "id", "value" } },
        .{ .name = "pushWithSeverity", .@"fn" = library.TelemetryHub.pushWithSeverity, .params = .{ "id", "value", "severity" } },
        .{ .name = "pushBatch", .@"fn" = library.TelemetryHub.pushBatch, .params = .{"values"} },
        .{ .name = "process", .@"fn" = library.TelemetryHub.process, .params = .{"limit"} },
        .{ .name = "processAll", .@"fn" = library.TelemetryHub.processAll },
        .{ .name = "clear", .@"fn" = library.TelemetryHub.clear },
        .{ .name = "resetStatistics", .@"fn" = library.TelemetryHub.resetStatistics },
        .{ .name = "accepted", .@"fn" = library.TelemetryHub.accepted },
        .{ .name = "rejected", .@"fn" = library.TelemetryHub.rejected },
        .{ .name = "dropped", .@"fn" = library.TelemetryHub.dropped },
        .{ .name = "processed", .@"fn" = library.TelemetryHub.processed },
        .{ .name = "filtered", .@"fn" = library.TelemetryHub.filtered },
        .{ .name = "sum", .@"fn" = library.TelemetryHub.sum },
        .{ .name = "minimum", .@"fn" = library.TelemetryHub.minimum },
        .{ .name = "maximum", .@"fn" = library.TelemetryHub.maximum },
        .{ .name = "average", .@"fn" = library.TelemetryHub.average },
        .{ .name = "firstId", .@"fn" = library.TelemetryHub.firstId },
        .{ .name = "firstValue", .@"fn" = library.TelemetryHub.firstValue },
        .{ .name = "lastId", .@"fn" = library.TelemetryHub.lastId },
        .{ .name = "lastValue", .@"fn" = library.TelemetryHub.lastValue },
        .{ .name = "lastSeverity", .@"fn" = library.TelemetryHub.lastSeverity },
        .{ .name = "countAbove", .@"fn" = library.TelemetryHub.countAbove, .params = .{"boundary"} },
        .{ .name = "countBelow", .@"fn" = library.TelemetryHub.countBelow, .params = .{"boundary"} },
        .{ .name = "containsAbove", .@"fn" = library.TelemetryHub.containsAbove, .params = .{"boundary"} },
        .{ .name = "containsBelow", .@"fn" = library.TelemetryHub.containsBelow, .params = .{"boundary"} },
        .{ .name = "scaleValues", .@"fn" = library.TelemetryHub.scaleValues, .params = .{"factor"} },
        .{ .name = "offsetValues", .@"fn" = library.TelemetryHub.offsetValues, .params = .{"delta"} },
        .{ .name = "clampValues", .@"fn" = library.TelemetryHub.clampValues, .params = .{ "lower", "upper" } },
        .{ .name = "absoluteValues", .@"fn" = library.TelemetryHub.absoluteValues },
        .{ .name = "negateValues", .@"fn" = library.TelemetryHub.negateValues },
        .{ .name = "deinit", .@"fn" = library.TelemetryHub.deinit },
        .{ .name = "liveHubs", .@"fn" = library.liveHubs },
    },
});
