// Code generated by zigo. DO NOT EDIT.
package pipeline

import (
	"runtime"

	"example.com/zigo/pipeline/internal/raw"
)

// NewIntBatch creates a caller-owned IntBatch.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewIntBatch() (*IntBatch, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.IntBatchCreate()
	if code != 0 {
		return nil, errorForCode("NewIntBatch", code)
	}
	return newIntBatch(result), nil
}

// Push invokes the bound Zig IntBatch.push operation.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (i *IntBatch) Push(value int32) error {
	if i != nil {
		i.mu.RLock()
		defer i.mu.RUnlock()
	}
	defer runtime.KeepAlive(i)
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("IntBatch.Push receiver", i)
	if err != nil {
		return err
	}
	code := raw.IntBatchPush(ptr, value)
	if code != 0 {
		return errorForCode("IntBatch.Push", code)
	}
	return nil
}

// Len invokes the bound Zig IntBatch.len operation.
// It returns *HandleError if a required handle is nil or closed.
func (i *IntBatch) Len() (uint, error) {
	if i != nil {
		i.mu.RLock()
		defer i.mu.RUnlock()
	}
	defer runtime.KeepAlive(i)
	ptr, err := zigoCheckedPointer("IntBatch.Len receiver", i)
	if err != nil {
		return 0, err
	}
	return raw.IntBatchLen(ptr), nil
}

// NewFloatBatch creates a caller-owned FloatBatch.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewFloatBatch() (*FloatBatch, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.FloatBatchCreate()
	if code != 0 {
		return nil, errorForCode("NewFloatBatch", code)
	}
	return newFloatBatch(result), nil
}

// Push invokes the bound Zig FloatBatch.push operation.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (f *FloatBatch) Push(value float64) error {
	if f != nil {
		f.mu.RLock()
		defer f.mu.RUnlock()
	}
	defer runtime.KeepAlive(f)
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("FloatBatch.Push receiver", f)
	if err != nil {
		return err
	}
	code := raw.FloatBatchPush(ptr, value)
	if code != 0 {
		return errorForCode("FloatBatch.Push", code)
	}
	return nil
}

// Len invokes the bound Zig FloatBatch.len operation.
// It returns *HandleError if a required handle is nil or closed.
func (f *FloatBatch) Len() (uint, error) {
	if f != nil {
		f.mu.RLock()
		defer f.mu.RUnlock()
	}
	defer runtime.KeepAlive(f)
	ptr, err := zigoCheckedPointer("FloatBatch.Len receiver", f)
	if err != nil {
		return 0, err
	}
	return raw.FloatBatchLen(ptr), nil
}

// NewPipeline creates a caller-owned Pipeline.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func NewPipeline(name string, mode Mode, callback PipelineCallback) (*Pipeline, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	callbackHandle := newPipelineCallbackHandle(callback)
	result, code := raw.PipelineCreate([]byte(name), uint32(mode), uintptr(callbackHandle))
	zigoRethrowCallbackPanic("NewPipeline", callbackHandle)
	if code != 0 {
		deleteCallbackHandle(callbackHandle)
		return nil, errorForCode("NewPipeline", code)
	}
	return newPipeline(result, []zigoCallbackHandle{callbackHandle}), nil
}

// Process invokes the bound Zig Pipeline.process operation.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) Process(values []int32) (int64, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Pipeline.Process receiver", p)
	if err != nil {
		return 0, err
	}
	result, code := raw.PipelineProcess(ptr, values)
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.Process", handle)
	}
	if code != 0 {
		return 0, errorForCode("Pipeline.Process", code)
	}
	return result, nil
}

// Name invokes the bound Zig Pipeline.name operation.
// It returns *HandleError if a required handle is nil or closed.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) Name() (string, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	ptr, err := zigoCheckedPointer("Pipeline.Name receiver", p)
	if err != nil {
		return "", err
	}
	result := raw.PipelineName(ptr)
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.Name", handle)
	}
	return string(result), nil
}

// Mode invokes the bound Zig Pipeline.mode operation.
// It returns *HandleError if a required handle is nil or closed.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) Mode() (Mode, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	ptr, err := zigoCheckedPointer("Pipeline.Mode receiver", p)
	if err != nil {
		return 0, err
	}
	result := raw.PipelineMode(ptr)
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.Mode", handle)
	}
	return Mode(result), nil
}

// SetEnabled invokes the bound Zig Pipeline.setEnabled operation.
// It returns *HandleError if a required handle is nil or closed.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) SetEnabled(enabled bool) (bool, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	ptr, err := zigoCheckedPointer("Pipeline.SetEnabled receiver", p)
	if err != nil {
		return false, err
	}
	result := raw.PipelineSetEnabled(ptr, boolToUint8(enabled))
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.SetEnabled", handle)
	}
	return result != 0, nil
}

// Processed invokes the bound Zig Pipeline.processed operation.
// It returns *HandleError if a required handle is nil or closed.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) Processed() (uint, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	ptr, err := zigoCheckedPointer("Pipeline.Processed receiver", p)
	if err != nil {
		return 0, err
	}
	result := raw.PipelineProcessed(ptr)
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.Processed", handle)
	}
	return result, nil
}

// Total invokes the bound Zig Pipeline.total operation.
// It returns *HandleError if a required handle is nil or closed.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (p *Pipeline) Total() (int64, error) {
	if p != nil {
		p.mu.RLock()
		defer p.mu.RUnlock()
	}
	defer runtime.KeepAlive(p)
	ptr, err := zigoCheckedPointer("Pipeline.Total receiver", p)
	if err != nil {
		return 0, err
	}
	result := raw.PipelineTotal(ptr)
	for _, handle := range p.callbackHandles {
		zigoRethrowCallbackPanic("Pipeline.Total", handle)
	}
	return result, nil
}

// LiveBytes invokes the bound Zig liveBytes operation.
func LiveBytes() uint {
	return raw.LiveBytes()
}

// CompressionBound invokes the bound Zig compressionBound operation.
func CompressionBound(sourceLen uint) uint {
	return raw.CompressionBound(sourceLen)
}
