// Code generated by zigo. DO NOT EDIT.
package pipeline

import (
	"runtime/cgo"
	"sync"
	"sync/atomic"
	"unsafe"
)

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
	zigoLocker() *sync.RWMutex
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return zigoCheckedPointer(operation, value)
}

// zigoReadLock holds the owner's read lock for the rest of the call, so a
// concurrent Close cannot release the handle between the pointer check and
// the native call. Use it as `defer zigoReadLock(receiver)()`. A borrowed
// ref delegates to its parent's lock; a nil receiver or a ref without a
// parent locks nothing.
func zigoReadLock(value zigoHandle) func() {
	mu := value.zigoLocker()
	if mu == nil {
		return func() {}
	}
	mu.RLock()
	return mu.RUnlock
}

// PipelineCallback is the Go callback signature accepted by the generated binding.
type PipelineCallback func(int32) int32

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var activeCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func newPipelineCallbackHandle(value PipelineCallback) zigoCallbackHandle {
	stored := (func(int32) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func deleteCallbackHandle(handle zigoCallbackHandle) {
	handle.Delete()
	activeCallbackHandles.Add(-1)
}

func activeCallbackHandleCount() int64 { return activeCallbackHandles.Load() }
