// Code generated by zigo. DO NOT EDIT.

package model

import (
	"unsafe"

	"example.com/zigo/packages/internal/raw"
)

// Point mirrors the Zig `extern struct` of the same name.
type Point struct {
	// X corresponds to the Zig field x.
	X int32
	// Y corresponds to the Zig field y.
	Y int32
}

// Point is reinterpreted as raw.PointData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(Point{})-unsafe.Sizeof(raw.PointData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(Point{}.X)-unsafe.Offsetof(raw.PointData{}.X)]
var _ = [1]struct{}{}[unsafe.Offsetof(Point{}.Y)-unsafe.Offsetof(raw.PointData{}.Y)]
