// Code generated by zigo. DO NOT EDIT.

// Package stream provides Go bindings generated by zigo.
package stream

import (
	"io"
	"runtime"

	"example.com/zigo/stream/internal/raw"
)


// Dump calls the Zig function Document.dump.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (d *Document) Dump(w io.Writer) error {
	if w == nil {
		return &StreamError{Operation: "Document.Dump", Parameter: "w", Err: ErrNilStream}
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Document.Dump receiver", d)
	if err != nil {
		return err
	}
	defer d.zigoRelease()
	wHandle := newZigoWriterHandle(w)
	defer deleteCallbackHandle(wHandle)
	code := raw.DocumentDump(ptr, uintptr(wHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("Document.Dump", wHandle)
	}
	if err := zigoStreamError("Document.Dump", "w", wHandle); err != nil {
		return err
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Document.Dump", code), d)
	}
	return nil
}

// Load calls the Zig function Document.load.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (d *Document) Load(r io.Reader) (uint, error) {
	if r == nil {
		return 0, &StreamError{Operation: "Document.Load", Parameter: "r", Err: ErrNilStream}
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Document.Load receiver", d)
	if err != nil {
		return 0, err
	}
	defer d.zigoRelease()
	rHandle := newZigoReaderHandle(r)
	defer deleteCallbackHandle(rHandle)
	rData := zigoReaderBytes(r)
	result, code := raw.DocumentLoad(ptr, uintptr(rHandle), rData)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("Document.Load", rHandle)
	}
	if err := zigoStreamError("Document.Load", "r", rHandle); err != nil {
		return 0, err
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Document.Load", code), d)
	}
	return result, nil
}

// Banner calls the Zig function banner.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func Banner(out io.Writer, width int32) error {
	if out == nil {
		return &StreamError{Operation: "Banner", Parameter: "out", Err: ErrNilStream}
	}
	outHandle := newZigoWriterHandle(out)
	defer deleteCallbackHandle(outHandle)
	raw.Banner(uintptr(outHandle), width)
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("Banner", outHandle)
	}
	if err := zigoStreamError("Banner", "out", outHandle); err != nil {
		return err
	}
	return nil
}

// Write writes to the stream Sink.writer() hands out, satisfying io.Writer.
// The stream is fetched from the receiver on every call and never stored.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (s *Sink) Write(bytes []byte) (int, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Sink.Write receiver", s)
	if err != nil {
		return 0, err
	}
	defer s.zigoRelease()
	result, code := raw.SinkWrite(ptr, bytes)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Sink.Write", code), s)
	}
	return result, nil
}

// Flush flushes the stream Sink.writer() hands out, satisfying io.Writer.
// The stream is fetched from the receiver on every call and never stored.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (s *Sink) Flush() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Sink.Flush receiver", s)
	if err != nil {
		return err
	}
	defer s.zigoRelease()
	code := raw.SinkFlush(ptr)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Sink.Flush", code), s)
	}
	return nil
}

// Read reads from the stream Sink.reader() hands out, satisfying io.Reader.
// The stream is fetched from the receiver on every call and never stored.
// The end of the stream is reported as io.EOF.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (s *Sink) Read(buffer []byte) (int, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Sink.Read receiver", s)
	if err != nil {
		return 0, err
	}
	defer s.zigoRelease()
	result, code := raw.SinkRead(ptr, buffer)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Sink.Read", code), s)
	}
	if result == 0 {
		return 0, io.EOF
	}
	return result, nil
}
