// Code generated by zigo. DO NOT EDIT.

package terminal

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/terminal/internal/raw"
)

// Terminal is a caller-owned native handle. Call Close when it is no longer needed.
type Terminal struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins t open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (t *Terminal) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if t == nil {
		return nil, &HandleError{Operation: operation}
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.closed || t.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if t.poison != nil {
		return nil, t.poison.poisoned(operation)
	}
	t.active++
	return t.ptr, nil
}

func (t *Terminal) zigoRelease() {
	if t == nil {
		return
	}
	t.mu.Lock()
	t.active--
	state, release := t.zigoTakeLocked()
	t.mu.Unlock()
	if release {
		zigoCleanupTerminal(state)
	}
}

// zigoPoison marks t unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (t *Terminal) zigoPoison(cause *NativePanicError) {
	if t == nil {
		return
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.poison == nil {
		t.poison = cause
		t.cleanup.Stop()
	}
}

type zigoTerminalCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewTerminal(ptr unsafe.Pointer) *Terminal {
	value := &Terminal{ptr: ptr}
	state := zigoTerminalCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupTerminal, state)
	return value
}

func zigoCleanupTerminal(state zigoTerminalCleanupState) {
	if state.ptr != nil {
		raw.TerminalFreeTerminal(state.ptr)
	}
}

// Close releases the native Terminal resources. It is safe to call more than once.
// The error result is always nil; it exists so Terminal satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (t *Terminal) Close() error {
	if t == nil {
		return nil
	}
	t.mu.Lock()
	if t.closed {
		t.mu.Unlock()
		return nil
	}
	t.closed = true
	t.cleanup.Stop()
	state, release := t.zigoTakeLocked()
	t.mu.Unlock()
	if release {
		zigoCleanupTerminal(state)
	}
	runtime.KeepAlive(t)
	return nil
}

// zigoTakeLocked hands out what is left to release once t is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (t *Terminal) zigoTakeLocked() (zigoTerminalCleanupState, bool) {
	if !t.closed || t.active != 0 || t.ptr == nil {
		return zigoTerminalCleanupState{}, false
	}
	state := zigoTerminalCleanupState{ptr: t.ptr}
	t.ptr = nil
	if t.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Snapshot is a caller-owned native handle. Call Close when it is no longer needed.
type Snapshot struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins s open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (s *Snapshot) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed || s.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if s.poison != nil {
		return nil, s.poison.poisoned(operation)
	}
	s.active++
	return s.ptr, nil
}

func (s *Snapshot) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshot(state)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Snapshot) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
}

type zigoSnapshotCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewSnapshot(ptr unsafe.Pointer) *Snapshot {
	value := &Snapshot{ptr: ptr}
	state := zigoSnapshotCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSnapshot, state)
	return value
}

func zigoCleanupSnapshot(state zigoSnapshotCleanupState) {
	if state.ptr != nil {
		raw.SnapshotFreeSnapshot(state.ptr)
	}
}

// Close releases the native Snapshot resources. It is safe to call more than once.
// The error result is always nil; it exists so Snapshot satisfies io.Closer.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Snapshot) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSnapshot(state)
	}
	runtime.KeepAlive(s)
	return nil
}

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Snapshot) zigoTakeLocked() (zigoSnapshotCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSnapshotCleanupState{}, false
	}
	state := zigoSnapshotCleanupState{ptr: s.ptr}
	s.ptr = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}
