// Code generated by zigo. DO NOT EDIT.

// Package fieldaccess provides Go bindings generated by zigo.
package fieldaccess

import "example.com/zigo/fieldaccess/internal/raw"


// CursorX returns the Zig field Terminal.screen.cursor.x.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) CursorX() (uint16, error) {
	ptr, err := zigoCheckedPointer("Terminal.CursorX receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TerminalCursorX(ptr)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(zigoErrorForCode("Terminal.CursorX", code), t)
	}
	return result, nil
}

// CursorVisible: Reports whether the cursor is visible.
// Zig field: Terminal.screen.cursor.visible.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) CursorVisible() (bool, error) {
	ptr, err := zigoCheckedPointer("Terminal.CursorVisible receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TerminalCursorVisible(ptr)
	if code != 0 {
		return false, zigoPoisonAfterPanic(zigoErrorForCode("Terminal.CursorVisible", code), t)
	}
	return result != 0, nil
}

// SetCursorStyle sets the Zig field Terminal.screen.cursor.style.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) SetCursorStyle(v CursorStyle) error {
	ptr, err := zigoCheckedPointer("Terminal.SetCursorStyle receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TerminalSetCursorStyle(ptr, uint8(v))
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("Terminal.SetCursorStyle", code), t)
	}
	return nil
}

// SetCursorX sets the Zig field Terminal.screen.cursor.x.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) SetCursorX(v uint16) error {
	if v > 4095 {
		return &RangeError{Operation: "Terminal.SetCursorX", Parameter: "v", Type: "u12"}
	}
	ptr, err := zigoCheckedPointer("Terminal.SetCursorX receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TerminalSetCursorX(ptr, v)
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("Terminal.SetCursorX", code), t)
	}
	return nil
}

// CharsetSingleShift: Reports the pending single shift, if any.
// Zig field: Terminal.screen.charset.single_shift.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) CharsetSingleShift() (CursorStyle, bool, error) {
	ptr, err := zigoCheckedPointer("Terminal.CharsetSingleShift receiver", t)
	if err != nil {
		return 0, false, err
	}
	defer t.zigoRelease()
	result, zigoHas, code := raw.TerminalCharsetSingleShift(ptr)
	if code != 0 {
		return 0, false, zigoPoisonAfterPanic(zigoErrorForCode("Terminal.CharsetSingleShift", code), t)
	}
	return CursorStyle(result), zigoHas, nil
}

// Scrollback returns the Zig field Terminal.scrollback.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) Scrollback() (uint16, bool, error) {
	ptr, err := zigoCheckedPointer("Terminal.Scrollback receiver", t)
	if err != nil {
		return 0, false, err
	}
	defer t.zigoRelease()
	result, zigoHas, code := raw.TerminalScrollback(ptr)
	if code != 0 {
		return 0, false, zigoPoisonAfterPanic(zigoErrorForCode("Terminal.Scrollback", code), t)
	}
	return result, zigoHas, nil
}

// SetScrollback sets the Zig field Terminal.scrollback.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) SetScrollback(v *uint16) error {
	ptr, err := zigoCheckedPointer("Terminal.SetScrollback receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TerminalSetScrollback(ptr, v)
	if code != 0 {
		return zigoPoisonAfterPanic(zigoErrorForCode("Terminal.SetScrollback", code), t)
	}
	return nil
}

// Title returns the Zig field Terminal.title.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) Title() (string, error) {
	ptr, err := zigoCheckedPointer("Terminal.Title receiver", t)
	if err != nil {
		return "", err
	}
	defer t.zigoRelease()
	result, code := raw.TerminalTitle(ptr)
	if code != 0 {
		return "", zigoPoisonAfterPanic(zigoErrorForCode("Terminal.Title", code), t)
	}
	return result, nil
}

// Palette returns the Zig field Terminal.palette.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) Palette() ([]uint32, error) {
	ptr, err := zigoCheckedPointer("Terminal.Palette receiver", t)
	if err != nil {
		return nil, err
	}
	defer t.zigoRelease()
	result, code := raw.TerminalPalette(ptr)
	if code != 0 {
		return nil, zigoPoisonAfterPanic(zigoErrorForCode("Terminal.Palette", code), t)
	}
	return result, nil
}
