// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);

export fn zg_int_batch_create_impl(out_result: **target.IntBatch) i32 {
    const result = target.IntBatch.create() catch |err| return switch (err) {
        error.OutOfMemory => 1,
    };
    out_result.* = result;
    return 0;
}
export fn zg_int_batch_len_impl(self: *target.IntBatch, out_result: *usize) i32 {
    const result = target.IntBatch.len(self);
    out_result.* = result;
    return 0;
}
export fn zg_int_batch_clear_impl(self: *target.IntBatch, keep: usize) i32 {
    target.IntBatch.clear(self, keep) catch |err| return switch (err) {
        error.OutOfRange => 2,
    };
    return 0;
}
export fn zg_int_batch_push_impl(self: *target.IntBatch, value: i32) i32 {
    target.IntBatch.push(self, value);
    return 0;
}
export fn zg_int_batch_deinit_impl(self: *target.IntBatch) i32 {
    target.IntBatch.deinit(self);
    return 0;
}
export fn zg_float_batch_create_impl(out_result: **target.FloatBatch) i32 {
    const result = target.FloatBatch.create() catch |err| return switch (err) {
        error.OutOfMemory => 1,
    };
    out_result.* = result;
    return 0;
}
export fn zg_float_batch_len_impl(self: *target.FloatBatch, out_result: *usize) i32 {
    const result = target.FloatBatch.len(self);
    out_result.* = result;
    return 0;
}
export fn zg_float_batch_clear_impl(self: *target.FloatBatch, retain: usize) i32 {
    target.FloatBatch.clear(self, retain) catch |err| return switch (err) {
        error.OutOfRange => 2,
    };
    return 0;
}
export fn zg_float_batch_push_impl(self: *target.FloatBatch, value: f64) i32 {
    target.FloatBatch.push(self, value);
    return 0;
}
export fn zg_float_batch_deinit_impl(self: *target.FloatBatch) i32 {
    target.FloatBatch.deinit(self);
    return 0;
}
export fn zg_window_size_impl(self: *target.Window, out_result: *usize) i32 {
    const result = target.Window.size(self);
    out_result.* = result;
    return 0;
}
export fn zg_int_batch_window_impl(self: *target.IntBatch, out_result: **target.Window) i32 {
    const result = target.IntBatch.window(self);
    out_result.* = result;
    return 0;
}
