// Code generated by zigo. DO NOT EDIT.

//! The native objects this binding hands out, each owning its own
//! lifetime.

use crate::raw;
use crate::Error;

/// Owns a native `Context`.
///
/// The native object is released when this value is dropped, so there is
/// no close call to make and no closed state to guard against.
///
/// Neither `Send` nor `Sync`, which is the honest default: whether the
/// bound library's `Context` may cross threads is a fact about that library
/// and zigo does not record it. Wrap it yourself if you know the answer.
pub struct Context {
    pub(crate) handle: *mut raw::zg_context,
}

impl Context {
    /// # Errors
    ///
    /// - [`ErrorKind::OutOfMemory`]
    pub fn new() -> Result<Self, Error> {
        let (result, code) = raw::context_create();
        if code != 0 {
            return Err(Error::from_code("create", code));
        }
        assert!(
            !result.is_null(),
            "zigo: create: the native call reported success without writing a handle"
        );
        Ok(Self { handle: result })
    }

    pub fn add(&mut self, value: i64) -> i64 {
        let (result, code) = unsafe { raw::context_add(self.handle, value) };
        if code != 0 {
            raw::panic_native("add", code);
        }
        result
    }

    /// addCopy receives a copy of the handle's value. Its mutation is visible
    /// to this call but cannot change the storage owned by the Go handle.
    pub fn add_copy(&self, value: i64) -> i64 {
        let (result, code) = unsafe { raw::context_add_copy(self.handle, value) };
        if code != 0 {
            raw::panic_native("addCopy", code);
        }
        result
    }

    pub fn borrow_view(&mut self) -> ContextView<'_> {
        let (result, code) = unsafe { raw::context_borrow_view(self.handle) };
        if code != 0 {
            raw::panic_native("borrowView", code);
        }
        assert!(
            !result.is_null(),
            "zigo: borrowView: the native call reported success without writing a handle"
        );
        ContextView { handle: result, owner: core::marker::PhantomData }
    }
}

impl Drop for Context {
    fn drop(&mut self) {
        // The status code is dropped on purpose: `Drop` cannot return
        // it, and panicking here would abort the process whenever a
        // destructor failed during another panic's unwind.
        let _ = unsafe { raw::context_deinit(self.handle) };
    }
}

/// A borrowed view into a native `ContextView`.
///
/// The lifetime is the borrow of whatever handed this out, so the
/// compiler rejects a view that outlives its owner. Go's binding can
/// only say so in a doc comment and check it at run time.
///
/// Nothing is released when this value is dropped: it points into an
/// object another handle owns.
pub struct ContextView<'owner> {
    pub(crate) handle: *mut raw::zg_context_view,
    pub(crate) owner: core::marker::PhantomData<&'owner ()>,
}

impl ContextView<'_> {
    pub fn total(&mut self) -> i64 {
        let (result, code) = unsafe { raw::context_view_total(self.handle) };
        if code != 0 {
            raw::panic_native("total", code);
        }
        result
    }
}
