// Code generated by zigo. DO NOT EDIT.

package scalar

import (
	"errors"

	"example.com/zigo/scalar/internal/raw"
)

// ErrLibraryLoad identifies a shared-library load or symbol resolution failure.
var ErrLibraryLoad = raw.ErrLibraryLoad
