// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

import (
	"errors"
	"fmt"
	"os"
	"runtime"
	"runtime/debug"
	"sync"
	"sync/atomic"
	"unsafe"

	"github.com/ebitengine/purego"
)

// DefaultLibraryName is the installed shared-library basename for the running platform.
// It is empty on platforms this backend does not support.
var DefaultLibraryName = map[string]string{"darwin": "libcallback_zigo.dylib", "linux": "libcallback_zigo.so", "windows": "callback_zigo.dll"}[runtime.GOOS]

// ErrLibraryLoad identifies a shared-library load or symbol resolution failure.
var ErrLibraryLoad = errors.New("zigo: shared library unavailable")

// LibraryError reports a native library loading or symbol resolution failure.
type LibraryError struct {
	Path      string
	Symbol    string
	Operation string
	Cause     error
}

// Error describes the failed loading operation.
func (err *LibraryError) Error() string {
	if err.Symbol != "" {
		return fmt.Sprintf("zigo: %s %q from %q: %v", err.Operation, err.Symbol, err.Path, err.Cause)
	}
	if err.Path == "" {
		return fmt.Sprintf("zigo: %s: %v", err.Operation, err.Cause)
	}
	return fmt.Sprintf("zigo: %s %q: %v", err.Operation, err.Path, err.Cause)
}

// Is reports ErrLibraryLoad so every generated error classifies the same way.
func (err *LibraryError) Is(target error) bool { return target == ErrLibraryLoad }

// Unwrap returns the platform loader error.
func (err *LibraryError) Unwrap() error { return err.Cause }

type nativeBindings struct {
	lastError               func() unsafe.Pointer
	fnFloatBufferCreate     func(*unsafe.Pointer) int32
	fnFloatBufferPush       func(unsafe.Pointer, float32)
	fnFloatBufferLen        func(unsafe.Pointer) uintptr
	fnFloatBufferDeinit     func(unsafe.Pointer)
	fnIntBufferCreate       func(*unsafe.Pointer) int32
	fnIntBufferPush         func(unsafe.Pointer, int32)
	fnIntBufferLen          func(unsafe.Pointer) uintptr
	fnIntBufferDeinit       func(unsafe.Pointer)
	fnCallbackContextCreate func(uintptr, uintptr, *unsafe.Pointer) int32
	fnCallbackContextRun    func(unsafe.Pointer, int32) int32
	fnCallbackContextDeinit func(unsafe.Pointer)
	fnPanicNow              func() int32
	fnCompressionBound      func(uintptr) uintptr
	fnApply                 func(int32, uintptr, uintptr) int32
}

type callbackEntry struct {
	mu         sync.Mutex
	cond       *sync.Cond
	value      any
	closing    bool
	active     int
	panicked   bool
	panicValue any
	panicStack []byte
}

// callbackRegistry maps a userdata token to its entry without a global lock,
// mirroring the sync.Map behind runtime/cgo.Handle on the cgo backend.
// Delete races an in-flight acquire safely through the entry's closing flag:
// an acquire either takes active++ before closing is set, in which case
// DeleteCallbackHandle waits for it to drain, or it observes closing and
// reports the token as gone.
var callbackRegistry sync.Map // uintptr -> *callbackEntry
var nextCallbackToken atomic.Uint64
var activeCallbackHandles atomic.Int64

// NewCallbackHandle stores a callback value and returns its native userdata token.
func NewCallbackHandle(value any) uintptr {
	entry := &callbackEntry{value: value}
	entry.cond = sync.NewCond(&entry.mu)
	token := uintptr(nextCallbackToken.Add(1))
	if token == 0 {
		token = uintptr(nextCallbackToken.Add(1))
	}
	callbackRegistry.Store(token, entry)
	activeCallbackHandles.Add(1)
	return token
}

// DeleteCallbackHandle releases a callback token after in-flight calls finish.
func DeleteCallbackHandle(token uintptr) {
	if token == 0 {
		return
	}
	stored, loaded := callbackRegistry.LoadAndDelete(token)
	if !loaded {
		return
	}
	entry := stored.(*callbackEntry)
	entry.mu.Lock()
	entry.closing = true
	for entry.active != 0 {
		entry.cond.Wait()
	}
	entry.value = nil
	entry.mu.Unlock()
	activeCallbackHandles.Add(-1)
}

// ActiveCallbackHandleCount reports the number of live callback tokens.
func ActiveCallbackHandleCount() int64 { return activeCallbackHandles.Load() }

// record keeps the first panic a callback raised until the generated caller takes it.
func (entry *callbackEntry) record(value any) {
	entry.mu.Lock()
	defer entry.mu.Unlock()
	if entry.panicked {
		return
	}
	entry.panicked = true
	entry.panicValue = value
	entry.panicStack = debug.Stack()
}

// TakeCallbackPanic returns and clears the panic the callback behind token recorded.
func TakeCallbackPanic(token uintptr) (any, []byte, bool) {
	stored, loaded := callbackRegistry.Load(token)
	if !loaded {
		return nil, nil, false
	}
	entry := stored.(*callbackEntry)
	entry.mu.Lock()
	defer entry.mu.Unlock()
	if !entry.panicked {
		return nil, nil, false
	}
	value, stack := entry.panicValue, entry.panicStack
	entry.panicValue, entry.panicStack, entry.panicked = nil, nil, false
	return value, stack, true
}

func acquireCallback(token uintptr) (*callbackEntry, any, bool) {
	stored, loaded := callbackRegistry.Load(token)
	if !loaded {
		return nil, nil, false
	}
	entry := stored.(*callbackEntry)
	entry.mu.Lock()
	if entry.closing {
		entry.mu.Unlock()
		return nil, nil, false
	}
	entry.active++
	value := entry.value
	entry.mu.Unlock()
	return entry, value, true
}

func releaseCallback(entry *callbackEntry) {
	entry.mu.Lock()
	entry.active--
	if entry.closing && entry.active == 0 {
		entry.cond.Broadcast()
	}
	entry.mu.Unlock()
}

// callbackResult widens a signed 32-bit callback result to the uintptr
// every dispatcher must return. The native caller declares the callback as
// returning int32_t and reads only the low word, so the value round-trips.
func callbackResult(value int32) uintptr { return uintptr(uint32(value)) }

var callbackPointers [1]uintptr
var callbackDispatchersOnce sync.Once

func ensureCallbackDispatchers() {
	callbackDispatchersOnce.Do(func() {
		callbackPointers[0] = purego.NewCallback(func(p0 int32, p1 uint) (result uintptr) {
			entry, stored, ok := acquireCallback(uintptr(p1))
			if !ok {
				return callbackResult(-4)
			}
			defer releaseCallback(entry)
			defer func() {
				if value := recover(); value != nil {
					entry.record(value)
					result = callbackResult(-3)
				}
			}()
			callback := stored.(func(int32) int32)
			return callbackResult(callback(p0))
		})
	})
}

// CallbackPointer0 returns the permanent dispatcher for callback ABI signature 0.
func CallbackPointer0() uintptr { ensureCallbackDispatchers(); return callbackPointers[0] }

// CallbackDispatcherCount reports the number of unique callback ABI dispatchers.
func CallbackDispatcherCount() int { ensureCallbackDispatchers(); return len(callbackPointers) }

var loadedBindings atomic.Pointer[nativeBindings]
var loadMu sync.Mutex
var successfulLibraryPath string

// LibraryLoaded reports whether every required native symbol was published.
func LibraryLoaded() bool { return loadedBindings.Load() != nil }

// libraryEnvVars are consulted in order when no explicit path is given.
var libraryEnvVars = []string{"ZIGO_CALLBACK_LIBRARY_PATH", "ZIGO_LIBRARY_PATH"}

// libraryCandidates lists the paths a load attempt tries, in order.
func libraryCandidates(explicit string) []string {
	if explicit != "" {
		return []string{explicit}
	}
	candidates := make([]string, 0, 2)
	for _, name := range libraryEnvVars {
		if value := os.Getenv(name); value != "" {
			candidates = append(candidates, value)
		}
	}
	if DefaultLibraryName != "" {
		candidates = append(candidates, DefaultLibraryName)
	}
	return candidates
}

// LoadLibrary atomically loads and registers every required native symbol.
// An empty path uses the configured candidates. A failed load leaves the
// binding retryable; a successful handle is never unloaded.
func LoadLibrary(path string) error {
	loadMu.Lock()
	defer loadMu.Unlock()
	return loadLibraryLocked(path)
}

func loadLibraryLocked(explicit string) error {
	candidates := libraryCandidates(explicit)
	if len(candidates) == 0 {
		return &LibraryError{Operation: "load", Cause: errors.New("no shared-library candidate is configured for this platform; pass an explicit path")}
	}
	if loadedBindings.Load() != nil {
		for _, candidate := range candidates {
			if candidate == successfulLibraryPath {
				return nil
			}
		}
		return &LibraryError{Path: candidates[0], Operation: "load", Cause: errors.New("a different library is already loaded")}
	}
	ensureCallbackDispatchers()
	attempts := make([]error, 0, len(candidates))
	for _, candidate := range candidates {
		if err := loadCandidate(candidate); err != nil {
			attempts = append(attempts, err)
			continue
		}
		successfulLibraryPath = candidate
		return nil
	}
	// One candidate keeps the precise path and symbol of its own failure.
	if len(attempts) == 1 {
		return attempts[0]
	}
	return &LibraryError{Operation: "load", Cause: errors.Join(attempts...)}
}

// loadCandidate publishes the call surface only after every symbol resolves.
func loadCandidate(path string) error {
	handle, err := openLibrary(path)
	if err != nil {
		return &LibraryError{Path: path, Operation: "open", Cause: err}
	}
	fail := func(symbol string, cause error) error {
		closeLibrary(handle)
		return &LibraryError{Path: path, Symbol: symbol, Operation: "resolve", Cause: cause}
	}
	addrLastError, err := resolveSymbol(handle, "zg_last_error_message")
	if err != nil {
		return fail("zg_last_error_message", err)
	}
	addrFloatBufferCreate, err := resolveSymbol(handle, "zg_float_buffer_create")
	if err != nil {
		return fail("zg_float_buffer_create", err)
	}
	addrFloatBufferPush, err := resolveSymbol(handle, "zg_float_buffer_push")
	if err != nil {
		return fail("zg_float_buffer_push", err)
	}
	addrFloatBufferLen, err := resolveSymbol(handle, "zg_float_buffer_len")
	if err != nil {
		return fail("zg_float_buffer_len", err)
	}
	addrFloatBufferDeinit, err := resolveSymbol(handle, "zg_float_buffer_deinit")
	if err != nil {
		return fail("zg_float_buffer_deinit", err)
	}
	addrIntBufferCreate, err := resolveSymbol(handle, "zg_int_buffer_create")
	if err != nil {
		return fail("zg_int_buffer_create", err)
	}
	addrIntBufferPush, err := resolveSymbol(handle, "zg_int_buffer_push")
	if err != nil {
		return fail("zg_int_buffer_push", err)
	}
	addrIntBufferLen, err := resolveSymbol(handle, "zg_int_buffer_len")
	if err != nil {
		return fail("zg_int_buffer_len", err)
	}
	addrIntBufferDeinit, err := resolveSymbol(handle, "zg_int_buffer_deinit")
	if err != nil {
		return fail("zg_int_buffer_deinit", err)
	}
	addrCallbackContextCreate, err := resolveSymbol(handle, "zg_callback_context_create_purego_v2")
	if err != nil {
		return fail("zg_callback_context_create_purego_v2", err)
	}
	addrCallbackContextRun, err := resolveSymbol(handle, "zg_callback_context_run")
	if err != nil {
		return fail("zg_callback_context_run", err)
	}
	addrCallbackContextDeinit, err := resolveSymbol(handle, "zg_callback_context_deinit")
	if err != nil {
		return fail("zg_callback_context_deinit", err)
	}
	addrPanicNow, err := resolveSymbol(handle, "zg_panic_now")
	if err != nil {
		return fail("zg_panic_now", err)
	}
	addrCompressionBound, err := resolveSymbol(handle, "zg_compression_bound")
	if err != nil {
		return fail("zg_compression_bound", err)
	}
	addrApply, err := resolveSymbol(handle, "zg_apply_purego_v2")
	if err != nil {
		return fail("zg_apply_purego_v2", err)
	}
	var next nativeBindings
	purego.RegisterFunc(&next.lastError, addrLastError)
	purego.RegisterFunc(&next.fnFloatBufferCreate, addrFloatBufferCreate)
	purego.RegisterFunc(&next.fnFloatBufferPush, addrFloatBufferPush)
	purego.RegisterFunc(&next.fnFloatBufferLen, addrFloatBufferLen)
	purego.RegisterFunc(&next.fnFloatBufferDeinit, addrFloatBufferDeinit)
	purego.RegisterFunc(&next.fnIntBufferCreate, addrIntBufferCreate)
	purego.RegisterFunc(&next.fnIntBufferPush, addrIntBufferPush)
	purego.RegisterFunc(&next.fnIntBufferLen, addrIntBufferLen)
	purego.RegisterFunc(&next.fnIntBufferDeinit, addrIntBufferDeinit)
	purego.RegisterFunc(&next.fnCallbackContextCreate, addrCallbackContextCreate)
	purego.RegisterFunc(&next.fnCallbackContextRun, addrCallbackContextRun)
	purego.RegisterFunc(&next.fnCallbackContextDeinit, addrCallbackContextDeinit)
	purego.RegisterFunc(&next.fnPanicNow, addrPanicNow)
	purego.RegisterFunc(&next.fnCompressionBound, addrCompressionBound)
	purego.RegisterFunc(&next.fnApply, addrApply)
	loadedBindings.Store(&next)
	return nil
}

func bindings() *nativeBindings {
	value := loadedBindings.Load()
	if value == nil {
		panic("zigo: native library is not loaded; call LoadLibrary first")
	}
	return value
}

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string {
	p := bindings().lastError()
	if p == nil {
		return ""
	}
	length := 0
	for *(*byte)(unsafe.Add(p, length)) != 0 {
		length++
	}
	return string(unsafe.Slice((*byte)(p), length))
}

// FloatBufferCreate calls the generated purego ABI wrapper for zg_float_buffer_create.
func FloatBufferCreate() (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnFloatBufferCreate(&outResult)
	return outResult, code
}

// FloatBufferPush calls the generated purego ABI wrapper for zg_float_buffer_push.
func FloatBufferPush(self unsafe.Pointer, value float32) {
	bindings().fnFloatBufferPush(self, value)
}

// FloatBufferLen calls the generated purego ABI wrapper for zg_float_buffer_len.
func FloatBufferLen(self unsafe.Pointer) uint {
	result := bindings().fnFloatBufferLen(self)
	return uint(result)
}

// FloatBufferDeinit calls the generated purego ABI wrapper for zg_float_buffer_deinit.
func FloatBufferDeinit(self unsafe.Pointer) {
	bindings().fnFloatBufferDeinit(self)
}

// IntBufferCreate calls the generated purego ABI wrapper for zg_int_buffer_create.
func IntBufferCreate() (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnIntBufferCreate(&outResult)
	return outResult, code
}

// IntBufferPush calls the generated purego ABI wrapper for zg_int_buffer_push.
func IntBufferPush(self unsafe.Pointer, value int32) {
	bindings().fnIntBufferPush(self, value)
}

// IntBufferLen calls the generated purego ABI wrapper for zg_int_buffer_len.
func IntBufferLen(self unsafe.Pointer) uint {
	result := bindings().fnIntBufferLen(self)
	return uint(result)
}

// IntBufferDeinit calls the generated purego ABI wrapper for zg_int_buffer_deinit.
func IntBufferDeinit(self unsafe.Pointer) {
	bindings().fnIntBufferDeinit(self)
}

// CallbackContextCreate calls the generated purego ABI wrapper for zg_callback_context_create_purego_v2.
func CallbackContextCreate(callbackCallback, callbackToken uintptr) (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnCallbackContextCreate(callbackCallback, callbackToken, &outResult)
	return outResult, code
}

// CallbackContextRun calls the generated purego ABI wrapper for zg_callback_context_run.
func CallbackContextRun(self unsafe.Pointer, value int32) int32 {
	result := bindings().fnCallbackContextRun(self, value)
	return int32(result)
}

// CallbackContextDeinit calls the generated purego ABI wrapper for zg_callback_context_deinit.
func CallbackContextDeinit(self unsafe.Pointer) {
	bindings().fnCallbackContextDeinit(self)
}

// PanicNow calls the generated purego ABI wrapper for zg_panic_now.
func PanicNow() int32 {
	code := bindings().fnPanicNow()
	return code
}

// CompressionBound calls the generated purego ABI wrapper for zg_compression_bound.
func CompressionBound(sourceLen uint) uint {
	result := bindings().fnCompressionBound(uintptr(sourceLen))
	return uint(result)
}

// Apply calls the generated purego ABI wrapper for zg_apply_purego_v2.
func Apply(value int32, callbackCallback, callbackToken uintptr) int32 {
	result := bindings().fnApply(value, callbackCallback, callbackToken)
	return int32(result)
}
