// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_flattened_options_H
#define ZIGO_flattened_options_H

#include <stddef.h>
#include <stdint.h>

typedef uint8_t zg_mode;
#define ZG_MODE_NORMAL 0
#define ZG_MODE_ALTERNATE 1

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT void zg_configure(uint8_t enabled, uint16_t options_rows, float scale, uint8_t mode, const uint32_t * limit, uint32_t rows);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_flattened_options_H
