// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);

export fn zg_new_parent_impl(out_result: **target.Parent) i32 {
    const result = target.newParent();
    out_result.* = result;
    return 0;
}
export fn zg_parent_free_parent_impl(self: *target.Parent) i32 {
    target.Parent.freeParent(self);
    return 0;
}
export fn zg_parent_view_impl(self: *target.Parent, out_result: **target.View) i32 {
    const result = target.Parent.view(self);
    out_result.* = result;
    return 0;
}
export fn zg_parent_maybe_view_impl(self: *target.Parent, out_result: *?*target.View) i32 {
    const result = target.Parent.maybeView(self);
    out_result.* = result;
    return 0;
}
export fn zg_parent_checked_view_impl(self: *target.Parent, out_result: *?*target.View) i32 {
    const result = target.Parent.checkedView(self) catch |err| return switch (err) {
        error.Missing => 1,
    };
    out_result.* = result;
    return 0;
}
export fn zg_view_touch_impl(self: *target.View, out_result: *i32) i32 {
    const result = target.View.touch(self);
    out_result.* = result;
    return 0;
}
