// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: ${SRCDIR}/../../../zig-out/lib/libcb_zigo.a
#include "zigo_cb.h"
*/
import "C"
import "runtime/cgo"
import "runtime/debug"
import "sync"
import "unsafe"

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string { return C.GoString(C.zg_last_error_message()) }

// CallbackState carries one Go callback across the native boundary, and
// the panic it raises there until the generated caller rethrows it. The
// trampoline has to recover: a panic cannot unwind native frames.
type CallbackState struct {
	Fn       any
	mu       sync.Mutex
	value    any
	stack    []byte
	panicked bool
	err      error
}

func (state *CallbackState) record(value any) {
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.panicked {
		return
	}
	state.panicked = true
	state.value = value
	state.stack = debug.Stack()
}

// TakeCallbackPanic returns and clears the panic the callback behind handle recorded.
func TakeCallbackPanic(handle cgo.Handle) (any, []byte, bool) {
	state := handle.Value().(*CallbackState)
	state.mu.Lock()
	defer state.mu.Unlock()
	if !state.panicked {
		return nil, nil, false
	}
	value, stack := state.value, state.stack
	state.value, state.stack, state.panicked = nil, nil, false
	return value, stack, true
}

// recordErr keeps the first error the Go side reported -- a stream that
// failed to write or read, or a callback that returned one -- until the
// generated caller takes it. Later crossings are not asked: once a stream
// has failed the adapter stops using it.
func (state *CallbackState) recordErr(err error) {
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.err == nil {
		state.err = err
	}
}

// TakeCallbackError returns and clears the error the Go callback behind handle returned.
func TakeCallbackError(handle cgo.Handle) (error, bool) {
	state := handle.Value().(*CallbackState)
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.err == nil {
		return nil, false
	}
	err := state.err
	state.err = nil
	return err, true
}

//export zg_hub_create_go_callback_observer
func zg_hub_create_go_callback_observer(p0 C.int32_t, p1 C.size_t) (result C.int32_t) {
	state := cgo.Handle(p1).Value().(*CallbackState)
	defer func() {
		if value := recover(); value != nil {
			state.record(value)
			result = C.int32_t(-3)
		}
	}()
	callback := state.Fn.(func(int32) (int32, error))
	value, err := callback(int32(p0))
	if err != nil {
		state.recordErr(err)
		return C.int32_t(-5)
	}
	return C.int32_t(value)
}

//export zg_apply_go_callback_observer
func zg_apply_go_callback_observer(p0 C.int32_t, p1 C.size_t) (result C.int32_t) {
	state := cgo.Handle(p1).Value().(*CallbackState)
	defer func() {
		if value := recover(); value != nil {
			state.record(value)
			result = C.int32_t(-3)
		}
	}()
	callback := state.Fn.(func(int32) (int32, error))
	value, err := callback(int32(p0))
	if err != nil {
		state.recordErr(err)
		return C.int32_t(-5)
	}
	return C.int32_t(value)
}

// HubCreate calls the generated C ABI wrapper for zg_hub_create.
func HubCreate(observerHandle uintptr) (unsafe.Pointer, int32) {
	var outResult *C.zg_hub
	code := int32(C.zg_hub_create(C.size_t(observerHandle), &outResult))
	return unsafe.Pointer(outResult), code
}
// HubRun calls the generated C ABI wrapper for zg_hub_run.
func HubRun(self unsafe.Pointer, value int32) (int32, int32) {
	var outResult C.int32_t
	code := int32(C.zg_hub_run((*C.zg_hub)(self), C.int32_t(value), &outResult))
	return int32(outResult), code
}
// HubDeinit calls the generated C ABI wrapper for zg_hub_deinit.
func HubDeinit(self unsafe.Pointer) int32 {
	code := int32(C.zg_hub_deinit((*C.zg_hub)(self)))
	return code
}
// Apply calls the generated C ABI wrapper for zg_apply.
func Apply(value int32, observerHandle uintptr) int32 {
	return int32(C.zg_apply(C.int32_t(value), C.size_t(observerHandle)))
}
