// Code generated by zigo. DO NOT EDIT.

package palette

import (
	"encoding/json"
	"fmt"
	"strconv"
)

// Mode represents the corresponding Zig enum.
type Mode uint8

const (
	// ModeIdle corresponds to the Zig tag idle.
	ModeIdle Mode = 0
	// ModeActive corresponds to the Zig tag active.
	ModeActive Mode = 1
)

var zigoModeNames = [2]string{
	0: "idle",
	1: "active",
}

// String returns the Zig tag name.
func (value Mode) String() string {
	if value >= 0 && value <= 1 {
		return zigoModeNames[uint64(value)]
	}
	return "Mode(" + strconv.Itoa(int(value)) + ")"
}

// ModeValues returns a fresh slice of known values in declaration order.
func ModeValues() []Mode {
	return []Mode{
		ModeIdle,
		ModeActive,
	}
}

// IsKnown reports whether value is an exported tag; unknown open-enum values return false.
func (value Mode) IsKnown() bool {
	return value >= 0 && value <= 1
}

// MarshalJSON encodes Mode as its Zig tag name.
func (value Mode) MarshalJSON() ([]byte, error) { return json.Marshal(value.String()) }

// UnmarshalJSON decodes a Zig tag name written by MarshalJSON.
//
// ModeValues supplies the candidates and IsKnown decides which of them a name may
// select, so this and the membership helpers cannot disagree.
func (value *Mode) UnmarshalJSON(data []byte) error {
	var text string
	if err := json.Unmarshal(data, &text); err != nil {
		return err
	}
	for _, candidate := range ModeValues() {
		if candidate.IsKnown() && candidate.String() == text {
			*value = candidate
			return nil
		}
	}
	return fmt.Errorf("Mode: unknown value %q", text)
}

// Channel represents the corresponding Zig enum.
type Channel uint8

const (
	// ChannelLeft corresponds to the Zig tag left.
	ChannelLeft Channel = 0
	// ChannelRight corresponds to the Zig tag right.
	ChannelRight Channel = 1
)

var zigoChannelNames = [2]string{
	0: "left",
	1: "right",
}

// String returns the Zig tag name.
func (value Channel) String() string {
	if value >= 0 && value <= 1 {
		return zigoChannelNames[uint64(value)]
	}
	return "Channel(" + strconv.Itoa(int(value)) + ")"
}

// MarshalJSON encodes Channel as its Zig tag name.
func (value Channel) MarshalJSON() ([]byte, error) { return json.Marshal(value.String()) }

// UnmarshalJSON decodes a Zig tag name written by MarshalJSON.
func (value *Channel) UnmarshalJSON(data []byte) error {
	var text string
	if err := json.Unmarshal(data, &text); err != nil {
		return err
	}
	switch text {
	case "left":
		*value = ChannelLeft
	case "right":
		*value = ChannelRight
	default:
		return fmt.Errorf("Channel: unknown value %q", text)
	}
	return nil
}
