// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_stream_H
#define ZIGO_stream_H

#include <stddef.h>
#include <stdint.h>

typedef struct zg_document zg_document;
typedef struct zg_sink zg_sink;
// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT int32_t zg_document_dump(zg_document * self, size_t w_userdata);
ZIGO_EXPORT int32_t zg_document_load(zg_document * self, const uint8_t * r_data, size_t r_data_len, size_t r_userdata, size_t * out_result);
ZIGO_EXPORT void zg_banner(size_t out_userdata, int32_t width);
ZIGO_EXPORT int32_t zg_sink_write(zg_sink * self, const uint8_t * bytes_ptr, size_t bytes_len, ptrdiff_t * out_result);
ZIGO_EXPORT int32_t zg_sink_flush(zg_sink * self);
ZIGO_EXPORT int32_t zg_sink_read(zg_sink * self, uint8_t * buffer_ptr, size_t buffer_len, ptrdiff_t * out_result);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_stream_H
