// Code generated by zigo. DO NOT EDIT.

//! Named Zig enum values. The native ABI carries only their integer tags.
//! Convert to a tag with `Into`, and from a tag with `TryFrom`.
//! Closed enums reject unknown and omitted members. Open enums preserve all
//! values within the original Zig tag range, including unnamed values.
//! A native result outside the public type's domain panics after status checks.

/// A closed enum: every value of the Rust type is a named member.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i8)]
pub enum Mode {
    Fast = 1,
    LowWater = 2,
}

impl ::core::convert::From<Mode> for i8 {
    fn from(value: Mode) -> Self {
        value as Self
    }
}

impl ::core::convert::TryFrom<i8> for Mode {
    type Error = i8;

    fn try_from(value: i8) -> ::core::result::Result<Self, i8> {
        match value {
            1 => ::core::result::Result::Ok(Self::Fast),
            2 => ::core::result::Result::Ok(Self::LowWater),
            _ => ::core::result::Result::Err(value),
        }
    }
}

impl crate::Mode {
    /// The known values, in declaration order.
    pub fn values() -> &'static [Self] {
        &[Self::Fast, Self::LowWater]
    }

    /// Reports whether this value is an exported tag.
    ///
    /// Always true: a closed enum makes an unknown value unrepresentable in Rust.
    pub fn is_known(self) -> bool {
        true
    }
}

/// An open enum whose members run without a gap, so membership is a range test.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Level(i8);

// Keep the same Type::Member spelling as closed enums.
#[allow(non_upper_case_globals)]
impl Level {
    pub const Low: Self = Self(-1);
    pub const High: Self = Self(0);
}

impl ::core::convert::From<Level> for i8 {
    fn from(value: Level) -> Self {
        value.0
    }
}

impl ::core::convert::TryFrom<i8> for Level {
    type Error = i8;

    fn try_from(value: i8) -> ::core::result::Result<Self, i8> {
        ::core::result::Result::Ok(Self(value))
    }
}

impl crate::Level {
    /// The known values, in declaration order.
    pub fn values() -> &'static [Self] {
        &[Self::Low, Self::High]
    }

    /// Reports whether this value is an exported tag; an unknown open-enum value is false.
    pub fn is_known(self) -> bool {
        (-1..=0).contains(&self.0)
    }
}

/// An open enum with a hole, and `text`, so the emitter's own Display and FromStr are already there.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Signal(u8);

// Keep the same Type::Member spelling as closed enums.
#[allow(non_upper_case_globals)]
impl Signal {
    pub const Quiet: Self = Self(0);
    pub const Loud: Self = Self(7);
}

impl ::core::convert::From<Signal> for u8 {
    fn from(value: Signal) -> Self {
        value.0
    }
}

impl ::core::convert::TryFrom<u8> for Signal {
    type Error = u8;

    fn try_from(value: u8) -> ::core::result::Result<Self, u8> {
        ::core::result::Result::Ok(Self(value))
    }
}

impl ::core::fmt::Display for Signal {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self.0 {
            0 => f.write_str("quiet"),
            7 => f.write_str("loud"),
            value => write!(f, "Signal({value})"),
        }
    }
}

/// Parses public Zig member names; numeric diagnostic spellings are not accepted.
impl ::core::str::FromStr for Signal {
    type Err = &'static str;

    fn from_str(text: &str) -> ::core::result::Result<Self, &'static str> {
        match text {
            "quiet" => ::core::result::Result::Ok(Self::Quiet),
            "loud" => ::core::result::Result::Ok(Self::Loud),
            _ => ::core::result::Result::Err("invalid Signal member name"),
        }
    }
}

impl crate::Signal {
    /// The known values, in declaration order.
    pub fn values() -> &'static [Self] {
        &[Self::Quiet, Self::Loud]
    }

    /// Reports whether this value is an exported tag; an unknown open-enum value is false.
    pub fn is_known(self) -> bool {
        matches!(self.0, 0 | 7)
    }
}

/// No attachment, so the plugin writes nothing beside it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Plain {
    One = 1,
}

impl ::core::convert::From<Plain> for u8 {
    fn from(value: Plain) -> Self {
        value as Self
    }
}

impl ::core::convert::TryFrom<u8> for Plain {
    type Error = u8;

    fn try_from(value: u8) -> ::core::result::Result<Self, u8> {
        match value {
            1 => ::core::result::Result::Ok(Self::One),
            _ => ::core::result::Result::Err(value),
        }
    }
}
