// Code generated by zigo. DO NOT EDIT.

// Package receiver_name_clash provides Go bindings generated by zigo.
package receiver_name_clash

import (
	"runtime"

	"example.com/zigo/receiver-name-clash/internal/raw"
)

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName


// SetTitle calls the Zig function Terminal.setTitle.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (te *Terminal) SetTitle(t []byte) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Terminal.SetTitle receiver", te)
	if err != nil {
		return err
	}
	defer te.zigoRelease()
	code := raw.TerminalSetTitle(ptr, t)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Terminal.SetTitle", code), te)
	}
	return nil
}

// CollideAll calls the Zig function Terminal.collideAll.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (recv *Terminal) CollideAll(t int32, te int32, ter int32, term int32, termi int32, termin int32, termina int32, terminal int32) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Terminal.CollideAll receiver", recv)
	if err != nil {
		return err
	}
	defer recv.zigoRelease()
	code := raw.TerminalCollideAll(ptr, t, te, ter, term, termi, termin, termina, terminal)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Terminal.CollideAll", code), recv)
	}
	return nil
}

// Clear calls the Zig function Terminal.clear.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) Clear() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Terminal.Clear receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TerminalClear(ptr)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Terminal.Clear", code), t)
	}
	return nil
}
