// Code generated by zigo. DO NOT EDIT.

// Package cbbytes provides Go bindings generated by zigo.
package cbbytes

import "example.com/zigo/cbbytes/internal/raw"


// OnLog calls the Zig function onLog.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func OnLog(callback OnLogCallback) {
	callbackHandle := zigoNewOnLogCallbackHandle(callback)
	defer zigoDeleteCallbackHandle(callbackHandle)
	raw.OnLog(uintptr(callbackHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("OnLog", callbackHandle)
	}
}

// OnChunk calls the Zig function onChunk.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func OnChunk(callback OnChunkCallback) {
	callbackHandle := zigoNewOnChunkCallbackHandle(callback)
	defer zigoDeleteCallbackHandle(callbackHandle)
	raw.OnChunk(uintptr(callbackHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("OnChunk", callbackHandle)
	}
}
