// Code generated by zigo. DO NOT EDIT.
package config

import "example.com/zigo/config/internal/raw"


// Configure invokes the bound Zig configure operation.
func Configure(config Config) {
	raw.Configure(zigoConfigToRaw(config))
}

// DefaultConfig invokes the bound Zig defaultConfig operation.
func DefaultConfig() Config {
	return zigoConfigFromRaw(raw.DefaultConfig())
}

// Translate invokes the bound Zig translate operation.
func Translate(origin Point, dx int16) Point {
	return zigoPointFromRaw(raw.Translate(zigoPointToRaw(origin), dx))
}

// Load invokes the bound Zig load operation.
// Native failures are returned as generated error values.
func Load() (Config, error) {
	result, code := raw.Load()
	if code != 0 {
		return Config{}, errorForCode("Load", code)
	}
	return zigoConfigFromRaw(result), nil
}

// AcceptPoints invokes the bound Zig acceptPoints operation.
func AcceptPoints(values []Point) {
	valuesRaw := zigoPointSliceToRaw(values)
	raw.AcceptPoints(valuesRaw)
}

// FillPoints invokes the bound Zig fillPoints operation.
// Native failures are returned as generated error values.
func FillPoints(output []Point) (uint, error) {
	outputRaw := zigoPointSliceToRaw(output)
	result, code := raw.FillPoints(outputRaw)
	if code != 0 {
		return 0, errorForCode("FillPoints", code)
	}
	zigoPointSliceCopyFromRaw(output, outputRaw, int(result))
	return result, nil
}

// Points invokes the bound Zig points operation.
func Points() []Point {
	return zigoPointSliceFromRaw(raw.Points())
}

// PointsChecked invokes the bound Zig pointsChecked operation.
// Native failures are returned as generated error values.
func PointsChecked() ([]Point, error) {
	result, code := raw.PointsChecked()
	if code != 0 {
		return nil, errorForCode("PointsChecked", code)
	}
	return zigoPointSliceFromRaw(result), nil
}
