// Code generated by zigo. DO NOT EDIT.

package model

import "strconv"

// Key represents the corresponding Zig enum.
type Key uint8

const (
	// KeyEnter corresponds to the Zig tag enter.
	KeyEnter Key = 0
	// KeyEscape corresponds to the Zig tag escape.
	KeyEscape Key = 1
)

// String returns the Zig tag name.
func (value Key) String() string {
	switch value {
	case KeyEnter:
		return "enter"
	case KeyEscape:
		return "escape"
	default:
		return "Key(" + strconv.Itoa(int(value)) + ")"
	}
}

// Mode represents the corresponding Zig enum.
type Mode uint8

const (
	// ModeIdle corresponds to the Zig tag idle.
	ModeIdle Mode = 0
	// ModeActive corresponds to the Zig tag active.
	ModeActive Mode = 1
)

// String returns the Zig tag name.
func (value Mode) String() string {
	switch value {
	case ModeIdle:
		return "idle"
	case ModeActive:
		return "active"
	default:
		return "Mode(" + strconv.Itoa(int(value)) + ")"
	}
}
