// Code generated by zigo. DO NOT EDIT.

// Package cb provides Go bindings generated by zigo.
package cb

import (
	"runtime"

	"example.com/zigo/cb/internal/raw"
)

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName


// NewHub creates a caller-owned Hub.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
// An error a Go callback returned is returned as *CallbackError once the native call returns.
func NewHub(observer HubObserver) (*Hub, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	observerHandle := newHubObserverHandle(observer)
	result, code := raw.HubCreate(raw.CallbackPointer0(), uintptr(observerHandle))
	zigoRethrowCallbackPanic("NewHub", observerHandle)
	if err := zigoCallbackError("NewHub", "observer", observerHandle); err != nil {
		deleteCallbackHandle(observerHandle)
		return nil, err
	}
	if code != 0 {
		deleteCallbackHandle(observerHandle)
		return nil, errorForCode("NewHub", code)
	}
	return newHub(result, []zigoCallbackHandle{observerHandle}), nil
}

// Run calls the Zig function Hub.run.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
// An error a Go callback returned is returned as *CallbackError once the native call returns.
func (h *Hub) Run(value int32) (int32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Hub.Run receiver", h)
	if err != nil {
		return 0, err
	}
	defer h.zigoRelease()
	result, code := raw.HubRun(ptr, value)
	for _, handle := range h.callbackHandles {
		zigoRethrowCallbackPanic("Hub.Run", handle)
	}
	for _, handle := range h.callbackHandles {
		if err := zigoCallbackError("Hub.Run", "callback", handle); err != nil {
			return 0, err
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Hub.Run", code), h)
	}
	return result, nil
}

// Apply calls the Zig function apply.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
// An error a Go callback returned is returned as *CallbackError once the native call returns.
func Apply(value int32, observer ApplyObserverCallback) (int32, error) {
	observerHandle := newApplyObserverCallbackHandle(observer)
	defer deleteCallbackHandle(observerHandle)
	result := raw.Apply(value, raw.CallbackPointer0(), uintptr(observerHandle))
	zigoRethrowCallbackPanic("Apply", observerHandle)
	if err := zigoCallbackError("Apply", "observer", observerHandle); err != nil {
		return 0, err
	}
	return result, nil
}
