// Code generated by zigo. DO NOT EDIT.

package packedvalue

import "example.com/zigo/packedvalue/internal/raw"

// Nibble mirrors the Zig packed struct of the same name.
type Nibble struct {
	Low uint8
}

func zigoNibbleToBacking(value Nibble) uint8 {
	var result uint64
	result |= (uint64(value.Low) & 0xf) << 0
	return uint8(result)
}

// Backing returns the integer representation used by Zig.
func (value Nibble) Backing() uint8 { return zigoNibbleToBacking(value) }

// NibbleFromBacking reconstructs a Nibble from its Zig integer representation.
func NibbleFromBacking(value uint8) Nibble {
	return Nibble{
		Low: uint8(((uint64(value) >> 0) & 0xf)),
	}
}

// Flags mirrors the Zig packed struct of the same name.
type Flags struct {
	Enabled bool
	Level int8
	Mode Mode
	Nested Nibble
	Reserved uint8
}

func zigoFlagsToBacking(value Flags) uint16 {
	var result uint64
	result |= (uint64(boolToUint8(value.Enabled)) & 0x1) << 0
	result |= (uint64(value.Level) & 0x7) << 1
	result |= (uint64(value.Mode) & 0x3) << 4
	result |= (uint64(zigoNibbleToBacking(value.Nested)) & 0xf) << 6
	result |= (uint64(value.Reserved) & 0x3f) << 10
	return uint16(result)
}

// Backing returns the integer representation used by Zig.
func (value Flags) Backing() uint16 { return zigoFlagsToBacking(value) }

// FlagsFromBacking reconstructs a Flags from its Zig integer representation.
func FlagsFromBacking(value uint16) Flags {
	return Flags{
		Enabled: ((uint64(value) >> 0) & 0x1) != 0,
		Level: int8(uint8(((uint64(value) >> 1) & 0x7) << 5)) >> 5,
		Mode: Mode(((uint64(value) >> 4) & 0x3)),
		Nested: NibbleFromBacking(uint8(((uint64(value) >> 6) & 0xf))),
		Reserved: uint8(((uint64(value) >> 10) & 0x3f)),
	}
}

// Record mirrors the Zig `extern struct` of the same name.
type Record struct {
	// Flags corresponds to the Zig field flags.
	Flags Flags
	// Count corresponds to the Zig field count.
	Count uint32
}

func zigoRecordToRaw(value Record) raw.RecordData {
	return raw.RecordData{
		Flags: value.Flags.Backing(),
		Count: value.Count,
	}
}

func zigoRecordFromRaw(value raw.RecordData) Record {
	return Record{
		Flags: FlagsFromBacking(value.Flags),
		Count: value.Count,
	}
}

func zigoRecordSliceToRaw(values []Record) []raw.RecordData {
	result := make([]raw.RecordData, len(values))
	for i := range values {
		result[i] = zigoRecordToRaw(values[i])
	}
	return result
}

func zigoRecordSliceFromRaw(values []raw.RecordData) []Record {
	result := make([]Record, len(values))
	for i := range values {
		result[i] = zigoRecordFromRaw(values[i])
	}
	return result
}

func zigoRecordSliceCopyFromRaw(dst []Record, values []raw.RecordData, count int) {
	if count > len(dst) { count = len(dst) }
	if count > len(values) { count = len(values) }
	for i := 0; i < count; i++ {
		dst[i] = zigoRecordFromRaw(values[i])
	}
}
