// Code generated by zigo. DO NOT EDIT.

//go:build !windows

package native

import "github.com/ebitengine/purego"

// openLibrary opens the shared library at path and returns its handle.
func openLibrary(path string) (uintptr, error) {
	return purego.Dlopen(path, purego.RTLD_NOW|purego.RTLD_LOCAL)
}

// closeLibrary releases a handle openLibrary returned.
func closeLibrary(handle uintptr) { _ = purego.Dlclose(handle) }

// resolveSymbol reports the address symbol is published at in handle.
func resolveSymbol(handle uintptr, symbol string) (uintptr, error) {
	return purego.Dlsym(handle, symbol)
}
