// Code generated by zigo. DO NOT EDIT.
package native

import (
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"sync/atomic"
	"unsafe"

	"github.com/ebitengine/purego"
)

// DefaultLibraryName is the installed shared-library basename for the running platform.
// It is empty on platforms this backend does not support.
var DefaultLibraryName = map[string]string{"darwin": "libtelemetry_hub_zigo.dylib", "linux": "libtelemetry_hub_zigo.so", "windows": "telemetry_hub_zigo.dll"}[runtime.GOOS]

// ErrLibraryLoad identifies a shared-library load or symbol resolution failure.
var ErrLibraryLoad = errors.New("zigo: shared library unavailable")

// LibraryError reports a native library loading or symbol resolution failure.
type LibraryError struct {
	Path      string
	Symbol    string
	Operation string
	Cause     error
}

// Error describes the failed loading operation.
func (err *LibraryError) Error() string {
	if err.Symbol != "" {
		return fmt.Sprintf("zigo: %s %q from %q: %v", err.Operation, err.Symbol, err.Path, err.Cause)
	}
	if err.Path == "" {
		return fmt.Sprintf("zigo: %s: %v", err.Operation, err.Cause)
	}
	return fmt.Sprintf("zigo: %s %q: %v", err.Operation, err.Path, err.Cause)
}

// Is reports ErrLibraryLoad so every generated error classifies the same way.
func (err *LibraryError) Is(target error) bool { return target == ErrLibraryLoad }

// Unwrap returns the platform loader error.
func (err *LibraryError) Unwrap() error { return err.Cause }

type nativeBindings struct {
	lastError                       func() unsafe.Pointer
	fnTelemetryHubCreate            func(unsafe.Pointer, uintptr, uintptr, uint32, uint32, uintptr, uintptr, *unsafe.Pointer) int32
	fnTelemetryHubRename            func(unsafe.Pointer, unsafe.Pointer, uintptr) int32
	fnTelemetryHubName              func(unsafe.Pointer, *unsafe.Pointer, *uintptr)
	fnTelemetryHubCapacity          func(unsafe.Pointer) uintptr
	fnTelemetryHubLen               func(unsafe.Pointer) uintptr
	fnTelemetryHubIsEmpty           func(unsafe.Pointer) uint8
	fnTelemetryHubIsFull            func(unsafe.Pointer) uint8
	fnTelemetryHubMode              func(unsafe.Pointer) uint32
	fnTelemetryHubSetMode           func(unsafe.Pointer, uint32) uint32
	fnTelemetryHubOverflowPolicy    func(unsafe.Pointer) uint32
	fnTelemetryHubSetOverflowPolicy func(unsafe.Pointer, uint32) uint32
	fnTelemetryHubEnabled           func(unsafe.Pointer) uint8
	fnTelemetryHubSetEnabled        func(unsafe.Pointer, uint8) uint8
	fnTelemetryHubThreshold         func(unsafe.Pointer) float64
	fnTelemetryHubSetThreshold      func(unsafe.Pointer, float64) int32
	fnTelemetryHubScaleFactor       func(unsafe.Pointer) float64
	fnTelemetryHubSetScaleFactor    func(unsafe.Pointer, float64) int32
	fnTelemetryHubOffset            func(unsafe.Pointer) float64
	fnTelemetryHubSetOffset         func(unsafe.Pointer, float64) int32
	fnTelemetryHubPush              func(unsafe.Pointer, uint64, float64) int32
	fnTelemetryHubPushWithSeverity  func(unsafe.Pointer, uint64, float64, uint32) int32
	fnTelemetryHubPushBatch         func(unsafe.Pointer, unsafe.Pointer, uintptr) int32
	fnTelemetryHubProcess           func(unsafe.Pointer, uintptr, *uintptr) int32
	fnTelemetryHubProcessAll        func(unsafe.Pointer, *uintptr) int32
	fnTelemetryHubClear             func(unsafe.Pointer) uintptr
	fnTelemetryHubResetStatistics   func(unsafe.Pointer)
	fnTelemetryHubAccepted          func(unsafe.Pointer) uintptr
	fnTelemetryHubRejected          func(unsafe.Pointer) uintptr
	fnTelemetryHubDropped           func(unsafe.Pointer) uintptr
	fnTelemetryHubProcessed         func(unsafe.Pointer) uintptr
	fnTelemetryHubFiltered          func(unsafe.Pointer) uintptr
	fnTelemetryHubSum               func(unsafe.Pointer) float64
	fnTelemetryHubMinimum           func(unsafe.Pointer, *float64) int32
	fnTelemetryHubMaximum           func(unsafe.Pointer, *float64) int32
	fnTelemetryHubAverage           func(unsafe.Pointer, *float64) int32
	fnTelemetryHubFirstID           func(unsafe.Pointer, *uint64) int32
	fnTelemetryHubFirstValue        func(unsafe.Pointer, *float64) int32
	fnTelemetryHubLastID            func(unsafe.Pointer, *uint64) int32
	fnTelemetryHubLastValue         func(unsafe.Pointer, *float64) int32
	fnTelemetryHubLastSeverity      func(unsafe.Pointer, *uint32) int32
	fnTelemetryHubCountAbove        func(unsafe.Pointer, float64, *uintptr) int32
	fnTelemetryHubCountBelow        func(unsafe.Pointer, float64, *uintptr) int32
	fnTelemetryHubContainsAbove     func(unsafe.Pointer, float64, *uint8) int32
	fnTelemetryHubContainsBelow     func(unsafe.Pointer, float64, *uint8) int32
	fnTelemetryHubScaleValues       func(unsafe.Pointer, float64) int32
	fnTelemetryHubOffsetValues      func(unsafe.Pointer, float64) int32
	fnTelemetryHubClampValues       func(unsafe.Pointer, float64, float64) int32
	fnTelemetryHubAbsoluteValues    func(unsafe.Pointer)
	fnTelemetryHubNegateValues      func(unsafe.Pointer)
	fnTelemetryHubDeinit            func(unsafe.Pointer)
	fnLiveHubs                      func() uintptr
}

type callbackEntry struct {
	mu      sync.Mutex
	cond    *sync.Cond
	value   any
	closing bool
	active  int
}

// callbackRegistry maps a userdata token to its entry without a global lock,
// mirroring the sync.Map behind runtime/cgo.Handle on the cgo backend.
// Delete races an in-flight acquire safely through the entry's closing flag:
// an acquire either takes active++ before closing is set, in which case
// DeleteCallbackHandle waits for it to drain, or it observes closing and
// reports the token as gone.
var callbackRegistry sync.Map // uintptr -> *callbackEntry
var nextCallbackToken atomic.Uint64
var activeCallbackHandles atomic.Int64

// NewCallbackHandle stores a callback value and returns its native userdata token.
func NewCallbackHandle(value any) uintptr {
	entry := &callbackEntry{value: value}
	entry.cond = sync.NewCond(&entry.mu)
	token := uintptr(nextCallbackToken.Add(1))
	if token == 0 {
		token = uintptr(nextCallbackToken.Add(1))
	}
	callbackRegistry.Store(token, entry)
	activeCallbackHandles.Add(1)
	return token
}

// DeleteCallbackHandle releases a callback token after in-flight calls finish.
func DeleteCallbackHandle(token uintptr) {
	if token == 0 {
		return
	}
	stored, loaded := callbackRegistry.LoadAndDelete(token)
	if !loaded {
		return
	}
	entry := stored.(*callbackEntry)
	entry.mu.Lock()
	entry.closing = true
	for entry.active != 0 {
		entry.cond.Wait()
	}
	entry.value = nil
	entry.mu.Unlock()
	activeCallbackHandles.Add(-1)
}

// ActiveCallbackHandleCount reports the number of live callback tokens.
func ActiveCallbackHandleCount() int64 { return activeCallbackHandles.Load() }

func acquireCallback(token uintptr) (*callbackEntry, any, bool) {
	stored, loaded := callbackRegistry.Load(token)
	if !loaded {
		return nil, nil, false
	}
	entry := stored.(*callbackEntry)
	entry.mu.Lock()
	if entry.closing {
		entry.mu.Unlock()
		return nil, nil, false
	}
	entry.active++
	value := entry.value
	entry.mu.Unlock()
	return entry, value, true
}

func releaseCallback(entry *callbackEntry) {
	entry.mu.Lock()
	entry.active--
	if entry.closing && entry.active == 0 {
		entry.cond.Broadcast()
	}
	entry.mu.Unlock()
}

// callbackResult widens a signed 32-bit callback result to the uintptr
// every dispatcher must return. The native caller declares the callback as
// returning int32_t and reads only the low word, so the value round-trips.
func callbackResult(value int32) uintptr { return uintptr(uint32(value)) }

var callbackPointers [1]uintptr
var callbackDispatchersOnce sync.Once

func ensureCallbackDispatchers() {
	callbackDispatchersOnce.Do(func() {
		callbackPointers[0] = purego.NewCallback(func(p0 uint64, p1 uint64, p2 uint) (result uintptr) {
			defer func() {
				if recover() != nil {
					result = callbackResult(-3)
				}
			}()
			entry, stored, ok := acquireCallback(uintptr(p2))
			if !ok {
				return callbackResult(-4)
			}
			defer releaseCallback(entry)
			callback := stored.(func(uint64, float64) int32)
			return callbackResult(callback(p0, math.Float64frombits(p1)))
		})
	})
}

// CallbackPointer0 returns the permanent dispatcher for callback ABI signature 0.
func CallbackPointer0() uintptr { ensureCallbackDispatchers(); return callbackPointers[0] }

// CallbackDispatcherCount reports the number of unique callback ABI dispatchers.
func CallbackDispatcherCount() int { ensureCallbackDispatchers(); return len(callbackPointers) }

var loadedBindings atomic.Pointer[nativeBindings]
var loadMu sync.Mutex
var successfulLibraryPath string

// LibraryLoaded reports whether every required native symbol was published.
func LibraryLoaded() bool { return loadedBindings.Load() != nil }

var automaticLoadAttempted bool
var automaticLoadError error

// libraryEnvVars are consulted in order when no explicit path is given.
var libraryEnvVars = []string{"ZIGO_TELEMETRY_HUB_LIBRARY_PATH", "ZIGO_LIBRARY_PATH"}

// librarySearchPaths are tried after the environment, in order.
var librarySearchPaths = []string{"${EXECUTABLE_DIR}", "${EXECUTABLE_DIR}/../lib", "../../zig-out/lib", "../../zig-out/bin"}

// resolveSearchPath joins a directory entry with the platform library
// name. It returns "" when the entry cannot be formed.
func resolveSearchPath(entry string) string {
	if strings.Contains(entry, "${EXECUTABLE_DIR}") {
		executable, err := os.Executable()
		if err != nil {
			return ""
		}
		entry = strings.ReplaceAll(entry, "${EXECUTABLE_DIR}", filepath.Dir(executable))
	}
	if DefaultLibraryName == "" {
		return ""
	}
	if strings.HasSuffix(entry, filepath.Ext(DefaultLibraryName)) {
		return entry
	}
	return filepath.Join(entry, DefaultLibraryName)
}

// libraryCandidates lists the paths a load attempt tries, in order.
func libraryCandidates(explicit string) []string {
	if explicit != "" {
		return []string{explicit}
	}
	candidates := make([]string, 0, 3)
	for _, name := range libraryEnvVars {
		if value := os.Getenv(name); value != "" {
			candidates = append(candidates, value)
		}
	}
	for _, entry := range librarySearchPaths {
		if resolved := resolveSearchPath(entry); resolved != "" {
			candidates = append(candidates, resolved)
		}
	}
	if DefaultLibraryName != "" {
		candidates = append(candidates, DefaultLibraryName)
	}
	return candidates
}

// LoadLibrary atomically loads and registers every required native symbol.
// An empty path uses the configured candidates. A failed load leaves the
// binding retryable; a successful handle is never unloaded.
func LoadLibrary(path string) error {
	loadMu.Lock()
	defer loadMu.Unlock()
	return loadLibraryLocked(path)
}

func loadLibraryLocked(explicit string) error {
	candidates := libraryCandidates(explicit)
	if len(candidates) == 0 {
		return &LibraryError{Operation: "load", Cause: errors.New("no shared-library candidate is configured for this platform; pass an explicit path")}
	}
	if loadedBindings.Load() != nil {
		for _, candidate := range candidates {
			if candidate == successfulLibraryPath {
				return nil
			}
		}
		return &LibraryError{Path: candidates[0], Operation: "load", Cause: errors.New("a different library is already loaded")}
	}
	ensureCallbackDispatchers()
	attempts := make([]error, 0, len(candidates))
	for _, candidate := range candidates {
		if err := loadCandidate(candidate); err != nil {
			attempts = append(attempts, err)
			continue
		}
		successfulLibraryPath = candidate
		return nil
	}
	// One candidate keeps the precise path and symbol of its own failure.
	if len(attempts) == 1 {
		return attempts[0]
	}
	return &LibraryError{Operation: "load", Cause: errors.Join(attempts...)}
}

// loadCandidate publishes the call surface only after every symbol resolves.
func loadCandidate(path string) error {
	handle, err := openLibrary(path)
	if err != nil {
		return &LibraryError{Path: path, Operation: "open", Cause: err}
	}
	fail := func(symbol string, cause error) error {
		closeLibrary(handle)
		return &LibraryError{Path: path, Symbol: symbol, Operation: "resolve", Cause: cause}
	}
	addrLastError, err := resolveSymbol(handle, "zg_last_error_message")
	if err != nil {
		return fail("zg_last_error_message", err)
	}
	addrTelemetryHubCreate, err := resolveSymbol(handle, "zg_telemetry_hub_create_purego_v2")
	if err != nil {
		return fail("zg_telemetry_hub_create_purego_v2", err)
	}
	addrTelemetryHubRename, err := resolveSymbol(handle, "zg_telemetry_hub_rename")
	if err != nil {
		return fail("zg_telemetry_hub_rename", err)
	}
	addrTelemetryHubName, err := resolveSymbol(handle, "zg_telemetry_hub_name")
	if err != nil {
		return fail("zg_telemetry_hub_name", err)
	}
	addrTelemetryHubCapacity, err := resolveSymbol(handle, "zg_telemetry_hub_capacity")
	if err != nil {
		return fail("zg_telemetry_hub_capacity", err)
	}
	addrTelemetryHubLen, err := resolveSymbol(handle, "zg_telemetry_hub_len")
	if err != nil {
		return fail("zg_telemetry_hub_len", err)
	}
	addrTelemetryHubIsEmpty, err := resolveSymbol(handle, "zg_telemetry_hub_is_empty")
	if err != nil {
		return fail("zg_telemetry_hub_is_empty", err)
	}
	addrTelemetryHubIsFull, err := resolveSymbol(handle, "zg_telemetry_hub_is_full")
	if err != nil {
		return fail("zg_telemetry_hub_is_full", err)
	}
	addrTelemetryHubMode, err := resolveSymbol(handle, "zg_telemetry_hub_mode")
	if err != nil {
		return fail("zg_telemetry_hub_mode", err)
	}
	addrTelemetryHubSetMode, err := resolveSymbol(handle, "zg_telemetry_hub_set_mode")
	if err != nil {
		return fail("zg_telemetry_hub_set_mode", err)
	}
	addrTelemetryHubOverflowPolicy, err := resolveSymbol(handle, "zg_telemetry_hub_overflow_policy")
	if err != nil {
		return fail("zg_telemetry_hub_overflow_policy", err)
	}
	addrTelemetryHubSetOverflowPolicy, err := resolveSymbol(handle, "zg_telemetry_hub_set_overflow_policy")
	if err != nil {
		return fail("zg_telemetry_hub_set_overflow_policy", err)
	}
	addrTelemetryHubEnabled, err := resolveSymbol(handle, "zg_telemetry_hub_enabled")
	if err != nil {
		return fail("zg_telemetry_hub_enabled", err)
	}
	addrTelemetryHubSetEnabled, err := resolveSymbol(handle, "zg_telemetry_hub_set_enabled")
	if err != nil {
		return fail("zg_telemetry_hub_set_enabled", err)
	}
	addrTelemetryHubThreshold, err := resolveSymbol(handle, "zg_telemetry_hub_threshold")
	if err != nil {
		return fail("zg_telemetry_hub_threshold", err)
	}
	addrTelemetryHubSetThreshold, err := resolveSymbol(handle, "zg_telemetry_hub_set_threshold")
	if err != nil {
		return fail("zg_telemetry_hub_set_threshold", err)
	}
	addrTelemetryHubScaleFactor, err := resolveSymbol(handle, "zg_telemetry_hub_scale_factor")
	if err != nil {
		return fail("zg_telemetry_hub_scale_factor", err)
	}
	addrTelemetryHubSetScaleFactor, err := resolveSymbol(handle, "zg_telemetry_hub_set_scale_factor")
	if err != nil {
		return fail("zg_telemetry_hub_set_scale_factor", err)
	}
	addrTelemetryHubOffset, err := resolveSymbol(handle, "zg_telemetry_hub_offset")
	if err != nil {
		return fail("zg_telemetry_hub_offset", err)
	}
	addrTelemetryHubSetOffset, err := resolveSymbol(handle, "zg_telemetry_hub_set_offset")
	if err != nil {
		return fail("zg_telemetry_hub_set_offset", err)
	}
	addrTelemetryHubPush, err := resolveSymbol(handle, "zg_telemetry_hub_push")
	if err != nil {
		return fail("zg_telemetry_hub_push", err)
	}
	addrTelemetryHubPushWithSeverity, err := resolveSymbol(handle, "zg_telemetry_hub_push_with_severity")
	if err != nil {
		return fail("zg_telemetry_hub_push_with_severity", err)
	}
	addrTelemetryHubPushBatch, err := resolveSymbol(handle, "zg_telemetry_hub_push_batch")
	if err != nil {
		return fail("zg_telemetry_hub_push_batch", err)
	}
	addrTelemetryHubProcess, err := resolveSymbol(handle, "zg_telemetry_hub_process")
	if err != nil {
		return fail("zg_telemetry_hub_process", err)
	}
	addrTelemetryHubProcessAll, err := resolveSymbol(handle, "zg_telemetry_hub_process_all")
	if err != nil {
		return fail("zg_telemetry_hub_process_all", err)
	}
	addrTelemetryHubClear, err := resolveSymbol(handle, "zg_telemetry_hub_clear")
	if err != nil {
		return fail("zg_telemetry_hub_clear", err)
	}
	addrTelemetryHubResetStatistics, err := resolveSymbol(handle, "zg_telemetry_hub_reset_statistics")
	if err != nil {
		return fail("zg_telemetry_hub_reset_statistics", err)
	}
	addrTelemetryHubAccepted, err := resolveSymbol(handle, "zg_telemetry_hub_accepted")
	if err != nil {
		return fail("zg_telemetry_hub_accepted", err)
	}
	addrTelemetryHubRejected, err := resolveSymbol(handle, "zg_telemetry_hub_rejected")
	if err != nil {
		return fail("zg_telemetry_hub_rejected", err)
	}
	addrTelemetryHubDropped, err := resolveSymbol(handle, "zg_telemetry_hub_dropped")
	if err != nil {
		return fail("zg_telemetry_hub_dropped", err)
	}
	addrTelemetryHubProcessed, err := resolveSymbol(handle, "zg_telemetry_hub_processed")
	if err != nil {
		return fail("zg_telemetry_hub_processed", err)
	}
	addrTelemetryHubFiltered, err := resolveSymbol(handle, "zg_telemetry_hub_filtered")
	if err != nil {
		return fail("zg_telemetry_hub_filtered", err)
	}
	addrTelemetryHubSum, err := resolveSymbol(handle, "zg_telemetry_hub_sum")
	if err != nil {
		return fail("zg_telemetry_hub_sum", err)
	}
	addrTelemetryHubMinimum, err := resolveSymbol(handle, "zg_telemetry_hub_minimum")
	if err != nil {
		return fail("zg_telemetry_hub_minimum", err)
	}
	addrTelemetryHubMaximum, err := resolveSymbol(handle, "zg_telemetry_hub_maximum")
	if err != nil {
		return fail("zg_telemetry_hub_maximum", err)
	}
	addrTelemetryHubAverage, err := resolveSymbol(handle, "zg_telemetry_hub_average")
	if err != nil {
		return fail("zg_telemetry_hub_average", err)
	}
	addrTelemetryHubFirstID, err := resolveSymbol(handle, "zg_telemetry_hub_first_id")
	if err != nil {
		return fail("zg_telemetry_hub_first_id", err)
	}
	addrTelemetryHubFirstValue, err := resolveSymbol(handle, "zg_telemetry_hub_first_value")
	if err != nil {
		return fail("zg_telemetry_hub_first_value", err)
	}
	addrTelemetryHubLastID, err := resolveSymbol(handle, "zg_telemetry_hub_last_id")
	if err != nil {
		return fail("zg_telemetry_hub_last_id", err)
	}
	addrTelemetryHubLastValue, err := resolveSymbol(handle, "zg_telemetry_hub_last_value")
	if err != nil {
		return fail("zg_telemetry_hub_last_value", err)
	}
	addrTelemetryHubLastSeverity, err := resolveSymbol(handle, "zg_telemetry_hub_last_severity")
	if err != nil {
		return fail("zg_telemetry_hub_last_severity", err)
	}
	addrTelemetryHubCountAbove, err := resolveSymbol(handle, "zg_telemetry_hub_count_above")
	if err != nil {
		return fail("zg_telemetry_hub_count_above", err)
	}
	addrTelemetryHubCountBelow, err := resolveSymbol(handle, "zg_telemetry_hub_count_below")
	if err != nil {
		return fail("zg_telemetry_hub_count_below", err)
	}
	addrTelemetryHubContainsAbove, err := resolveSymbol(handle, "zg_telemetry_hub_contains_above")
	if err != nil {
		return fail("zg_telemetry_hub_contains_above", err)
	}
	addrTelemetryHubContainsBelow, err := resolveSymbol(handle, "zg_telemetry_hub_contains_below")
	if err != nil {
		return fail("zg_telemetry_hub_contains_below", err)
	}
	addrTelemetryHubScaleValues, err := resolveSymbol(handle, "zg_telemetry_hub_scale_values")
	if err != nil {
		return fail("zg_telemetry_hub_scale_values", err)
	}
	addrTelemetryHubOffsetValues, err := resolveSymbol(handle, "zg_telemetry_hub_offset_values")
	if err != nil {
		return fail("zg_telemetry_hub_offset_values", err)
	}
	addrTelemetryHubClampValues, err := resolveSymbol(handle, "zg_telemetry_hub_clamp_values")
	if err != nil {
		return fail("zg_telemetry_hub_clamp_values", err)
	}
	addrTelemetryHubAbsoluteValues, err := resolveSymbol(handle, "zg_telemetry_hub_absolute_values")
	if err != nil {
		return fail("zg_telemetry_hub_absolute_values", err)
	}
	addrTelemetryHubNegateValues, err := resolveSymbol(handle, "zg_telemetry_hub_negate_values")
	if err != nil {
		return fail("zg_telemetry_hub_negate_values", err)
	}
	addrTelemetryHubDeinit, err := resolveSymbol(handle, "zg_telemetry_hub_deinit")
	if err != nil {
		return fail("zg_telemetry_hub_deinit", err)
	}
	addrLiveHubs, err := resolveSymbol(handle, "zg_live_hubs")
	if err != nil {
		return fail("zg_live_hubs", err)
	}
	var next nativeBindings
	purego.RegisterFunc(&next.lastError, addrLastError)
	purego.RegisterFunc(&next.fnTelemetryHubCreate, addrTelemetryHubCreate)
	purego.RegisterFunc(&next.fnTelemetryHubRename, addrTelemetryHubRename)
	purego.RegisterFunc(&next.fnTelemetryHubName, addrTelemetryHubName)
	purego.RegisterFunc(&next.fnTelemetryHubCapacity, addrTelemetryHubCapacity)
	purego.RegisterFunc(&next.fnTelemetryHubLen, addrTelemetryHubLen)
	purego.RegisterFunc(&next.fnTelemetryHubIsEmpty, addrTelemetryHubIsEmpty)
	purego.RegisterFunc(&next.fnTelemetryHubIsFull, addrTelemetryHubIsFull)
	purego.RegisterFunc(&next.fnTelemetryHubMode, addrTelemetryHubMode)
	purego.RegisterFunc(&next.fnTelemetryHubSetMode, addrTelemetryHubSetMode)
	purego.RegisterFunc(&next.fnTelemetryHubOverflowPolicy, addrTelemetryHubOverflowPolicy)
	purego.RegisterFunc(&next.fnTelemetryHubSetOverflowPolicy, addrTelemetryHubSetOverflowPolicy)
	purego.RegisterFunc(&next.fnTelemetryHubEnabled, addrTelemetryHubEnabled)
	purego.RegisterFunc(&next.fnTelemetryHubSetEnabled, addrTelemetryHubSetEnabled)
	purego.RegisterFunc(&next.fnTelemetryHubThreshold, addrTelemetryHubThreshold)
	purego.RegisterFunc(&next.fnTelemetryHubSetThreshold, addrTelemetryHubSetThreshold)
	purego.RegisterFunc(&next.fnTelemetryHubScaleFactor, addrTelemetryHubScaleFactor)
	purego.RegisterFunc(&next.fnTelemetryHubSetScaleFactor, addrTelemetryHubSetScaleFactor)
	purego.RegisterFunc(&next.fnTelemetryHubOffset, addrTelemetryHubOffset)
	purego.RegisterFunc(&next.fnTelemetryHubSetOffset, addrTelemetryHubSetOffset)
	purego.RegisterFunc(&next.fnTelemetryHubPush, addrTelemetryHubPush)
	purego.RegisterFunc(&next.fnTelemetryHubPushWithSeverity, addrTelemetryHubPushWithSeverity)
	purego.RegisterFunc(&next.fnTelemetryHubPushBatch, addrTelemetryHubPushBatch)
	purego.RegisterFunc(&next.fnTelemetryHubProcess, addrTelemetryHubProcess)
	purego.RegisterFunc(&next.fnTelemetryHubProcessAll, addrTelemetryHubProcessAll)
	purego.RegisterFunc(&next.fnTelemetryHubClear, addrTelemetryHubClear)
	purego.RegisterFunc(&next.fnTelemetryHubResetStatistics, addrTelemetryHubResetStatistics)
	purego.RegisterFunc(&next.fnTelemetryHubAccepted, addrTelemetryHubAccepted)
	purego.RegisterFunc(&next.fnTelemetryHubRejected, addrTelemetryHubRejected)
	purego.RegisterFunc(&next.fnTelemetryHubDropped, addrTelemetryHubDropped)
	purego.RegisterFunc(&next.fnTelemetryHubProcessed, addrTelemetryHubProcessed)
	purego.RegisterFunc(&next.fnTelemetryHubFiltered, addrTelemetryHubFiltered)
	purego.RegisterFunc(&next.fnTelemetryHubSum, addrTelemetryHubSum)
	purego.RegisterFunc(&next.fnTelemetryHubMinimum, addrTelemetryHubMinimum)
	purego.RegisterFunc(&next.fnTelemetryHubMaximum, addrTelemetryHubMaximum)
	purego.RegisterFunc(&next.fnTelemetryHubAverage, addrTelemetryHubAverage)
	purego.RegisterFunc(&next.fnTelemetryHubFirstID, addrTelemetryHubFirstID)
	purego.RegisterFunc(&next.fnTelemetryHubFirstValue, addrTelemetryHubFirstValue)
	purego.RegisterFunc(&next.fnTelemetryHubLastID, addrTelemetryHubLastID)
	purego.RegisterFunc(&next.fnTelemetryHubLastValue, addrTelemetryHubLastValue)
	purego.RegisterFunc(&next.fnTelemetryHubLastSeverity, addrTelemetryHubLastSeverity)
	purego.RegisterFunc(&next.fnTelemetryHubCountAbove, addrTelemetryHubCountAbove)
	purego.RegisterFunc(&next.fnTelemetryHubCountBelow, addrTelemetryHubCountBelow)
	purego.RegisterFunc(&next.fnTelemetryHubContainsAbove, addrTelemetryHubContainsAbove)
	purego.RegisterFunc(&next.fnTelemetryHubContainsBelow, addrTelemetryHubContainsBelow)
	purego.RegisterFunc(&next.fnTelemetryHubScaleValues, addrTelemetryHubScaleValues)
	purego.RegisterFunc(&next.fnTelemetryHubOffsetValues, addrTelemetryHubOffsetValues)
	purego.RegisterFunc(&next.fnTelemetryHubClampValues, addrTelemetryHubClampValues)
	purego.RegisterFunc(&next.fnTelemetryHubAbsoluteValues, addrTelemetryHubAbsoluteValues)
	purego.RegisterFunc(&next.fnTelemetryHubNegateValues, addrTelemetryHubNegateValues)
	purego.RegisterFunc(&next.fnTelemetryHubDeinit, addrTelemetryHubDeinit)
	purego.RegisterFunc(&next.fnLiveHubs, addrLiveHubs)
	loadedBindings.Store(&next)
	return nil
}

// ensureLoaded performs the one automatic load attempt. A later explicit
// call can still succeed with a different path.
func ensureLoaded() {
	loadMu.Lock()
	defer loadMu.Unlock()
	if loadedBindings.Load() != nil || automaticLoadAttempted {
		return
	}
	automaticLoadAttempted = true
	automaticLoadError = loadLibraryLocked("")
}

func bindings() *nativeBindings {
	value := loadedBindings.Load()
	if value == nil {
		ensureLoaded()
		value = loadedBindings.Load()
	}
	if value == nil {
		panic(automaticLoadError)
	}
	return value
}

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string {
	p := bindings().lastError()
	if p == nil {
		return ""
	}
	length := 0
	for *(*byte)(unsafe.Add(p, length)) != 0 {
		length++
	}
	return string(unsafe.Slice((*byte)(p), length))
}

// TelemetryHubCreate calls the generated purego ABI wrapper for zg_telemetry_hub_create_purego_v2.
func TelemetryHubCreate(inputName []uint8, maxSamples uint, initialMode uint32, overflowPolicy uint32, observerCallback, observerToken uintptr) (unsafe.Pointer, int32) {
	var inputNamePtr unsafe.Pointer
	if len(inputName) != 0 {
		inputNamePtr = unsafe.Pointer(&inputName[0])
	}
	var outResult unsafe.Pointer
	code := bindings().fnTelemetryHubCreate(inputNamePtr, uintptr(len(inputName)), uintptr(maxSamples), initialMode, overflowPolicy, observerCallback, observerToken, &outResult)
	return outResult, code
}

// TelemetryHubRename calls the generated purego ABI wrapper for zg_telemetry_hub_rename.
func TelemetryHubRename(self unsafe.Pointer, newName []uint8) int32 {
	var newNamePtr unsafe.Pointer
	if len(newName) != 0 {
		newNamePtr = unsafe.Pointer(&newName[0])
	}
	code := bindings().fnTelemetryHubRename(self, newNamePtr, uintptr(len(newName)))
	return code
}

// TelemetryHubName calls the generated purego ABI wrapper for zg_telemetry_hub_name.
func TelemetryHubName(self unsafe.Pointer) []uint8 {
	var outResultPtr unsafe.Pointer
	var outResultLen uintptr
	bindings().fnTelemetryHubName(self, &outResultPtr, &outResultLen)
	if outResultLen == 0 {
		return nil
	}
	return unsafe.Slice((*uint8)(outResultPtr), int(outResultLen))
}

// TelemetryHubCapacity calls the generated purego ABI wrapper for zg_telemetry_hub_capacity.
func TelemetryHubCapacity(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubCapacity(self)
	return uint(result)
}

// TelemetryHubLen calls the generated purego ABI wrapper for zg_telemetry_hub_len.
func TelemetryHubLen(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubLen(self)
	return uint(result)
}

// TelemetryHubIsEmpty calls the generated purego ABI wrapper for zg_telemetry_hub_is_empty.
func TelemetryHubIsEmpty(self unsafe.Pointer) uint8 {
	result := bindings().fnTelemetryHubIsEmpty(self)
	return uint8(result)
}

// TelemetryHubIsFull calls the generated purego ABI wrapper for zg_telemetry_hub_is_full.
func TelemetryHubIsFull(self unsafe.Pointer) uint8 {
	result := bindings().fnTelemetryHubIsFull(self)
	return uint8(result)
}

// TelemetryHubMode calls the generated purego ABI wrapper for zg_telemetry_hub_mode.
func TelemetryHubMode(self unsafe.Pointer) uint32 {
	result := bindings().fnTelemetryHubMode(self)
	return uint32(result)
}

// TelemetryHubSetMode calls the generated purego ABI wrapper for zg_telemetry_hub_set_mode.
func TelemetryHubSetMode(self unsafe.Pointer, newMode uint32) uint32 {
	result := bindings().fnTelemetryHubSetMode(self, newMode)
	return uint32(result)
}

// TelemetryHubOverflowPolicy calls the generated purego ABI wrapper for zg_telemetry_hub_overflow_policy.
func TelemetryHubOverflowPolicy(self unsafe.Pointer) uint32 {
	result := bindings().fnTelemetryHubOverflowPolicy(self)
	return uint32(result)
}

// TelemetryHubSetOverflowPolicy calls the generated purego ABI wrapper for zg_telemetry_hub_set_overflow_policy.
func TelemetryHubSetOverflowPolicy(self unsafe.Pointer, newPolicy uint32) uint32 {
	result := bindings().fnTelemetryHubSetOverflowPolicy(self, newPolicy)
	return uint32(result)
}

// TelemetryHubEnabled calls the generated purego ABI wrapper for zg_telemetry_hub_enabled.
func TelemetryHubEnabled(self unsafe.Pointer) uint8 {
	result := bindings().fnTelemetryHubEnabled(self)
	return uint8(result)
}

// TelemetryHubSetEnabled calls the generated purego ABI wrapper for zg_telemetry_hub_set_enabled.
func TelemetryHubSetEnabled(self unsafe.Pointer, newEnabled uint8) uint8 {
	result := bindings().fnTelemetryHubSetEnabled(self, newEnabled)
	return uint8(result)
}

// TelemetryHubThreshold calls the generated purego ABI wrapper for zg_telemetry_hub_threshold.
func TelemetryHubThreshold(self unsafe.Pointer) float64 {
	result := bindings().fnTelemetryHubThreshold(self)
	return float64(result)
}

// TelemetryHubSetThreshold calls the generated purego ABI wrapper for zg_telemetry_hub_set_threshold.
func TelemetryHubSetThreshold(self unsafe.Pointer, newThreshold float64) int32 {
	code := bindings().fnTelemetryHubSetThreshold(self, newThreshold)
	return code
}

// TelemetryHubScaleFactor calls the generated purego ABI wrapper for zg_telemetry_hub_scale_factor.
func TelemetryHubScaleFactor(self unsafe.Pointer) float64 {
	result := bindings().fnTelemetryHubScaleFactor(self)
	return float64(result)
}

// TelemetryHubSetScaleFactor calls the generated purego ABI wrapper for zg_telemetry_hub_set_scale_factor.
func TelemetryHubSetScaleFactor(self unsafe.Pointer, newFactor float64) int32 {
	code := bindings().fnTelemetryHubSetScaleFactor(self, newFactor)
	return code
}

// TelemetryHubOffset calls the generated purego ABI wrapper for zg_telemetry_hub_offset.
func TelemetryHubOffset(self unsafe.Pointer) float64 {
	result := bindings().fnTelemetryHubOffset(self)
	return float64(result)
}

// TelemetryHubSetOffset calls the generated purego ABI wrapper for zg_telemetry_hub_set_offset.
func TelemetryHubSetOffset(self unsafe.Pointer, newOffset float64) int32 {
	code := bindings().fnTelemetryHubSetOffset(self, newOffset)
	return code
}

// TelemetryHubPush calls the generated purego ABI wrapper for zg_telemetry_hub_push.
func TelemetryHubPush(self unsafe.Pointer, id uint64, value float64) int32 {
	code := bindings().fnTelemetryHubPush(self, id, value)
	return code
}

// TelemetryHubPushWithSeverity calls the generated purego ABI wrapper for zg_telemetry_hub_push_with_severity.
func TelemetryHubPushWithSeverity(self unsafe.Pointer, id uint64, value float64, severity uint32) int32 {
	code := bindings().fnTelemetryHubPushWithSeverity(self, id, value, severity)
	return code
}

// TelemetryHubPushBatch calls the generated purego ABI wrapper for zg_telemetry_hub_push_batch.
func TelemetryHubPushBatch(self unsafe.Pointer, values []float64) int32 {
	var valuesPtr unsafe.Pointer
	if len(values) != 0 {
		valuesPtr = unsafe.Pointer(&values[0])
	}
	code := bindings().fnTelemetryHubPushBatch(self, valuesPtr, uintptr(len(values)))
	return code
}

// TelemetryHubProcess calls the generated purego ABI wrapper for zg_telemetry_hub_process.
func TelemetryHubProcess(self unsafe.Pointer, limit uint) (uint, int32) {
	var outResult uintptr
	code := bindings().fnTelemetryHubProcess(self, uintptr(limit), &outResult)
	return uint(outResult), code
}

// TelemetryHubProcessAll calls the generated purego ABI wrapper for zg_telemetry_hub_process_all.
func TelemetryHubProcessAll(self unsafe.Pointer) (uint, int32) {
	var outResult uintptr
	code := bindings().fnTelemetryHubProcessAll(self, &outResult)
	return uint(outResult), code
}

// TelemetryHubClear calls the generated purego ABI wrapper for zg_telemetry_hub_clear.
func TelemetryHubClear(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubClear(self)
	return uint(result)
}

// TelemetryHubResetStatistics calls the generated purego ABI wrapper for zg_telemetry_hub_reset_statistics.
func TelemetryHubResetStatistics(self unsafe.Pointer) {
	bindings().fnTelemetryHubResetStatistics(self)
}

// TelemetryHubAccepted calls the generated purego ABI wrapper for zg_telemetry_hub_accepted.
func TelemetryHubAccepted(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubAccepted(self)
	return uint(result)
}

// TelemetryHubRejected calls the generated purego ABI wrapper for zg_telemetry_hub_rejected.
func TelemetryHubRejected(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubRejected(self)
	return uint(result)
}

// TelemetryHubDropped calls the generated purego ABI wrapper for zg_telemetry_hub_dropped.
func TelemetryHubDropped(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubDropped(self)
	return uint(result)
}

// TelemetryHubProcessed calls the generated purego ABI wrapper for zg_telemetry_hub_processed.
func TelemetryHubProcessed(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubProcessed(self)
	return uint(result)
}

// TelemetryHubFiltered calls the generated purego ABI wrapper for zg_telemetry_hub_filtered.
func TelemetryHubFiltered(self unsafe.Pointer) uint {
	result := bindings().fnTelemetryHubFiltered(self)
	return uint(result)
}

// TelemetryHubSum calls the generated purego ABI wrapper for zg_telemetry_hub_sum.
func TelemetryHubSum(self unsafe.Pointer) float64 {
	result := bindings().fnTelemetryHubSum(self)
	return float64(result)
}

// TelemetryHubMinimum calls the generated purego ABI wrapper for zg_telemetry_hub_minimum.
func TelemetryHubMinimum(self unsafe.Pointer) (float64, int32) {
	var outResult float64
	code := bindings().fnTelemetryHubMinimum(self, &outResult)
	return outResult, code
}

// TelemetryHubMaximum calls the generated purego ABI wrapper for zg_telemetry_hub_maximum.
func TelemetryHubMaximum(self unsafe.Pointer) (float64, int32) {
	var outResult float64
	code := bindings().fnTelemetryHubMaximum(self, &outResult)
	return outResult, code
}

// TelemetryHubAverage calls the generated purego ABI wrapper for zg_telemetry_hub_average.
func TelemetryHubAverage(self unsafe.Pointer) (float64, int32) {
	var outResult float64
	code := bindings().fnTelemetryHubAverage(self, &outResult)
	return outResult, code
}

// TelemetryHubFirstID calls the generated purego ABI wrapper for zg_telemetry_hub_first_id.
func TelemetryHubFirstID(self unsafe.Pointer) (uint64, int32) {
	var outResult uint64
	code := bindings().fnTelemetryHubFirstID(self, &outResult)
	return outResult, code
}

// TelemetryHubFirstValue calls the generated purego ABI wrapper for zg_telemetry_hub_first_value.
func TelemetryHubFirstValue(self unsafe.Pointer) (float64, int32) {
	var outResult float64
	code := bindings().fnTelemetryHubFirstValue(self, &outResult)
	return outResult, code
}

// TelemetryHubLastID calls the generated purego ABI wrapper for zg_telemetry_hub_last_id.
func TelemetryHubLastID(self unsafe.Pointer) (uint64, int32) {
	var outResult uint64
	code := bindings().fnTelemetryHubLastID(self, &outResult)
	return outResult, code
}

// TelemetryHubLastValue calls the generated purego ABI wrapper for zg_telemetry_hub_last_value.
func TelemetryHubLastValue(self unsafe.Pointer) (float64, int32) {
	var outResult float64
	code := bindings().fnTelemetryHubLastValue(self, &outResult)
	return outResult, code
}

// TelemetryHubLastSeverity calls the generated purego ABI wrapper for zg_telemetry_hub_last_severity.
func TelemetryHubLastSeverity(self unsafe.Pointer) (uint32, int32) {
	var outResult uint32
	code := bindings().fnTelemetryHubLastSeverity(self, &outResult)
	return outResult, code
}

// TelemetryHubCountAbove calls the generated purego ABI wrapper for zg_telemetry_hub_count_above.
func TelemetryHubCountAbove(self unsafe.Pointer, boundary float64) (uint, int32) {
	var outResult uintptr
	code := bindings().fnTelemetryHubCountAbove(self, boundary, &outResult)
	return uint(outResult), code
}

// TelemetryHubCountBelow calls the generated purego ABI wrapper for zg_telemetry_hub_count_below.
func TelemetryHubCountBelow(self unsafe.Pointer, boundary float64) (uint, int32) {
	var outResult uintptr
	code := bindings().fnTelemetryHubCountBelow(self, boundary, &outResult)
	return uint(outResult), code
}

// TelemetryHubContainsAbove calls the generated purego ABI wrapper for zg_telemetry_hub_contains_above.
func TelemetryHubContainsAbove(self unsafe.Pointer, boundary float64) (uint8, int32) {
	var outResult uint8
	code := bindings().fnTelemetryHubContainsAbove(self, boundary, &outResult)
	return outResult, code
}

// TelemetryHubContainsBelow calls the generated purego ABI wrapper for zg_telemetry_hub_contains_below.
func TelemetryHubContainsBelow(self unsafe.Pointer, boundary float64) (uint8, int32) {
	var outResult uint8
	code := bindings().fnTelemetryHubContainsBelow(self, boundary, &outResult)
	return outResult, code
}

// TelemetryHubScaleValues calls the generated purego ABI wrapper for zg_telemetry_hub_scale_values.
func TelemetryHubScaleValues(self unsafe.Pointer, factor float64) int32 {
	code := bindings().fnTelemetryHubScaleValues(self, factor)
	return code
}

// TelemetryHubOffsetValues calls the generated purego ABI wrapper for zg_telemetry_hub_offset_values.
func TelemetryHubOffsetValues(self unsafe.Pointer, delta float64) int32 {
	code := bindings().fnTelemetryHubOffsetValues(self, delta)
	return code
}

// TelemetryHubClampValues calls the generated purego ABI wrapper for zg_telemetry_hub_clamp_values.
func TelemetryHubClampValues(self unsafe.Pointer, lower float64, upper float64) int32 {
	code := bindings().fnTelemetryHubClampValues(self, lower, upper)
	return code
}

// TelemetryHubAbsoluteValues calls the generated purego ABI wrapper for zg_telemetry_hub_absolute_values.
func TelemetryHubAbsoluteValues(self unsafe.Pointer) {
	bindings().fnTelemetryHubAbsoluteValues(self)
}

// TelemetryHubNegateValues calls the generated purego ABI wrapper for zg_telemetry_hub_negate_values.
func TelemetryHubNegateValues(self unsafe.Pointer) {
	bindings().fnTelemetryHubNegateValues(self)
}

// TelemetryHubDeinit calls the generated purego ABI wrapper for zg_telemetry_hub_deinit.
func TelemetryHubDeinit(self unsafe.Pointer) {
	bindings().fnTelemetryHubDeinit(self)
}

// LiveHubs calls the generated purego ABI wrapper for zg_live_hubs.
func LiveHubs() uint {
	result := bindings().fnLiveHubs()
	return uint(result)
}
