// Code generated by zigo. DO NOT EDIT.

package cb

import "example.com/zigo/cb/internal/raw"

// ReduceReducerCallback is the Go callback signature accepted by the generated binding.
type ReduceReducerCallback func(int32, int32) int32

// VisitVisitorCallback is the Go callback signature accepted by the generated binding.
type VisitVisitorCallback func(int32, bool)

type zigoCallbackHandle = uintptr

func zigoNewReduceReducerCallbackHandle(value ReduceReducerCallback) zigoCallbackHandle {
	return raw.NewCallbackHandle((func(int32, int32) int32)(value))
}

func zigoNewVisitVisitorCallbackHandle(value VisitVisitorCallback) zigoCallbackHandle {
	return raw.NewCallbackHandle(func(p0 int32, p1 uint8) {
		value(p0, p1 != 0)
	})
}

func zigoDeleteCallbackHandle(handle zigoCallbackHandle) { raw.DeleteCallbackHandle(handle) }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 { return }
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}
