// Code generated by zigo. DO NOT EDIT.
package tagged_union

import (
	"runtime"
	"strconv"
	"sync"
	"unsafe"

	"example.com/zigo/tagged-union/internal/raw"
)

// Mode represents the corresponding Zig enum.
type Mode uint8

// ModeIdle corresponds to the Zig tag idle.
const ModeIdle Mode = 0

// ModeActive corresponds to the Zig tag active.
const ModeActive Mode = 1

// ModePaused corresponds to the Zig tag paused.
const ModePaused Mode = 2

// String returns the Zig tag name.
func (value Mode) String() string {
	switch value {
	case ModeIdle:
		return "idle"
	case ModeActive:
		return "active"
	case ModePaused:
		return "paused"
	default:
		return "Mode(" + strconv.FormatInt(int64(value), 10) + ")"
	}
}

// ValueTag represents the corresponding Zig enum.
type ValueTag uint8

// ValueTagNone corresponds to the Zig tag none.
const ValueTagNone ValueTag = 0

// ValueTagInteger corresponds to the Zig tag integer.
const ValueTagInteger ValueTag = 1

// ValueTagFlag corresponds to the Zig tag flag.
const ValueTagFlag ValueTag = 2

// ValueTagMode corresponds to the Zig tag mode.
const ValueTagMode ValueTag = 3

// ValueTagSamples corresponds to the Zig tag samples.
const ValueTagSamples ValueTag = 4

// ValueTagChild corresponds to the Zig tag child.
const ValueTagChild ValueTag = 5

// ValueTagMutableSamples corresponds to the Zig tag mutableSamples.
const ValueTagMutableSamples ValueTag = 6

// String returns the Zig tag name.
func (value ValueTag) String() string {
	switch value {
	case ValueTagNone:
		return "none"
	case ValueTagInteger:
		return "integer"
	case ValueTagFlag:
		return "flag"
	case ValueTagMode:
		return "mode"
	case ValueTagSamples:
		return "samples"
	case ValueTagChild:
		return "child"
	case ValueTagMutableSamples:
		return "mutableSamples"
	default:
		return "ValueTag(" + strconv.FormatInt(int64(value), 10) + ")"
	}
}

// SignalTag represents the corresponding Zig enum.
type SignalTag uint8

// SignalTagIdle corresponds to the Zig tag idle.
const SignalTagIdle SignalTag = 0

// SignalTagTicks corresponds to the Zig tag ticks.
const SignalTagTicks SignalTag = 1

// SignalTagLevel corresponds to the Zig tag level.
const SignalTagLevel SignalTag = 2

// SignalTagOffset corresponds to the Zig tag offset.
const SignalTagOffset SignalTag = 3

// SignalTagMode corresponds to the Zig tag mode.
const SignalTagMode SignalTag = 4

// SignalTagActive corresponds to the Zig tag active.
const SignalTagActive SignalTag = 5

// String returns the Zig tag name.
func (value SignalTag) String() string {
	switch value {
	case SignalTagIdle:
		return "idle"
	case SignalTagTicks:
		return "ticks"
	case SignalTagLevel:
		return "level"
	case SignalTagOffset:
		return "offset"
	case SignalTagMode:
		return "mode"
	case SignalTagActive:
		return "active"
	default:
		return "SignalTag(" + strconv.FormatInt(int64(value), 10) + ")"
	}
}

// Child is a caller-owned native handle. Call Close when it is no longer needed.
type Child struct {
	ptr     unsafe.Pointer
	once    sync.Once
	cleanup runtime.Cleanup
}

// ChildRef is a borrowed Child reference that remains valid only while its parent is open.
type ChildRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (c *Child) zigoPointer() unsafe.Pointer {
	if c == nil {
		return nil
	}
	return c.ptr
}

func (c *ChildRef) zigoPointer() unsafe.Pointer {
	if c == nil || c.ptr == nil {
		return nil
	}
	if parent := c.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return c.ptr
}

type childCleanupState struct {
	ptr unsafe.Pointer
}

func newChild(ptr unsafe.Pointer) *Child {
	value := &Child{ptr: ptr}
	state := childCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupChild, state)
	return value
}

func cleanupChild(state childCleanupState) {
	if state.ptr != nil {
		raw.ChildDeinit(state.ptr)
	}
}

// Close releases the native Child resources. It is safe to call more than once.
func (c *Child) Close() {
	if c == nil {
		return
	}
	c.once.Do(func() {
		c.cleanup.Stop()
		cleanupChild(childCleanupState{ptr: c.ptr})
		c.ptr = nil
	})
	runtime.KeepAlive(c)
}

// Value is a caller-owned native handle. Call Close when it is no longer needed.
type Value struct {
	ptr     unsafe.Pointer
	once    sync.Once
	cleanup runtime.Cleanup
}

// ValueRef is a borrowed Value reference that remains valid only while its parent is open.
type ValueRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (v *Value) zigoPointer() unsafe.Pointer {
	if v == nil {
		return nil
	}
	return v.ptr
}

func (v *ValueRef) zigoPointer() unsafe.Pointer {
	if v == nil || v.ptr == nil {
		return nil
	}
	if parent := v.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return v.ptr
}

type valueCleanupState struct {
	ptr unsafe.Pointer
}

func newValue(ptr unsafe.Pointer) *Value {
	value := &Value{ptr: ptr}
	state := valueCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupValue, state)
	return value
}

func cleanupValue(state valueCleanupState) {
	if state.ptr != nil {
		raw.ValueDeinit(state.ptr)
	}
}

// Close releases the native Value resources. It is safe to call more than once.
func (v *Value) Close() {
	if v == nil {
		return
	}
	v.once.Do(func() {
		v.cleanup.Stop()
		cleanupValue(valueCleanupState{ptr: v.ptr})
		v.ptr = nil
	})
	runtime.KeepAlive(v)
}

// Signal is a caller-owned native handle. Call Close when it is no longer needed.
type Signal struct {
	ptr     unsafe.Pointer
	once    sync.Once
	cleanup runtime.Cleanup
}

// SignalRef is a borrowed Signal reference that remains valid only while its parent is open.
type SignalRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (s *Signal) zigoPointer() unsafe.Pointer {
	if s == nil {
		return nil
	}
	return s.ptr
}

func (s *SignalRef) zigoPointer() unsafe.Pointer {
	if s == nil || s.ptr == nil {
		return nil
	}
	if parent := s.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return s.ptr
}

type signalCleanupState struct {
	ptr unsafe.Pointer
}

func newSignal(ptr unsafe.Pointer) *Signal {
	value := &Signal{ptr: ptr}
	state := signalCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupSignal, state)
	return value
}

func cleanupSignal(state signalCleanupState) {
	if state.ptr != nil {
		raw.SignalDeinit(state.ptr)
	}
}

// Close releases the native Signal resources. It is safe to call more than once.
func (s *Signal) Close() {
	if s == nil {
		return
	}
	s.once.Do(func() {
		s.cleanup.Stop()
		cleanupSignal(signalCleanupState{ptr: s.ptr})
		s.ptr = nil
	})
	runtime.KeepAlive(s)
}

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoMustPointer(operation string, value zigoHandle) unsafe.Pointer {
	ptr, err := zigoCheckedPointer(operation, value)
	if err != nil {
		panic(err)
	}
	return ptr
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) unsafe.Pointer {
	if absent {
		return nil
	}
	return zigoMustPointer(operation, value)
}

const (
	zigoProjectionMismatch uint8 = iota
	zigoProjectionSuccess
	zigoProjectionInvalidHandle
	zigoProjectionPanic
)

func zigoProjectionError(operation string, status uint8) error {
	switch status {
	case zigoProjectionInvalidHandle:
		return &HandleError{Operation: operation}
	case zigoProjectionPanic:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	default:
		return &ProjectionError{Operation: operation, Status: status}
	}
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (v *Value) TryTag() (ValueTag, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.Tag receiver", v)
	if err != nil {
		return 0, err
	}
	result, status := raw.ValueProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Value.Tag", status)
	}
	return ValueTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (v *Value) Tag() ValueTag {
	result, err := v.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsInteger returns the integer payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsInteger() (int64, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsInteger receiver", v)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectInteger(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsInteger", status)
	}
	return result, true, nil
}

// AsInteger returns the integer payload when active and panics with a typed error on failure.
func (v *Value) AsInteger() (int64, bool) {
	result, matched, err := v.TryAsInteger()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsFlag returns the flag payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsFlag() (bool, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsFlag receiver", v)
	if err != nil {
		return false, false, err
	}
	result, status := raw.ValueProjectFlag(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Value.AsFlag", status)
	}
	return result != 0, true, nil
}

// AsFlag returns the flag payload when active and panics with a typed error on failure.
func (v *Value) AsFlag() (bool, bool) {
	result, matched, err := v.TryAsFlag()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsMode receiver", v)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (v *Value) AsMode() (Mode, bool) {
	result, matched, err := v.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsSamples returns the samples payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsSamples receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsSamples returns the samples payload when active and panics with a typed error on failure.
func (v *Value) AsSamples() ([]int16, bool) {
	result, matched, err := v.TryAsSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsChild returns the child payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsChild() (*ChildRef, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsChild receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectChild(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsChild", status)
	}
	return &ChildRef{ptr: result, parent: v}, true, nil
}

// AsChild returns the child payload when active and panics with a typed error on failure.
func (v *Value) AsChild() (*ChildRef, bool) {
	result, matched, err := v.TryAsChild()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMutableSamples returns the mutableSamples payload, whether it is active, and any lifecycle/native error.
func (v *Value) TryAsMutableSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsMutableSamples receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectMutableSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsMutableSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsMutableSamples returns the mutableSamples payload when active and panics with a typed error on failure.
func (v *Value) AsMutableSamples() ([]int16, bool) {
	result, matched, err := v.TryAsMutableSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (v *ValueRef) TryTag() (ValueTag, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.Tag receiver", v)
	if err != nil {
		return 0, err
	}
	result, status := raw.ValueProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Value.Tag", status)
	}
	return ValueTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (v *ValueRef) Tag() ValueTag {
	result, err := v.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsInteger returns the integer payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsInteger() (int64, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsInteger receiver", v)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectInteger(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsInteger", status)
	}
	return result, true, nil
}

// AsInteger returns the integer payload when active and panics with a typed error on failure.
func (v *ValueRef) AsInteger() (int64, bool) {
	result, matched, err := v.TryAsInteger()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsFlag returns the flag payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsFlag() (bool, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsFlag receiver", v)
	if err != nil {
		return false, false, err
	}
	result, status := raw.ValueProjectFlag(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Value.AsFlag", status)
	}
	return result != 0, true, nil
}

// AsFlag returns the flag payload when active and panics with a typed error on failure.
func (v *ValueRef) AsFlag() (bool, bool) {
	result, matched, err := v.TryAsFlag()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsMode receiver", v)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (v *ValueRef) AsMode() (Mode, bool) {
	result, matched, err := v.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsSamples returns the samples payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsSamples receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsSamples returns the samples payload when active and panics with a typed error on failure.
func (v *ValueRef) AsSamples() ([]int16, bool) {
	result, matched, err := v.TryAsSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsChild returns the child payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsChild() (*ChildRef, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsChild receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectChild(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsChild", status)
	}
	return &ChildRef{ptr: result, parent: v}, true, nil
}

// AsChild returns the child payload when active and panics with a typed error on failure.
func (v *ValueRef) AsChild() (*ChildRef, bool) {
	result, matched, err := v.TryAsChild()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMutableSamples returns the mutableSamples payload, whether it is active, and any lifecycle/native error.
func (v *ValueRef) TryAsMutableSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(v)
	ptr, err := zigoCheckedPointer("Value.AsMutableSamples receiver", v)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectMutableSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsMutableSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsMutableSamples returns the mutableSamples payload when active and panics with a typed error on failure.
func (v *ValueRef) AsMutableSamples() ([]int16, bool) {
	result, matched, err := v.TryAsMutableSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (s *Signal) TryTag() (SignalTag, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.Tag receiver", s)
	if err != nil {
		return 0, err
	}
	result, status := raw.SignalProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Signal.Tag", status)
	}
	return SignalTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (s *Signal) Tag() SignalTag {
	result, err := s.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsTicks returns the ticks payload, whether it is active, and any lifecycle/native error.
func (s *Signal) TryAsTicks() (uint32, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsTicks receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectTicks(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsTicks", status)
	}
	return result, true, nil
}

// AsTicks returns the ticks payload when active and panics with a typed error on failure.
func (s *Signal) AsTicks() (uint32, bool) {
	result, matched, err := s.TryAsTicks()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsLevel returns the level payload, whether it is active, and any lifecycle/native error.
func (s *Signal) TryAsLevel() (float64, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsLevel receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectLevel(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsLevel", status)
	}
	return result, true, nil
}

// AsLevel returns the level payload when active and panics with a typed error on failure.
func (s *Signal) AsLevel() (float64, bool) {
	result, matched, err := s.TryAsLevel()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsOffset returns the offset payload, whether it is active, and any lifecycle/native error.
func (s *Signal) TryAsOffset() (int16, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsOffset receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectOffset(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsOffset", status)
	}
	return result, true, nil
}

// AsOffset returns the offset payload when active and panics with a typed error on failure.
func (s *Signal) AsOffset() (int16, bool) {
	result, matched, err := s.TryAsOffset()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (s *Signal) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsMode receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (s *Signal) AsMode() (Mode, bool) {
	result, matched, err := s.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsActive returns the active payload, whether it is active, and any lifecycle/native error.
func (s *Signal) TryAsActive() (bool, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsActive receiver", s)
	if err != nil {
		return false, false, err
	}
	result, status := raw.SignalProjectActive(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Signal.AsActive", status)
	}
	return result != 0, true, nil
}

// AsActive returns the active payload when active and panics with a typed error on failure.
func (s *Signal) AsActive() (bool, bool) {
	result, matched, err := s.TryAsActive()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (s *SignalRef) TryTag() (SignalTag, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.Tag receiver", s)
	if err != nil {
		return 0, err
	}
	result, status := raw.SignalProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Signal.Tag", status)
	}
	return SignalTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (s *SignalRef) Tag() SignalTag {
	result, err := s.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsTicks returns the ticks payload, whether it is active, and any lifecycle/native error.
func (s *SignalRef) TryAsTicks() (uint32, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsTicks receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectTicks(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsTicks", status)
	}
	return result, true, nil
}

// AsTicks returns the ticks payload when active and panics with a typed error on failure.
func (s *SignalRef) AsTicks() (uint32, bool) {
	result, matched, err := s.TryAsTicks()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsLevel returns the level payload, whether it is active, and any lifecycle/native error.
func (s *SignalRef) TryAsLevel() (float64, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsLevel receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectLevel(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsLevel", status)
	}
	return result, true, nil
}

// AsLevel returns the level payload when active and panics with a typed error on failure.
func (s *SignalRef) AsLevel() (float64, bool) {
	result, matched, err := s.TryAsLevel()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsOffset returns the offset payload, whether it is active, and any lifecycle/native error.
func (s *SignalRef) TryAsOffset() (int16, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsOffset receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectOffset(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsOffset", status)
	}
	return result, true, nil
}

// AsOffset returns the offset payload when active and panics with a typed error on failure.
func (s *SignalRef) AsOffset() (int16, bool) {
	result, matched, err := s.TryAsOffset()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (s *SignalRef) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsMode receiver", s)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.SignalProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Signal.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (s *SignalRef) AsMode() (Mode, bool) {
	result, matched, err := s.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsActive returns the active payload, whether it is active, and any lifecycle/native error.
func (s *SignalRef) TryAsActive() (bool, bool, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.AsActive receiver", s)
	if err != nil {
		return false, false, err
	}
	result, status := raw.SignalProjectActive(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Signal.AsActive", status)
	}
	return result != 0, true, nil
}

// AsActive returns the active payload when active and panics with a typed error on failure.
func (s *SignalRef) AsActive() (bool, bool) {
	result, matched, err := s.TryAsActive()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// SignalSnapshot is a value copy of a Signal: one native call carries the active tag
// and every scalar payload back together.
type SignalSnapshot struct {
	tag    SignalTag
	level  float64
	ticks  uint32
	offset int16
	mode   Mode
	active bool
}

// Tag returns the variant the snapshot captured.
func (snapshot SignalSnapshot) Tag() SignalTag {
	return snapshot.tag
}

// Level returns the level payload and whether it is the captured variant.
func (snapshot SignalSnapshot) Level() (float64, bool) {
	return snapshot.level, snapshot.tag == SignalTagLevel
}

// Ticks returns the ticks payload and whether it is the captured variant.
func (snapshot SignalSnapshot) Ticks() (uint32, bool) {
	return snapshot.ticks, snapshot.tag == SignalTagTicks
}

// Offset returns the offset payload and whether it is the captured variant.
func (snapshot SignalSnapshot) Offset() (int16, bool) {
	return snapshot.offset, snapshot.tag == SignalTagOffset
}

// Mode returns the mode payload and whether it is the captured variant.
func (snapshot SignalSnapshot) Mode() (Mode, bool) {
	return snapshot.mode, snapshot.tag == SignalTagMode
}

// Active returns the active payload and whether it is the captured variant.
func (snapshot SignalSnapshot) Active() (bool, bool) {
	return snapshot.active, snapshot.tag == SignalTagActive
}

// TrySnapshot reads the tag and every payload in one native call, or
// returns a typed lifecycle/native error.
func (s *Signal) TrySnapshot() (SignalSnapshot, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.Snapshot receiver", s)
	if err != nil {
		return SignalSnapshot{}, err
	}
	data, status := raw.SignalReadSnapshot(ptr)
	if status != zigoProjectionSuccess {
		return SignalSnapshot{}, zigoProjectionError("Signal.Snapshot", status)
	}
	return SignalSnapshot{
		tag:    SignalTag(data.Tag),
		level:  data.Level,
		ticks:  data.Ticks,
		offset: data.Offset,
		mode:   Mode(data.Mode),
		active: data.Active != 0,
	}, nil
}

// Snapshot reads the tag and every payload in one native call and panics
// with a typed error on failure.
func (s *Signal) Snapshot() SignalSnapshot {
	result, err := s.TrySnapshot()
	if err != nil {
		panic(err)
	}
	return result
}

// TrySnapshot reads the tag and every payload in one native call, or
// returns a typed lifecycle/native error.
func (s *SignalRef) TrySnapshot() (SignalSnapshot, error) {
	defer runtime.KeepAlive(s)
	ptr, err := zigoCheckedPointer("Signal.Snapshot receiver", s)
	if err != nil {
		return SignalSnapshot{}, err
	}
	data, status := raw.SignalReadSnapshot(ptr)
	if status != zigoProjectionSuccess {
		return SignalSnapshot{}, zigoProjectionError("Signal.Snapshot", status)
	}
	return SignalSnapshot{
		tag:    SignalTag(data.Tag),
		level:  data.Level,
		ticks:  data.Ticks,
		offset: data.Offset,
		mode:   Mode(data.Mode),
		active: data.Active != 0,
	}, nil
}

// Snapshot reads the tag and every payload in one native call and panics
// with a typed error on failure.
func (s *SignalRef) Snapshot() SignalSnapshot {
	result, err := s.TrySnapshot()
	if err != nil {
		panic(err)
	}
	return result
}
