// Code generated by zigo. DO NOT EDIT.

package types

import (
	"unsafe"

	raw "example.com/zigo/event-queue-purego/internal/native"
)

// TickerInfo mirrors the Zig `extern struct` of the same name.
type TickerInfo struct {
	// Interval corresponds to the Zig field interval.
	Interval uint32
	// Ticks corresponds to the Zig field ticks.
	Ticks uint32
}

// TickerInfo is reinterpreted as raw.TickerInfoData instead of copied, so the two
// layouts must stay identical.
var _ = [1]struct{}{}[unsafe.Sizeof(TickerInfo{})-unsafe.Sizeof(raw.TickerInfoData{})]
var _ = [1]struct{}{}[unsafe.Offsetof(TickerInfo{}.Interval)-unsafe.Offsetof(raw.TickerInfoData{}.Interval)]
var _ = [1]struct{}{}[unsafe.Offsetof(TickerInfo{}.Ticks)-unsafe.Offsetof(raw.TickerInfoData{}.Ticks)]
