// Code generated by zigo. DO NOT EDIT.

// Package optional_return_checks provides Go bindings generated by zigo.
package optional_return_checks

import "example.com/zigo/optional-return-checks/internal/raw"

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName


// Password calls the Zig function Terminal.password.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (t *Terminal) Password() (int32, bool, error) {
	ptr, err := zigoCheckedPointer("Terminal.Password receiver", t)
	if err != nil {
		return 0, false, err
	}
	defer t.zigoRelease()
	result, zigoHas, code := raw.TerminalPassword(ptr)
	if code != 0 {
		return 0, false, zigoPoisonAfterPanic(errorForCode("Terminal.Password", code), t)
	}
	return result, zigoHas, nil
}

// CheckedLevel calls the Zig function checkedLevel.
// Native failures are returned as generated error values.
func CheckedLevel(level uint8) (int32, bool, error) {
	if level > 127 {
		return 0, false, &RangeError{Operation: "CheckedLevel", Parameter: "level", Type: "u7"}
	}
	result, zigoHas, code := raw.CheckedLevel(level)
	if code != 0 {
		return 0, false, errorForCode("CheckedLevel", code)
	}
	return result, zigoHas, nil
}

// TerminalValue calls the Zig function terminalValue.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func TerminalValue(terminal *Terminal) (int32, bool, error) {
	terminalPtr, err := zigoOptionalPointer("TerminalValue parameter terminal", terminal == nil, terminal)
	if err != nil {
		return 0, false, err
	}
	defer terminal.zigoRelease()
	result, zigoHas, code := raw.TerminalValue(terminalPtr)
	if code != 0 {
		return 0, false, zigoPoisonAfterPanic(errorForCode("TerminalValue", code), terminal)
	}
	return result, zigoHas, nil
}
