// Code generated by zigo. DO NOT EDIT.
#include <setjmp.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

static _Thread_local jmp_buf zg_panic_env;
static _Thread_local int zg_panic_active;
static _Thread_local char zg_panic_message[1024];

void zg_panic_bridge(const uint8_t *message, size_t length) {
    size_t count = length < sizeof(zg_panic_message) - 1 ? length : sizeof(zg_panic_message) - 1;
    memcpy(zg_panic_message, message, count);
    zg_panic_message[count] = '\0';
    if (zg_panic_active) longjmp(zg_panic_env, 1);
    abort();
}

ZIGO_EXPORT const char *zg_last_error_message(void) { return zg_panic_message; }

int32_t zg_int_batch_create_impl(void * * out_result);
ZIGO_EXPORT int32_t zg_int_batch_create(void * * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_int_batch_create_impl(out_result);
    zg_panic_active = 0;
    return result;
}

int32_t zg_int_batch_push_impl(void * self, int32_t value);
ZIGO_EXPORT int32_t zg_int_batch_push(void * self, int32_t value) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_int_batch_push_impl(self, value);
    zg_panic_active = 0;
    return result;
}

size_t zg_int_batch_len_impl(void * self);
ZIGO_EXPORT size_t zg_int_batch_len(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    size_t result = zg_int_batch_len_impl(self);
    zg_panic_active = 0;
    return result;
}

void zg_int_batch_deinit_impl(void * self);
ZIGO_EXPORT void zg_int_batch_deinit(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_int_batch_deinit_impl(self);
    zg_panic_active = 0;
}

int32_t zg_float_batch_create_impl(void * * out_result);
ZIGO_EXPORT int32_t zg_float_batch_create(void * * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_float_batch_create_impl(out_result);
    zg_panic_active = 0;
    return result;
}

int32_t zg_float_batch_push_impl(void * self, double p0);
ZIGO_EXPORT int32_t zg_float_batch_push(void * self, double p0) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_float_batch_push_impl(self, p0);
    zg_panic_active = 0;
    return result;
}

size_t zg_float_batch_len_impl(void * self);
ZIGO_EXPORT size_t zg_float_batch_len(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    size_t result = zg_float_batch_len_impl(self);
    zg_panic_active = 0;
    return result;
}

void zg_float_batch_deinit_impl(void * self);
ZIGO_EXPORT void zg_float_batch_deinit(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_float_batch_deinit_impl(self);
    zg_panic_active = 0;
}

int32_t zg_pipeline_create_impl(const uint8_t * name_ptr, size_t name_len, uint32_t mode, size_t userdata, void * * out_result);
ZIGO_EXPORT int32_t zg_pipeline_create(const uint8_t * name_ptr, size_t name_len, uint32_t mode, size_t userdata, void * * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_pipeline_create_impl(name_ptr, name_len, mode, userdata, out_result);
    zg_panic_active = 0;
    return result;
}

int32_t zg_pipeline_process_impl(void * self, const int32_t * values_ptr, size_t values_len, int64_t * out_result);
ZIGO_EXPORT int32_t zg_pipeline_process(void * self, const int32_t * values_ptr, size_t values_len, int64_t * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_pipeline_process_impl(self, values_ptr, values_len, out_result);
    zg_panic_active = 0;
    return result;
}

void zg_pipeline_name_impl(void * self, const uint8_t * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT void zg_pipeline_name(void * self, const uint8_t * * out_result_ptr, size_t * out_result_len) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_pipeline_name_impl(self, out_result_ptr, out_result_len);
    zg_panic_active = 0;
}

void zg_sample_values_impl(const float * * out_result_ptr, size_t * out_result_len);
ZIGO_EXPORT void zg_sample_values(const float * * out_result_ptr, size_t * out_result_len) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_sample_values_impl(out_result_ptr, out_result_len);
    zg_panic_active = 0;
}

uint32_t zg_pipeline_mode_impl(void * self);
ZIGO_EXPORT uint32_t zg_pipeline_mode(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    uint32_t result = zg_pipeline_mode_impl(self);
    zg_panic_active = 0;
    return result;
}

uint8_t zg_pipeline_set_enabled_impl(void * self, uint8_t enabled);
ZIGO_EXPORT uint8_t zg_pipeline_set_enabled(void * self, uint8_t enabled) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    uint8_t result = zg_pipeline_set_enabled_impl(self, enabled);
    zg_panic_active = 0;
    return result;
}

size_t zg_pipeline_processed_impl(void * self);
ZIGO_EXPORT size_t zg_pipeline_processed(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    size_t result = zg_pipeline_processed_impl(self);
    zg_panic_active = 0;
    return result;
}

int64_t zg_pipeline_total_impl(void * self);
ZIGO_EXPORT int64_t zg_pipeline_total(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    int64_t result = zg_pipeline_total_impl(self);
    zg_panic_active = 0;
    return result;
}

void zg_pipeline_deinit_impl(void * self);
ZIGO_EXPORT void zg_pipeline_deinit(void * self) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_pipeline_deinit_impl(self);
    zg_panic_active = 0;
}

size_t zg_live_bytes_impl(void);
ZIGO_EXPORT size_t zg_live_bytes(void) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    size_t result = zg_live_bytes_impl();
    zg_panic_active = 0;
    return result;
}

size_t zg_compression_bound_impl(size_t source_len);
ZIGO_EXPORT size_t zg_compression_bound(size_t source_len) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return 0;
    }
    size_t result = zg_compression_bound_impl(source_len);
    zg_panic_active = 0;
    return result;
}
