// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);
pub const std_options: std.Options = if (@hasDecl(target, "std_options")) target.std_options else .{};

export fn zg_terminal_init_impl(initial_cols: u16, rows: u16, max_scrollback_bytes: usize, out_result: **target.Terminal) i32 {
    const result = target.Terminal.init(initial_cols, target.TerminalOptions{ .rows = rows, .max_scrollback_bytes = max_scrollback_bytes });
    out_result.* = result;
    return 0;
}
export fn zg_configure_impl(rows: u16, scale: f32) void {
    target.configure(target.ConfigureOptions{ .rows = rows, .scale = scale });
}
export fn zg_terminal_free_terminal_impl(self: *target.Terminal) i32 {
    target.Terminal.freeTerminal(self);
    return 0;
}
