// Code generated by zigo. DO NOT EDIT.

package streams

import (
	"io"
	"unsafe"

	"example.com/zigo/streams-purego/internal/raw"
)

// zigoHandle is what every handle and borrowed reference offers a generated
// call: pin it open for the native call, let it go afterwards, and mark it
// unusable when the call ended in a Zig panic.
type zigoHandle interface {
	zigoAcquire(operation string) (unsafe.Pointer, error)
	zigoRelease()
	zigoPoison(cause *NativePanicError)
}

// zigoCheckedPointer pins value open for the rest of the call and hands back
// its native pointer; the caller defers zigoRelease. A nil, closed, or
// poisoned handle is the error instead, and nothing is pinned.
func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return value.zigoAcquire(operation)
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return zigoCheckedPointer(operation, value)
}

// zigoPoisonAfterPanic marks every handle a call reached unusable when that
// call ended in a Zig panic: the panic unwound the native frames without
// running their defers, so what is behind those handles is unknown. Any
// other error passes through untouched.
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	if cause, ok := err.(*NativePanicError); ok {
		for _, handle := range handles {
			handle.zigoPoison(cause)
		}
	}
	return err
}

type zigoCallbackHandle = uintptr

func newZigoWriterHandle(value io.Writer) zigoCallbackHandle {
	return raw.NewCallbackHandle(value)
}

func newZigoReaderHandle(value io.Reader) zigoCallbackHandle {
	return raw.NewCallbackHandle(value)
}

func deleteCallbackHandle(handle zigoCallbackHandle) { raw.DeleteCallbackHandle(handle) }

func activeCallbackHandleCount() int64 { return raw.ActiveCallbackHandleCount() }
func callbackDispatcherCount() int     { return raw.CallbackDispatcherCount() }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}

// zigoStreamError reports the error the Go stream behind handle returned
// inside the native call that has just finished, wrapped so the caller can
// match it with errors.Is.
func zigoStreamError(operation string, parameter string, handle zigoCallbackHandle) error {
	if err, ok := raw.TakeStreamError(handle); ok {
		return &StreamError{Operation: operation, Parameter: parameter, Err: err}
	}
	return nil
}

// zigoReaderBytes returns the bytes a reader can hand over whole, or nil
// when it cannot and the native call has to read it a chunk at a time.
// The slice is never nil when the fast path applies, so an empty reader
// is still told apart from one that has to be streamed.
func zigoReaderBytes(value io.Reader) []byte {
	var data []byte
	switch source := value.(type) {
	case interface{ zigoBytes() []byte }:
		data = source.zigoBytes()
	case interface{ Bytes() []byte }:
		data = source.Bytes()
	default:
		return nil
	}
	if data == nil {
		return []byte{}
	}
	return data
}
