// Code generated by zigo. DO NOT EDIT.

package geometry

// zigoSpeedToRaw converts through the binding's `.go` adapter (modeToRaw).
func zigoSpeedToRaw(value Mode) uint8 {
	return modeToRaw(value)
}

// zigoSpeedFromRaw converts through the binding's `.go` adapter (modeFromRaw).
func zigoSpeedFromRaw(value uint8) Mode {
	return modeFromRaw(value)
}

func zigoSpeedSliceToRaw(values []Mode) []uint8 {
	result := make([]uint8, len(values))
	for i := range values {
		result[i] = zigoSpeedToRaw(values[i])
	}
	return result
}

func zigoSpeedSliceFromRaw(values []uint8) []Mode {
	result := make([]Mode, len(values))
	for i := range values {
		result[i] = zigoSpeedFromRaw(values[i])
	}
	return result
}
