// Code generated by zigo. DO NOT EDIT.

/// How the native library behind this binding was built: the Zig version,
/// the optimize mode and the target triple.
pub fn build_info() -> &'static str {
    crate::raw::buildinfo_build_info()
}
