// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_cbbytes_H
#define ZIGO_cbbytes_H

#include <stddef.h>
#include <stdint.h>

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT void zg_on_log(size_t userdata);
ZIGO_EXPORT void zg_on_chunk(size_t userdata);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_cbbytes_H
