// Code generated by zigo. DO NOT EDIT.

package session

import (
	"errors"
	"io"
	"sync"
)

// Session owns a queue and every stream it handed out.
//
// Session adopts one Queue and the child handles that primary handed out, and
// closes them in that order: the children it adopted, most recent first,
// then the primary.
type Session struct {
	queue     *Queue
	streams   []*Stream
	ticks     []*Ticker
	mu        sync.Mutex
	closed    bool
	closeOnce sync.Once
	closeErr  error
}

// NewSession adopts the primary handle. Adopt the children it hands out with the
// Add methods below. A nil primary is skipped when the session closes.
func NewSession(queue *Queue) *Session {
	return &Session{queue: queue}
}

// AddStream adopts Stream handles the primary handed out and returns the session,
// so calls chain. A nil handle is ignored. A handle adopted after Close has
// run is closed immediately rather than leaked.
func (s *Session) AddStream(streams ...*Stream) *Session {
	for _, handle := range streams {
		if handle == nil {
			continue
		}
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			_ = handle.Close()
			continue
		}
		s.streams = append(s.streams, handle)
		s.mu.Unlock()
	}
	return s
}

// AddTick adopts Ticker handles the primary handed out and returns the session,
// so calls chain. A nil handle is ignored. A handle adopted after Close has
// run is closed immediately rather than leaked.
func (s *Session) AddTick(ticks ...*Ticker) *Session {
	for _, handle := range ticks {
		if handle == nil {
			continue
		}
		s.mu.Lock()
		if s.closed {
			s.mu.Unlock()
			_ = handle.Close()
			continue
		}
		s.ticks = append(s.ticks, handle)
		s.mu.Unlock()
	}
	return s
}

// Close closes every child handle the session adopted, most recent first,
// and then the primary. It is idempotent and safe to call from several
// goroutines: a later call returns the first result without closing anything
// again. A member that fails to close does not stop the others, and the
// failures are reported together.
func (s *Session) Close() error {
	s.closeOnce.Do(func() {
		s.mu.Lock()
		s.closed = true
		streams := s.streams
		s.streams = nil
		ticks := s.ticks
		s.ticks = nil
		s.mu.Unlock()

		var failures []error
		for index := len(streams) - 1; index >= 0; index-- {
			if err := streams[index].Close(); err != nil {
				failures = append(failures, err)
			}
		}
		for index := len(ticks) - 1; index >= 0; index-- {
			if err := ticks[index].Close(); err != nil {
				failures = append(failures, err)
			}
		}
		if s.queue != nil {
			if err := s.queue.Close(); err != nil {
				failures = append(failures, err)
			}
		}
		s.closeErr = errors.Join(failures...)
	})
	return s.closeErr
}

// Queue returns the primary handle the session owns.
func (s *Session) Queue() *Queue { return s.queue }

// Streams returns the Stream handles the session adopted, oldest first.
func (s *Session) Streams() []*Stream {
	s.mu.Lock()
	defer s.mu.Unlock()
	return append([]*Stream(nil), s.streams...)
}

// Ticks returns the Ticker handles the session adopted, oldest first.
func (s *Session) Ticks() []*Ticker {
	s.mu.Lock()
	defer s.mu.Unlock()
	return append([]*Ticker(nil), s.ticks...)
}

var _ io.Closer = (*Session)(nil)
