// Code generated by zigo. DO NOT EDIT.
#include <setjmp.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static _Thread_local jmp_buf zg_panic_env;
static _Thread_local int zg_panic_active;
static _Thread_local char zg_panic_message[1024];

void zg_panic_bridge(const uint8_t *message, size_t length) {
    size_t count = length < sizeof(zg_panic_message) - 1 ? length : sizeof(zg_panic_message) - 1;
    memcpy(zg_panic_message, message, count);
    zg_panic_message[count] = '\0';
    if (zg_panic_active) longjmp(zg_panic_env, 1);
    abort();
}

const char *zg_last_error_message(void) { return zg_panic_message; }

void zg_configure_impl(const zg_config * config);
void zg_configure(const zg_config * config) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_configure_impl(config);
    zg_panic_active = 0;
}

void zg_default_config_impl(zg_config * out_result);
void zg_default_config(zg_config * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_default_config_impl(out_result);
    zg_panic_active = 0;
}

void zg_translate_impl(const zg_point * origin, int16_t dx, zg_point * out_result);
void zg_translate(const zg_point * origin, int16_t dx, zg_point * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return;
    }
zg_translate_impl(origin, dx, out_result);
    zg_panic_active = 0;
}

int32_t zg_load_impl(zg_config * out_result);
int32_t zg_load(zg_config * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return -2;
    }
    int32_t result = zg_load_impl(out_result);
    zg_panic_active = 0;
    return result;
}
