// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_impl_H
#define ZIGO_impl_H

#include <stddef.h>
#include <stdint.h>

typedef struct zg_stream zg_stream;
typedef struct zg_buffer zg_buffer;
// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT int32_t zg_stream_feed(zg_stream * self, const uint8_t * bytes_ptr, size_t bytes_len);
ZIGO_EXPORT int32_t zg_buffer_push(zg_buffer * self, const uint8_t * bytes_ptr, size_t bytes_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_stream_append_string(zg_stream * self, const uint8_t * text_ptr, size_t text_len);
ZIGO_EXPORT int32_t zg_buffer_push_string(zg_buffer * self, const uint8_t * bytes_ptr, size_t bytes_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_buffer_drain(zg_buffer * self, uint8_t * dst_ptr, size_t dst_len, size_t * out_result);
ZIGO_EXPORT int32_t zg_stream_dump_purego_v2(zg_stream * self, int32_t (*w_fn)(const uint8_t *, size_t, size_t), size_t w_userdata);
ZIGO_EXPORT int32_t zg_stream_load_purego_v2(zg_stream * self, int32_t (*r_fn)(uint8_t *, size_t, size_t), const uint8_t * r_data, size_t r_data_len, size_t r_userdata, size_t * out_result);
ZIGO_EXPORT int32_t zg_buffer_render_purego_v2(zg_buffer * self, int32_t (*w_fn)(const uint8_t *, size_t, size_t), size_t w_userdata, uint32_t * out_result);
ZIGO_EXPORT int32_t zg_buffer_fill_purego_v2(zg_buffer * self, int32_t (*r_fn)(uint8_t *, size_t, size_t), const uint8_t * r_data, size_t r_data_len, size_t r_userdata);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_impl_H
