// Code generated by zigo. DO NOT EDIT.

package cbenum

import "strconv"

// Location represents the corresponding Zig enum.
type Location int32

const (
	// LocationStandard corresponds to the Zig tag standard.
	LocationStandard Location = 0
	// LocationSelection corresponds to the Zig tag selection.
	LocationSelection Location = 1
)

var zigoLocationNames = [2]string{
	0: "standard",
	1: "selection",
}

// String returns the Zig tag name.
func (value Location) String() string {
	if value >= 0 && value <= 1 {
		return zigoLocationNames[uint64(value)]
	}
	return "Location(" + strconv.Itoa(int(value)) + ")"
}
