// Code generated by zigo. DO NOT EDIT.

// Package borrowed_return provides Go bindings generated by zigo.
package borrowed_return

import (
	"runtime"

	"example.com/zigo/borrowed-return/internal/raw"
)


// NewParent creates a caller-owned Parent.
// The caller must call Close on the returned handle.
// A native panic is returned as *NativePanicError.
func NewParent() (*Parent, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.NewParent()
	if code != 0 {
		return nil, errorForCode("NewParent", code)
	}
	return newParent(result), nil
}

// View calls the Zig function Parent.view.
// The returned reference remains valid only while its parent handle remains open.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (p *Parent) View() (*View, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Parent.View receiver", p)
	if err != nil {
		return nil, err
	}
	defer p.zigoRelease()
	result, code := raw.ParentView(ptr)
	if code != 0 {
		return nil, zigoPoisonAfterPanic(errorForCode("Parent.View", code), p)
	}
	return newBorrowedView(result, p), nil
}

// MaybeView calls the Zig function Parent.maybeView.
// The returned reference remains valid only while its parent handle remains open.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (p *Parent) MaybeView() (*View, bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Parent.MaybeView receiver", p)
	if err != nil {
		return nil, false, err
	}
	defer p.zigoRelease()
	result, code := raw.ParentMaybeView(ptr)
	if code != 0 {
		return nil, false, zigoPoisonAfterPanic(errorForCode("Parent.MaybeView", code), p)
	}
	if result == nil {
		return nil, false, nil
	}
	return newBorrowedView(result, p), true, nil
}

// CheckedView calls the Zig function Parent.checkedView.
// The returned reference remains valid only while its parent handle remains open.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (p *Parent) CheckedView() (*View, bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Parent.CheckedView receiver", p)
	if err != nil {
		return nil, false, err
	}
	defer p.zigoRelease()
	result, code := raw.ParentCheckedView(ptr)
	if code != 0 {
		return nil, false, zigoPoisonAfterPanic(errorForCode("Parent.CheckedView", code), p)
	}
	if result == nil {
		return nil, false, nil
	}
	return newBorrowedView(result, p), true, nil
}

// Touch calls the Zig function View.touch.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (v *View) Touch() (int32, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("View.Touch receiver", v)
	if err != nil {
		return 0, err
	}
	defer v.zigoRelease()
	result, code := raw.ViewTouch(ptr)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("View.Touch", code), v)
	}
	return result, nil
}
