// Code generated by zigo. DO NOT EDIT.

// Package nested_namespace provides Go bindings generated by zigo.
package nested_namespace

import "example.com/zigo/nested-namespace/internal/raw"


// CodepointWidth
// Reports the display width of a codepoint.
func CodepointWidth(cp uint32) uint8 {
	return raw.UnicodeCodepointWidth(cp)
}

// Breaks
// Reports whether a grapheme cluster breaks between two codepoints.
func Breaks(before uint32, after uint32) bool {
	return raw.UnicodeGraphemeBreaks(before, after) != 0
}

// Parse
// Parses one OSC byte.
func Parse(byte uint8) uint8 {
	return raw.OscParserStateParse(byte)
}
