// Code generated by zigo. DO NOT EDIT.

// Package viewport provides Go bindings generated by zigo.
package viewport

import "example.com/zigo/viewport/internal/raw"


// Apply calls the Zig function apply.
func Apply(behavior ScrollViewport) int64 {
	return raw.Apply(zigoScrollViewportToRaw(behavior))
}
