// Code generated by zigo. DO NOT EDIT.

package viewport

import "strconv"

// ScrollViewportTag represents the corresponding Zig enum.
type ScrollViewportTag uint8

const (
	// ScrollViewportTagTop corresponds to the Zig tag top.
	ScrollViewportTagTop ScrollViewportTag = 0
	// ScrollViewportTagDelta corresponds to the Zig tag delta.
	ScrollViewportTagDelta ScrollViewportTag = 1
	// ScrollViewportTagPage corresponds to the Zig tag page.
	ScrollViewportTagPage ScrollViewportTag = 2
	// ScrollViewportTagRatio corresponds to the Zig tag ratio.
	ScrollViewportTagRatio ScrollViewportTag = 3
	// ScrollViewportTagAnimated corresponds to the Zig tag animated.
	ScrollViewportTagAnimated ScrollViewportTag = 4
	// ScrollViewportTagMode corresponds to the Zig tag mode.
	ScrollViewportTagMode ScrollViewportTag = 5
)

// String returns the Zig tag name.
func (value ScrollViewportTag) String() string {
	switch value {
	case ScrollViewportTagTop:
		return "top"
	case ScrollViewportTagDelta:
		return "delta"
	case ScrollViewportTagPage:
		return "page"
	case ScrollViewportTagRatio:
		return "ratio"
	case ScrollViewportTagAnimated:
		return "animated"
	case ScrollViewportTagMode:
		return "mode"
	default:
		return "ScrollViewportTag(" + strconv.Itoa(int(value)) + ")"
	}
}

// Mode represents the corresponding Zig enum.
type Mode uint8

const (
	// ModeInstant corresponds to the Zig tag instant.
	ModeInstant Mode = 0
	// ModeSmooth corresponds to the Zig tag smooth.
	ModeSmooth Mode = 1
)

// String returns the Zig tag name.
func (value Mode) String() string {
	switch value {
	case ModeInstant:
		return "instant"
	case ModeSmooth:
		return "smooth"
	default:
		return "Mode(" + strconv.Itoa(int(value)) + ")"
	}
}
