// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: ${SRCDIR}/../../../zig-out/lib/libfunctional_options_zigo.a
#include "zigo_functional_options.h"
*/
import "C"
import "unsafe"

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string { return C.GoString(C.zg_last_error_message()) }

// PanicMessage returns the message of the native panic a status code of -256 or below names.
func PanicMessage(code int32) string { return C.GoString(C.zg_caught_panic_message(C.int32_t(code))) }

// TerminalInit calls the generated C ABI wrapper for zg_terminal_init.
func TerminalInit(initialCols uint16, rows uint16, maxScrollbackBytes uint) (unsafe.Pointer, int32) {
	var outResult *C.zg_terminal
	code := int32(C.zg_terminal_init(C.uint16_t(initialCols), C.uint16_t(rows), C.size_t(maxScrollbackBytes), &outResult))
	return unsafe.Pointer(outResult), code
}
// Configure calls the generated C ABI wrapper for zg_configure.
func Configure(rows uint16, scale float32) {
	C.zg_configure(C.uint16_t(rows), C.float(scale))
}
// TerminalFreeTerminal calls the generated C ABI wrapper for zg_terminal_free_terminal.
func TerminalFreeTerminal(self unsafe.Pointer) int32 {
	code := int32(C.zg_terminal_free_terminal((*C.zg_terminal)(self)))
	return code
}
