// Code generated by zigo. DO NOT EDIT.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: -L${SRCDIR}/../../../zig-out/lib -lopaque_zigo
#include "zigo_opaque.h"
*/
import "C"
import "unsafe"

func ContextCreate() (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := int32(C.zg_context_create(&outResult))
	return unsafe.Pointer(outResult), code
}
func ContextAdd(self unsafe.Pointer, value int64) int64 {
	return int64(C.zg_context_add(self, C.int64_t(value)))
}
func ContextDeinit(self unsafe.Pointer) {
	C.zg_context_deinit(self)
}
func LiveBytes() uint {
	return uint(C.zg_live_bytes())
}
func Echo(text []uint8) []uint8 {
	var outResultPtr *C.uint8_t
	var outResultLen C.size_t
	var text_zero C.uint8_t
	text_ptr := &text_zero
	if len(text) != 0 {
		text_ptr = (*C.uint8_t)(unsafe.Pointer(&text[0]))
	}
	C.zg_echo(text_ptr, C.size_t(len(text)), &outResultPtr, &outResultLen)
	return C.GoBytes(unsafe.Pointer(outResultPtr), C.int(outResultLen))
}
func Fallback(p0 int64) int64 {
	return int64(C.zg_fallback(C.int64_t(p0)))
}
