// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: ${SRCDIR}/../../../zig-out/lib/libopaque_zigo.a
#include "zigo_opaque.h"
*/
import "C"
import "unsafe"

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string { return C.GoString(C.zg_last_error_message()) }

// ContextCreate calls the generated C ABI wrapper for zg_context_create.
func ContextCreate() (unsafe.Pointer, int32) {
	var outResult *C.zg_context
	code := int32(C.zg_context_create(&outResult))
	return unsafe.Pointer(outResult), code
}

// ContextAdd calls the generated C ABI wrapper for zg_context_add.
func ContextAdd(self unsafe.Pointer, value int64) (int64, int32) {
	var outResult C.int64_t
	code := int32(C.zg_context_add((*C.zg_context)(self), C.int64_t(value), &outResult))
	return int64(outResult), code
}

// ContextMaybeTotal calls the generated C ABI wrapper for zg_context_maybe_total.
func ContextMaybeTotal(self unsafe.Pointer, present uint8) (int64, bool, int32) {
	var outResultHas C.uint8_t
	var outResult C.int64_t
	code := int32(C.zg_context_maybe_total((*C.zg_context)(self), C.uint8_t(present), &outResultHas, &outResult))
	return int64(outResult), outResultHas != 0, code
}

// ContextSetTotal calls the generated C ABI wrapper for zg_context_set_total.
func ContextSetTotal(self unsafe.Pointer, c int64) int32 {
	code := int32(C.zg_context_set_total((*C.zg_context)(self), C.int64_t(c)))
	return code
}

// ContextNext calls the generated C ABI wrapper for zg_context_next.
func ContextNext(self unsafe.Pointer) (int64, bool, int32) {
	var outResultHas C.uint8_t
	var outResult C.int64_t
	code := int32(C.zg_context_next((*C.zg_context)(self), &outResultHas, &outResult))
	return int64(outResult), outResultHas != 0, code
}

// ContextNextChecked calls the generated C ABI wrapper for zg_context_next_checked.
func ContextNextChecked(self unsafe.Pointer) (int64, bool, int32) {
	var outResultHas C.uint8_t
	var outResult C.int64_t
	code := int32(C.zg_context_next_checked((*C.zg_context)(self), &outResultHas, &outResult))
	return int64(outResult), outResultHas != 0, code
}

// ContextRewind calls the generated C ABI wrapper for zg_context_rewind.
func ContextRewind(self unsafe.Pointer) int32 {
	code := int32(C.zg_context_rewind((*C.zg_context)(self)))
	return code
}

// ContextAddCopy calls the generated C ABI wrapper for zg_context_add_copy.
func ContextAddCopy(self unsafe.Pointer, value int64) (int64, int32) {
	var outResult C.int64_t
	code := int32(C.zg_context_add_copy((*C.zg_context)(self), C.int64_t(value), &outResult))
	return int64(outResult), code
}

// ContextBorrowView calls the generated C ABI wrapper for zg_context_borrow_view.
func ContextBorrowView(self unsafe.Pointer) (unsafe.Pointer, int32) {
	var outResult *C.zg_context_view
	code := int32(C.zg_context_borrow_view((*C.zg_context)(self), &outResult))
	return unsafe.Pointer(outResult), code
}

// ContextViewTotal calls the generated C ABI wrapper for zg_context_view_total.
func ContextViewTotal(self unsafe.Pointer) (int64, int32) {
	var outResult C.int64_t
	code := int32(C.zg_context_view_total((*C.zg_context_view)(self), &outResult))
	return int64(outResult), code
}

// ContextCrash calls the generated C ABI wrapper for zg_context_crash.
func ContextCrash(self unsafe.Pointer) int32 {
	code := int32(C.zg_context_crash((*C.zg_context)(self)))
	return code
}

// ContextCrashInfallible calls the generated C ABI wrapper for zg_context_crash_infallible.
func ContextCrashInfallible(self unsafe.Pointer) (int64, int32) {
	var outResult C.int64_t
	code := int32(C.zg_context_crash_infallible((*C.zg_context)(self), &outResult))
	return int64(outResult), code
}

// ContextDeinit calls the generated C ABI wrapper for zg_context_deinit.
func ContextDeinit(self unsafe.Pointer) int32 {
	code := int32(C.zg_context_deinit((*C.zg_context)(self)))
	return code
}

// CrashFatal calls the generated C ABI wrapper for zg_crash_fatal.
func CrashFatal() {
	C.zg_crash_fatal()
}

// LiveBytes calls the generated C ABI wrapper for zg_live_bytes.
func LiveBytes() uint {
	return uint(C.zg_live_bytes())
}

// SumCopies calls the generated C ABI wrapper for zg_sum_copies.
func SumCopies(bias int64, left unsafe.Pointer, right unsafe.Pointer) (int64, int32) {
	var outResult C.int64_t
	code := int32(C.zg_sum_copies(C.int64_t(bias), (*C.zg_context)(left), (*C.zg_context)(right), &outResult))
	return int64(outResult), code
}

// Echo calls the generated C ABI wrapper for zg_echo.
func Echo(text string) string {
	var outResultPtr *C.uint8_t
	var outResultLen C.size_t
	var textZero C.uint8_t
	textPtr := &textZero
	if len(text) != 0 {
		textPtr = (*C.uint8_t)(unsafe.Pointer(unsafe.StringData(text)))
	}
	C.zg_echo(textPtr, C.size_t(len(text)), &outResultPtr, &outResultLen)
	return C.GoStringN((*C.char)(unsafe.Pointer(outResultPtr)), C.int(outResultLen))
}

// Fallback calls the generated C ABI wrapper for zg_fallback.
func Fallback(p0 int64) int64 {
	return int64(C.zg_fallback(C.int64_t(p0)))
}
