// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);
pub const std_options: std.Options = if (@hasDecl(target, "std_options")) target.std_options else .{};

export fn zg_apply_impl(behavior_tag: u8, behavior_delta: isize, behavior_page: usize, behavior_ratio: f64, behavior_animated: u8, behavior_mode: u8, behavior_rgb_r: u8, behavior_rgb_g: u8, behavior_rgb_b: u8, behavior_region_x: i16, behavior_region_enabled: u8, behavior_region_color_r: u8, behavior_region_color_g: u8, behavior_region_color_b: u8, behavior_region_mode: u8) i64 {
    return target.apply(switch (behavior_tag) {
        0 => target.ScrollViewport.top,
        1 => target.ScrollViewport{ .delta = behavior_delta },
        2 => target.ScrollViewport{ .page = behavior_page },
        3 => target.ScrollViewport{ .ratio = behavior_ratio },
        4 => target.ScrollViewport{ .animated = behavior_animated != 0 },
        5 => target.ScrollViewport{ .mode = @enumFromInt(behavior_mode) },
        6 => target.ScrollViewport{ .rgb = target.RGB{ .r = behavior_rgb_r, .g = behavior_rgb_g, .b = behavior_rgb_b } },
        7 => target.ScrollViewport{ .region = target.Region{ .x = behavior_region_x, .enabled = behavior_region_enabled != 0, .color = target.RGB{ .r = behavior_region_color_r, .g = behavior_region_color_g, .b = behavior_region_color_b }, .mode = @enumFromInt(behavior_region_mode) } },
        else => @panic("zigo: invalid tag for argument `behavior`"),
    });
}
export fn zg_current_impl(out_result: *zg_scroll_viewport_snapshot_t) i32 {
    const result = target.current();
    out_result.* = std.mem.zeroes(zg_scroll_viewport_snapshot_t);
    switch (result) {
        .top => out_result.tag = 0,
        .delta => |value| {
            out_result.tag = 1;
            out_result.delta = value;
        },
        .page => |value| {
            out_result.tag = 2;
            out_result.page = value;
        },
        .ratio => |value| {
            out_result.tag = 3;
            out_result.ratio = value;
        },
        .animated => |value| {
            out_result.tag = 4;
            out_result.animated = @intFromBool(value);
        },
        .mode => |value| {
            out_result.tag = 5;
            out_result.mode = @intFromEnum(value);
        },
        .rgb => |value| {
            out_result.tag = 6;
            out_result.rgb_r = value.r;
            out_result.rgb_g = value.g;
            out_result.rgb_b = value.b;
        },
        .region => |value| {
            out_result.tag = 7;
            out_result.region_x = value.x;
            out_result.region_enabled = @intFromBool(value.enabled);
            out_result.region_color_r = value.color.r;
            out_result.region_color_g = value.color.g;
            out_result.region_color_b = value.color.b;
            out_result.region_mode = @intFromEnum(value.mode);
        },
        .unknown => return -3,
    }
    return 0;
}

const zg_scroll_viewport_snapshot_t = extern struct {
    tag: u8,
    delta: isize,
    page: usize,
    ratio: f64,
    animated: u8,
    mode: u8,
    rgb_r: u8,
    rgb_g: u8,
    rgb_b: u8,
    region_x: i16,
    region_enabled: u8,
    region_color_r: u8,
    region_color_g: u8,
    region_color_b: u8,
    region_mode: u8,
};

/// Fails this compile when a layout zigo reflected on the build host does
/// not describe the compilation target. The usual cause is a C type whose
/// width varies by target -- `c_long` and `c_ulong` are 4 bytes on Windows
/// and 8 bytes on Linux and macOS, and `c_longdouble` varies too. Use a
/// fixed-width type in the binding surface, or generate on the target.
fn zigoAbiGuard(comptime what: []const u8, comptime reflected: usize, comptime actual: usize) void {
    if (reflected != actual) @compileError(std.fmt.comptimePrint(
        "zigo ABI guard: {s} is {d} on this target, but zigo reflected {d} on the build host. " ++
            "The generated C header and Go mirrors use the reflected layout, so this binding " ++
            "cannot be built for this target. A C type whose width varies by target, such as " ++
            "c_long or c_ulong, is the usual cause; replace it with a fixed-width type.",
        .{ what, actual, reflected },
    ));
}

comptime {
    zigoAbiGuard("@sizeOf(RGB)", 3, @sizeOf(target.RGB));
    zigoAbiGuard("@alignOf(RGB)", 1, @alignOf(target.RGB));
    zigoAbiGuard("@offsetOf(RGB, \"r\")", 0, @offsetOf(target.RGB, "r"));
    zigoAbiGuard("@offsetOf(RGB, \"g\")", 1, @offsetOf(target.RGB, "g"));
    zigoAbiGuard("@offsetOf(RGB, \"b\")", 2, @offsetOf(target.RGB, "b"));
}

comptime {
    zigoAbiGuard("@sizeOf(Region)", 8, @sizeOf(target.Region));
    zigoAbiGuard("@alignOf(Region)", 2, @alignOf(target.Region));
    zigoAbiGuard("@offsetOf(Region, \"x\")", 0, @offsetOf(target.Region, "x"));
    zigoAbiGuard("@offsetOf(Region, \"enabled\")", 2, @offsetOf(target.Region, "enabled"));
    zigoAbiGuard("@offsetOf(Region, \"color\")", 3, @offsetOf(target.Region, "color"));
    zigoAbiGuard("@offsetOf(Region, \"mode\")", 6, @offsetOf(target.Region, "mode"));
}
