// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);
pub const std_options: std.Options = if (@hasDecl(target, "std_options")) target.std_options else .{};

export fn zg_take_digits_impl(count: u32, out_result_ptr: *[*c]const i32, out_result_len: *usize) void {
    const result = target.takeDigits(count);
    out_result_ptr.* = result.ptr;
    out_result_len.* = result.len;
}
export fn zg_free_digits_impl(values_ptr: [*c]const i32, values_len: usize) void {
    target.freeDigits(if (values_len == 0) &.{} else values_ptr[0..values_len]);
}
export fn zg_take_name_impl(out_result_ptr: *[*c]const u8, out_result_len: *usize) void {
    const result = target.takeName();
    out_result_ptr.* = result.ptr;
    out_result_len.* = result.len;
}
export fn zg_free_name_impl(value_ptr: [*c]const u8, value_len: usize) void {
    target.freeName(if (value_len == 0) &.{} else value_ptr[0..value_len]);
}
