// Code generated by zigo. DO NOT EDIT.

// Package job provides Go bindings generated by zigo.
package job

import (
	"context"
	"errors"
	"runtime"
	"sync/atomic"

	"example.com/zigo/job/internal/raw"
)

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName


// Crunch calls the Zig function Job.crunch.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// Cancelling ctx stops the native call at its next polling point; the call
// then returns ctx.Err() rather than the library's own Canceled error.
func (j *Job) Crunch(ctx context.Context, rounds uint32) (float64, error) {
	var zigoCancel uint32
	var zigoPinner runtime.Pinner
	zigoPinner.Pin(&zigoCancel)
	defer zigoPinner.Unpin()
	if ctx.Err() != nil {
		atomic.StoreUint32(&zigoCancel, 1)
	} else if zigoDone := ctx.Done(); zigoDone != nil {
		zigoStop := make(chan struct{})
		defer close(zigoStop)
		go func() {
			select {
			case <-zigoDone:
				atomic.StoreUint32(&zigoCancel, 1)
			case <-zigoStop:
			}
		}()
	}
	ptr, err := zigoCheckedPointer("Job.Crunch receiver", j)
	if err != nil {
		return 0, err
	}
	defer j.zigoRelease()
	result, code := raw.JobCrunch(ptr, rounds, &zigoCancel)
	if code != 0 {
		zigoErr := zigoPoisonAfterPanic(errorForCode("Job.Crunch", code), j)
		if errors.Is(zigoErr, ErrCanceled) && ctx.Err() != nil {
			return 0, ctx.Err()
		}
		return 0, zigoErr
	}
	return result, nil
}

// Total calls the Zig function Job.total.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (j *Job) Total() (float64, error) {
	ptr, err := zigoCheckedPointer("Job.Total receiver", j)
	if err != nil {
		return 0, err
	}
	defer j.zigoRelease()
	result, code := raw.JobTotal(ptr)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Job.Total", code), j)
	}
	return result, nil
}
