// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_store_H
#define ZIGO_store_H

#include <stddef.h>
#include <stdint.h>

typedef struct zg_cursor zg_cursor;
typedef struct zg_store zg_store;
// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT int32_t zg_store_open(const uint8_t * name_ptr, size_t name_len, zg_store * * out_result);
ZIGO_EXPORT int32_t zg_store_flush(zg_store * self);
ZIGO_EXPORT int32_t zg_store_deinit(zg_store * self);
ZIGO_EXPORT int32_t zg_cursor_init(uint32_t column, zg_cursor * * out_result);
ZIGO_EXPORT int32_t zg_cursor_deinit(zg_cursor * self);
ZIGO_EXPORT const char *zg_last_error_message(void);

#endif // ZIGO_store_H
