// Code generated by zigo. DO NOT EDIT.

package tagged_union

import (
	"unsafe"

	"example.com/zigo/tagged-union/internal/raw"
)

// zigoHandle is what every handle and borrowed reference offers a generated
// call: pin it open for the native call, let it go afterwards, and mark it
// unusable when the call ended in a Zig panic.
type zigoHandle interface {
	zigoAcquire(operation string) (unsafe.Pointer, error)
	zigoRelease()
	zigoPoison(cause *NativePanicError)
}

// zigoCheckedPointer pins value open for the rest of the call and hands back
// its native pointer; the caller defers zigoRelease. A nil, closed, or
// poisoned handle is the error instead, and nothing is pinned.
func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return value.zigoAcquire(operation)
}

// zigoPoisonAfterPanic marks every handle a call reached unusable when that
// call ended in a Zig panic: the panic unwound the native frames without
// running their defers, so what is behind those handles is unknown. Any
// other error passes through untouched.
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	if cause, ok := err.(*NativePanicError); ok {
		for _, handle := range handles {
			handle.zigoPoison(cause)
		}
	}
	return err
}

const (
	zigoProjectionMismatch int32 = iota
	zigoProjectionSuccess
	zigoProjectionInvalidHandle
)

// zigoProjectionError maps a projection status to its error. A status of -256
// or below is a caught native panic whose message the code names.
func zigoProjectionError(operation string, status int32) error {
	if status <= -256 {
		return &NativePanicError{Operation: operation, Message: raw.PanicMessage(status)}
	}
	switch status {
	case zigoProjectionInvalidHandle:
		return &HandleError{Operation: operation}
	default:
		return &StatusError{Operation: operation, Status: status}
	}
}

func zigoMust[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func zigoMustMatch[T any](value T, matched bool, err error) (T, bool) {
	if err != nil {
		panic(err)
	}
	return value, matched
}

// FlagsObserver is the Go callback signature accepted by the generated binding.
type FlagsObserver func(Flags)

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

type zigoCallbackHandle = uintptr

func newFlagsObserverHandle(value FlagsObserver) zigoCallbackHandle {
	return raw.NewCallbackHandle(func(p0 uint16) {
		value(FlagsFromBacking(p0))
	})
}

func deleteCallbackHandle(handle zigoCallbackHandle) { raw.DeleteCallbackHandle(handle) }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}
