// Code generated by zigo. DO NOT EDIT.
package tagged_union

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/tagged-union/internal/raw"
)

// Child is a caller-owned native handle. Call Close when it is no longer needed.
type Child struct {
	ptr     unsafe.Pointer
	mu      sync.RWMutex
	cleanup runtime.Cleanup
}

// ChildRef is a borrowed Child reference that remains valid only while its parent is open.
type ChildRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (c *Child) zigoPointer() unsafe.Pointer {
	if c == nil {
		return nil
	}
	return c.ptr
}

func (c *ChildRef) zigoPointer() unsafe.Pointer {
	if c == nil || c.ptr == nil {
		return nil
	}
	if parent := c.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return c.ptr
}

func (c *Child) zigoLocker() *sync.RWMutex {
	if c == nil {
		return nil
	}
	return &c.mu
}

func (c *ChildRef) zigoLocker() *sync.RWMutex {
	if c == nil || c.parent == nil {
		return nil
	}
	return c.parent.zigoLocker()
}

type childCleanupState struct {
	ptr unsafe.Pointer
}

func newChild(ptr unsafe.Pointer) *Child {
	value := &Child{ptr: ptr}
	state := childCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupChild, state)
	return value
}

func cleanupChild(state childCleanupState) {
	if state.ptr != nil {
		raw.ChildDeinit(state.ptr)
	}
}

// Close releases the native Child resources. It is safe to call more than once.
// The error result is always nil; it exists so Child satisfies io.Closer.
func (c *Child) Close() error {
	if c == nil {
		return nil
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.ptr == nil {
		return nil
	}
	c.cleanup.Stop()
	cleanupChild(childCleanupState{ptr: c.ptr})
	c.ptr = nil
	runtime.KeepAlive(c)
	return nil
}

// Value is a caller-owned native handle. Call Close when it is no longer needed.
type Value struct {
	ptr     unsafe.Pointer
	mu      sync.RWMutex
	cleanup runtime.Cleanup
}

// ValueRef is a borrowed Value reference that remains valid only while its parent is open.
type ValueRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (v *Value) zigoPointer() unsafe.Pointer {
	if v == nil {
		return nil
	}
	return v.ptr
}

func (v *ValueRef) zigoPointer() unsafe.Pointer {
	if v == nil || v.ptr == nil {
		return nil
	}
	if parent := v.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return v.ptr
}

func (v *Value) zigoLocker() *sync.RWMutex {
	if v == nil {
		return nil
	}
	return &v.mu
}

func (v *ValueRef) zigoLocker() *sync.RWMutex {
	if v == nil || v.parent == nil {
		return nil
	}
	return v.parent.zigoLocker()
}

type valueCleanupState struct {
	ptr unsafe.Pointer
}

func newValue(ptr unsafe.Pointer) *Value {
	value := &Value{ptr: ptr}
	state := valueCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupValue, state)
	return value
}

func cleanupValue(state valueCleanupState) {
	if state.ptr != nil {
		raw.ValueDeinit(state.ptr)
	}
}

// Close releases the native Value resources. It is safe to call more than once.
// The error result is always nil; it exists so Value satisfies io.Closer.
func (v *Value) Close() error {
	if v == nil {
		return nil
	}
	v.mu.Lock()
	defer v.mu.Unlock()
	if v.ptr == nil {
		return nil
	}
	v.cleanup.Stop()
	cleanupValue(valueCleanupState{ptr: v.ptr})
	v.ptr = nil
	runtime.KeepAlive(v)
	return nil
}

// Signal is a caller-owned native handle. Call Close when it is no longer needed.
type Signal struct {
	ptr     unsafe.Pointer
	mu      sync.RWMutex
	cleanup runtime.Cleanup
}

func (s *Signal) zigoPointer() unsafe.Pointer {
	if s == nil {
		return nil
	}
	return s.ptr
}

func (s *Signal) zigoLocker() *sync.RWMutex {
	if s == nil {
		return nil
	}
	return &s.mu
}

type signalCleanupState struct {
	ptr unsafe.Pointer
}

func newSignal(ptr unsafe.Pointer) *Signal {
	value := &Signal{ptr: ptr}
	state := signalCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupSignal, state)
	return value
}

func cleanupSignal(state signalCleanupState) {
	if state.ptr != nil {
		raw.SignalDeinit(state.ptr)
	}
}

// Close releases the native Signal resources. It is safe to call more than once.
// The error result is always nil; it exists so Signal satisfies io.Closer.
func (s *Signal) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.ptr == nil {
		return nil
	}
	s.cleanup.Stop()
	cleanupSignal(signalCleanupState{ptr: s.ptr})
	s.ptr = nil
	runtime.KeepAlive(s)
	return nil
}
