// Code generated by zigo. DO NOT EDIT.
package tagged_union

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/tagged-union/internal/raw"
)

// Mode represents the corresponding Zig enum.
type Mode uint8

// ModeIdle corresponds to the Zig tag idle.
const ModeIdle Mode = 0

// ModeActive corresponds to the Zig tag active.
const ModeActive Mode = 1

// ModePaused corresponds to the Zig tag paused.
const ModePaused Mode = 2

// String returns the Zig tag name.
func (value Mode) String() string {
	switch value {
	case ModeIdle:
		return "idle"
	case ModeActive:
		return "active"
	case ModePaused:
		return "paused"
	default:
		return "Mode(?)"
	}
}

// ValueTag represents the corresponding Zig enum.
type ValueTag uint8

// ValueTagNone corresponds to the Zig tag none.
const ValueTagNone ValueTag = 0

// ValueTagInteger corresponds to the Zig tag integer.
const ValueTagInteger ValueTag = 1

// ValueTagFlag corresponds to the Zig tag flag.
const ValueTagFlag ValueTag = 2

// ValueTagMode corresponds to the Zig tag mode.
const ValueTagMode ValueTag = 3

// ValueTagSamples corresponds to the Zig tag samples.
const ValueTagSamples ValueTag = 4

// ValueTagChild corresponds to the Zig tag child.
const ValueTagChild ValueTag = 5

// ValueTagMutableSamples corresponds to the Zig tag mutableSamples.
const ValueTagMutableSamples ValueTag = 6

// String returns the Zig tag name.
func (value ValueTag) String() string {
	switch value {
	case ValueTagNone:
		return "none"
	case ValueTagInteger:
		return "integer"
	case ValueTagFlag:
		return "flag"
	case ValueTagMode:
		return "mode"
	case ValueTagSamples:
		return "samples"
	case ValueTagChild:
		return "child"
	case ValueTagMutableSamples:
		return "mutableSamples"
	default:
		return "ValueTag(?)"
	}
}

// Child is a caller-owned native handle. Call Close when it is no longer needed.
type Child struct {
	ptr     unsafe.Pointer
	once    sync.Once
	cleanup runtime.Cleanup
}

// ChildRef is a borrowed Child reference that remains valid only while its parent is open.
type ChildRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *Child) zigoPointer() unsafe.Pointer {
	if value == nil {
		return nil
	}
	return value.ptr
}

func (value *ChildRef) zigoPointer() unsafe.Pointer {
	if value == nil || value.ptr == nil {
		return nil
	}
	if parent, ok := value.parent.(interface{ zigoPointer() unsafe.Pointer }); ok && parent.zigoPointer() == nil {
		return nil
	}
	return value.ptr
}

type childCleanupState struct {
	ptr unsafe.Pointer
}

func newChild(ptr unsafe.Pointer) *Child {
	value := &Child{ptr: ptr}
	state := childCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupChild, state)
	return value
}

func cleanupChild(state childCleanupState) {
	if state.ptr != nil {
		raw.ChildDeinit(state.ptr)
	}
}

// Close releases the native Child resources. It is safe to call more than once.
func (value *Child) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		value.cleanup.Stop()
		cleanupChild(childCleanupState{ptr: value.ptr})
		value.ptr = nil
	})
	runtime.KeepAlive(value)
}

// Value is a caller-owned native handle. Call Close when it is no longer needed.
type Value struct {
	ptr     unsafe.Pointer
	once    sync.Once
	cleanup runtime.Cleanup
}

// ValueRef is a borrowed Value reference that remains valid only while its parent is open.
type ValueRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *Value) zigoPointer() unsafe.Pointer {
	if value == nil {
		return nil
	}
	return value.ptr
}

func (value *ValueRef) zigoPointer() unsafe.Pointer {
	if value == nil || value.ptr == nil {
		return nil
	}
	if parent, ok := value.parent.(interface{ zigoPointer() unsafe.Pointer }); ok && parent.zigoPointer() == nil {
		return nil
	}
	return value.ptr
}

type valueCleanupState struct {
	ptr unsafe.Pointer
}

func newValue(ptr unsafe.Pointer) *Value {
	value := &Value{ptr: ptr}
	state := valueCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupValue, state)
	return value
}

func cleanupValue(state valueCleanupState) {
	if state.ptr != nil {
		raw.ValueDeinit(state.ptr)
	}
}

// Close releases the native Value resources. It is safe to call more than once.
func (value *Value) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		value.cleanup.Stop()
		cleanupValue(valueCleanupState{ptr: value.ptr})
		value.ptr = nil
	})
	runtime.KeepAlive(value)
}

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoMustPointer(operation string, value zigoHandle) unsafe.Pointer {
	ptr, err := zigoCheckedPointer(operation, value)
	if err != nil {
		panic(err)
	}
	return ptr
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) unsafe.Pointer {
	if absent {
		return nil
	}
	return zigoMustPointer(operation, value)
}

const (
	zigoProjectionMismatch uint8 = iota
	zigoProjectionSuccess
	zigoProjectionInvalidHandle
	zigoProjectionPanic
)

func zigoProjectionError(operation string, status uint8) error {
	switch status {
	case zigoProjectionInvalidHandle:
		return &HandleError{Operation: operation}
	case zigoProjectionPanic:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	default:
		return &ProjectionError{Operation: operation, Status: status}
	}
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (value *Value) TryTag() (ValueTag, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.Tag receiver", value)
	if err != nil {
		return 0, err
	}
	result, status := raw.ValueProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Value.Tag", status)
	}
	return ValueTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (value *Value) Tag() ValueTag {
	result, err := value.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsInteger returns the integer payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsInteger() (int64, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsInteger receiver", value)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectInteger(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsInteger", status)
	}
	return result, true, nil
}

// AsInteger returns the integer payload when active and panics with a typed error on failure.
func (value *Value) AsInteger() (int64, bool) {
	result, matched, err := value.TryAsInteger()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsFlag returns the flag payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsFlag() (bool, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsFlag receiver", value)
	if err != nil {
		return false, false, err
	}
	result, status := raw.ValueProjectFlag(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Value.AsFlag", status)
	}
	return result != 0, true, nil
}

// AsFlag returns the flag payload when active and panics with a typed error on failure.
func (value *Value) AsFlag() (bool, bool) {
	result, matched, err := value.TryAsFlag()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsMode receiver", value)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (value *Value) AsMode() (Mode, bool) {
	result, matched, err := value.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsSamples returns the samples payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsSamples receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsSamples returns the samples payload when active and panics with a typed error on failure.
func (value *Value) AsSamples() ([]int16, bool) {
	result, matched, err := value.TryAsSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsChild returns the child payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsChild() (*ChildRef, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsChild receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectChild(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsChild", status)
	}
	return &ChildRef{ptr: result, parent: value}, true, nil
}

// AsChild returns the child payload when active and panics with a typed error on failure.
func (value *Value) AsChild() (*ChildRef, bool) {
	result, matched, err := value.TryAsChild()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMutableSamples returns the mutableSamples payload, whether it is active, and any lifecycle/native error.
func (value *Value) TryAsMutableSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsMutableSamples receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectMutableSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsMutableSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsMutableSamples returns the mutableSamples payload when active and panics with a typed error on failure.
func (value *Value) AsMutableSamples() ([]int16, bool) {
	result, matched, err := value.TryAsMutableSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryTag returns the active tagged-union tag or a typed lifecycle/native error.
func (value *ValueRef) TryTag() (ValueTag, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.Tag receiver", value)
	if err != nil {
		return 0, err
	}
	result, status := raw.ValueProjectTag(ptr)
	if status != zigoProjectionSuccess {
		return 0, zigoProjectionError("Value.Tag", status)
	}
	return ValueTag(result), nil
}

// Tag returns the active tagged-union tag and panics with a typed error on failure.
func (value *ValueRef) Tag() ValueTag {
	result, err := value.TryTag()
	if err != nil {
		panic(err)
	}
	return result
}

// TryAsInteger returns the integer payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsInteger() (int64, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsInteger receiver", value)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectInteger(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsInteger", status)
	}
	return result, true, nil
}

// AsInteger returns the integer payload when active and panics with a typed error on failure.
func (value *ValueRef) AsInteger() (int64, bool) {
	result, matched, err := value.TryAsInteger()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsFlag returns the flag payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsFlag() (bool, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsFlag receiver", value)
	if err != nil {
		return false, false, err
	}
	result, status := raw.ValueProjectFlag(ptr)
	if status == zigoProjectionMismatch {
		return false, false, nil
	}
	if status != zigoProjectionSuccess {
		return false, false, zigoProjectionError("Value.AsFlag", status)
	}
	return result != 0, true, nil
}

// AsFlag returns the flag payload when active and panics with a typed error on failure.
func (value *ValueRef) AsFlag() (bool, bool) {
	result, matched, err := value.TryAsFlag()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMode returns the mode payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsMode() (Mode, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsMode receiver", value)
	if err != nil {
		return 0, false, err
	}
	result, status := raw.ValueProjectMode(ptr)
	if status == zigoProjectionMismatch {
		return 0, false, nil
	}
	if status != zigoProjectionSuccess {
		return 0, false, zigoProjectionError("Value.AsMode", status)
	}
	return Mode(result), true, nil
}

// AsMode returns the mode payload when active and panics with a typed error on failure.
func (value *ValueRef) AsMode() (Mode, bool) {
	result, matched, err := value.TryAsMode()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsSamples returns the samples payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsSamples receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsSamples returns the samples payload when active and panics with a typed error on failure.
func (value *ValueRef) AsSamples() ([]int16, bool) {
	result, matched, err := value.TryAsSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsChild returns the child payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsChild() (*ChildRef, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsChild receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectChild(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsChild", status)
	}
	return &ChildRef{ptr: result, parent: value}, true, nil
}

// AsChild returns the child payload when active and panics with a typed error on failure.
func (value *ValueRef) AsChild() (*ChildRef, bool) {
	result, matched, err := value.TryAsChild()
	if err != nil {
		panic(err)
	}
	return result, matched
}

// TryAsMutableSamples returns the mutableSamples payload, whether it is active, and any lifecycle/native error.
func (value *ValueRef) TryAsMutableSamples() ([]int16, bool, error) {
	defer runtime.KeepAlive(value)
	ptr, err := zigoCheckedPointer("Value.AsMutableSamples receiver", value)
	if err != nil {
		return nil, false, err
	}
	result, status := raw.ValueProjectMutableSamples(ptr)
	if status == zigoProjectionMismatch {
		return nil, false, nil
	}
	if status != zigoProjectionSuccess {
		return nil, false, zigoProjectionError("Value.AsMutableSamples", status)
	}
	return append([]int16(nil), result...), true, nil
}

// AsMutableSamples returns the mutableSamples payload when active and panics with a typed error on failure.
func (value *ValueRef) AsMutableSamples() ([]int16, bool) {
	result, matched, err := value.TryAsMutableSamples()
	if err != nil {
		panic(err)
	}
	return result, matched
}
