// Code generated by zigo. DO NOT EDIT.

// Package cb provides Go bindings generated by zigo.
package cb

import "example.com/zigo/cb/internal/raw"


// Filter calls the Zig function filter.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func Filter(value int32, predicate FilterPredicateCallback) bool {
	if predicate == nil {
		panic(&CallbackError{Operation: "Filter", Callback: "predicate", Err: ErrNilCallback})
	}
	predicateHandle := zigoNewFilterPredicateCallbackHandle(predicate)
	defer zigoDeleteCallbackHandle(predicateHandle)
	result := raw.Filter(value, uintptr(predicateHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("Filter", predicateHandle)
	}
	return result != 0
}

// Each calls the Zig function each.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func Each(visitor EachVisitorCallback) {
	if visitor == nil {
		panic(&CallbackError{Operation: "Each", Callback: "visitor", Err: ErrNilCallback})
	}
	visitorHandle := zigoNewEachVisitorCallbackHandle(visitor)
	defer zigoDeleteCallbackHandle(visitorHandle)
	raw.Each(uintptr(visitorHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("Each", visitorHandle)
	}
}
