// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: ${SRCDIR}/../../../zig-out/lib/liblookup_zigo.a
#include "zigo_lookup.h"
*/
import "C"

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string { return C.GoString(C.zg_last_error_message()) }

// PanicMessage returns the message of the native panic a status code of -256 or below names.
func PanicMessage(code int32) string { return C.GoString(C.zg_caught_panic_message(C.int32_t(code))) }

// EchoDense calls the generated C ABI wrapper for zg_echo_dense.
func EchoDense(value int8) int8 {
	return int8(C.zg_echo_dense(C.int8_t(value)))
}
// EchoHoles calls the generated C ABI wrapper for zg_echo_holes.
func EchoHoles(value int8) int8 {
	return int8(C.zg_echo_holes(C.int8_t(value)))
}
// EchoMin64 calls the generated C ABI wrapper for zg_echo_min64.
func EchoMin64(value int64) int64 {
	return int64(C.zg_echo_min64(C.int64_t(value)))
}
// EchoMax64 calls the generated C ABI wrapper for zg_echo_max64.
func EchoMax64(value uint64) uint64 {
	return uint64(C.zg_echo_max64(C.uint64_t(value)))
}
// EchoMax8 calls the generated C ABI wrapper for zg_echo_max8.
func EchoMax8(value uint8) uint8 {
	return uint8(C.zg_echo_max8(C.uint8_t(value)))
}
// EchoSparse calls the generated C ABI wrapper for zg_echo_sparse.
func EchoSparse(value int64) int64 {
	return int64(C.zg_echo_sparse(C.int64_t(value)))
}
// EchoSingle calls the generated C ABI wrapper for zg_echo_single.
func EchoSingle(value int8) int8 {
	return int8(C.zg_echo_single(C.int8_t(value)))
}
// EchoLarge calls the generated C ABI wrapper for zg_echo_large.
func EchoLarge(value uint8) uint8 {
	return uint8(C.zg_echo_large(C.uint8_t(value)))
}
