// Code generated by zigo. DO NOT EDIT.

package event_queue

import (
	"runtime/cgo"
	"sync/atomic"
	"unsafe"

	raw "example.com/zigo/event-queue/internal/cgo"
	lifecycle "example.com/zigo/event-queue/internal/lifecycle"
)

type zigoHandle = lifecycle.Handle

type zigoChildHandle = lifecycle.ChildHandle

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	return lifecycle.CheckedPointer(operation, value)
}
func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	return lifecycle.OptionalPointer(operation, absent, value)
}
func zigoPoisonAfterPanic(err error, handles ...zigoHandle) error {
	return lifecycle.PoisonAfterPanic(err, handles...)
}

// The lifecycle methods of every handle here stay unexported. The shared
// runtime reaches them through this registration.
func init() {
	lifecycle.Register(lifecycle.Methods[*EventQueue]{Acquire: (*EventQueue).zigoAcquire, Release: (*EventQueue).zigoRelease, Poison: (*EventQueue).zigoPoison, AcquireChild: (*EventQueue).zigoAcquireChild, DropChild: (*EventQueue).zigoDropChild})
	lifecycle.Register(lifecycle.Methods[*Stream]{Acquire: (*Stream).zigoAcquire, Release: (*Stream).zigoRelease, Poison: (*Stream).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*BorrowBox]{Acquire: (*BorrowBox).zigoAcquire, Release: (*BorrowBox).zigoRelease, Poison: (*BorrowBox).zigoPoison, AcquireChild: (*BorrowBox).zigoAcquireChild, DropChild: (*BorrowBox).zigoDropChild})
	lifecycle.Register(lifecycle.Methods[*BorrowView]{Acquire: (*BorrowView).zigoAcquire, Release: (*BorrowView).zigoRelease, Poison: (*BorrowView).zigoPoison, AcquireChild: (*BorrowView).zigoAcquireChild, DropChild: (*BorrowView).zigoDropChild})
	lifecycle.Register(lifecycle.Methods[*BorrowChild]{Acquire: (*BorrowChild).zigoAcquire, Release: (*BorrowChild).zigoRelease, Poison: (*BorrowChild).zigoPoison})
	lifecycle.Register(lifecycle.Methods[*Terminal]{Acquire: (*Terminal).zigoAcquire, Release: (*Terminal).zigoRelease, Poison: (*Terminal).zigoPoison})
}

func zigoMust[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func zigoMustMatch[T any](value T, matched bool, err error) (T, bool) {
	if err != nil {
		panic(err)
	}
	return value, matched
}

// Observer is the Go callback signature accepted by the generated binding.
type Observer func(uint64, int32) int32

func zigoBoolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var zigoActiveCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func zigoNewObserverHandle(value Observer) zigoCallbackHandle {
	stored := (func(uint64, int32) int32)(value)
	handle := cgo.NewHandle(&raw.CallbackState{Fn: stored})
	zigoActiveCallbackHandles.Add(1)
	return handle
}

func zigoDeleteCallbackHandle(handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	handle.Delete()
	zigoActiveCallbackHandles.Add(-1)
}

func zigoActiveCallbackHandleCount() int64 { return zigoActiveCallbackHandles.Load() }

// zigoCallbackPanicPending is the fast-path check ahead of the per-slot sweep:
// one atomic load says whether any callback recorded a panic nobody has taken.
func zigoCallbackPanicPending() bool { return raw.PendingCallbackPanics() != 0 }

// zigoRethrowCallbackPanic resumes a panic that a Go callback raised inside
// the native call that has just returned. The trampoline recovered it so the
// native frames could unwind; the caller sees it as a *CallbackPanicError.
func zigoRethrowCallbackPanic(operation string, handle zigoCallbackHandle) {
	if handle == 0 {
		return
	}
	if value, stack, ok := raw.TakeCallbackPanic(handle); ok {
		panic(&CallbackPanicError{Operation: operation, Value: value, Stack: stack})
	}
}
