// Code generated by zigo. DO NOT EDIT.
package event_queue

import (
	"runtime/cgo"
	"sync/atomic"
)

var activeCallbackHandles atomic.Int64

func newEventQueueObserverHandle(value EventQueueObserver) cgo.Handle {
	stored := (func(uint64, int32) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func deleteCallbackHandle(handle cgo.Handle) {
	handle.Delete()
	activeCallbackHandles.Add(-1)
}

func activeCallbackHandleCount() int64 { return activeCallbackHandles.Load() }
