// Code generated by zigo. DO NOT EDIT.
package event_queue

import (
	"runtime/cgo"
	"sync/atomic"
	"unsafe"
)

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return zigoCheckedPointer(operation, value)
}

// EventQueueObserver is the Go callback signature accepted by the generated binding.
type EventQueueObserver func(uint64, int32) int32

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var activeCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func newEventQueueObserverHandle(value EventQueueObserver) zigoCallbackHandle {
	stored := (func(uint64, int32) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func deleteCallbackHandle(handle zigoCallbackHandle) {
	handle.Delete()
	activeCallbackHandles.Add(-1)
}

func activeCallbackHandleCount() int64 { return activeCallbackHandles.Load() }
