// Code generated by zigo. DO NOT EDIT.
package telemetry_hub

import (
	"runtime/cgo"
	"sync/atomic"
)

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}

var activeCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func newTelemetryHubObserverHandle(value TelemetryHubObserver) zigoCallbackHandle {
	stored := (func(uint64, float64) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func deleteCallbackHandle(handle zigoCallbackHandle) {
	handle.Delete()
	activeCallbackHandles.Add(-1)
}

func activeCallbackHandleCount() int64 { return activeCallbackHandles.Load() }
