// Code generated by zigo. DO NOT EDIT.

// Package telemetry_hub provides Go bindings generated by zigo.
package telemetry_hub

import (
	"context"
	"errors"
	"runtime"
	"sync/atomic"

	raw "example.com/zigo/telemetry-hub/internal/native"
)

// NewTelemetryHub creates a caller-owned TelemetryHub.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func NewTelemetryHub(inputName string, maxSamples uint, initialMode Mode, overflowPolicy OverflowPolicy, observer TelemetryHubObserver) (*TelemetryHub, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	observerHandle := newTelemetryHubObserverHandle(observer)
	result, code := raw.TelemetryHubCreate(inputName, maxSamples, uint32(initialMode), uint32(overflowPolicy), uintptr(observerHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("NewTelemetryHub", observerHandle)
	}
	if code != 0 {
		deleteCallbackHandle(observerHandle)
		return nil, errorForCode("NewTelemetryHub", code)
	}
	return newTelemetryHub(result, []zigoCallbackHandle{observerHandle}), nil
}

// Rename calls the Zig function TelemetryHub.rename.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Rename(newName string) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Rename receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubRename(ptr, newName)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Rename", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.Rename", code), t)
	}
	return nil
}

// Name calls the Zig function TelemetryHub.name.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Name() (string, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Name receiver", t)
	if err != nil {
		return "", err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubName(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Name", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return "", zigoPoisonAfterPanic(errorForCode("TelemetryHub.Name", code), t)
	}
	return result, nil
}

// Reduce: A deliberately long fold, polling a cancellation flag between rounds.
// The flag is Go's: a goroutine watching `ctx.Done()` raises it while
// this is running, and the only thing that has to be true for that to be
// safe is that this reads it atomically and never writes it.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
// Cancelling ctx stops the native call at its next polling point; the call
// then returns ctx.Err() rather than the library's own Cancelled error.
func (t *TelemetryHub) Reduce(ctx context.Context, rounds uint32) (float64, error) {
	var zigoCancel uint32
	if ctx.Err() != nil {
		atomic.StoreUint32(&zigoCancel, 1)
	} else if zigoDone := ctx.Done(); zigoDone != nil {
		zigoStop := make(chan struct{})
		defer close(zigoStop)
		go func() {
			select {
			case <-zigoDone:
				atomic.StoreUint32(&zigoCancel, 1)
			case <-zigoStop:
			}
		}()
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Reduce receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubReduce(ptr, rounds, &zigoCancel)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Reduce", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		zigoErr := zigoPoisonAfterPanic(errorForCode("TelemetryHub.Reduce", code), t)
		if errors.Is(zigoErr, ErrCancelled) && ctx.Err() != nil {
			return 0, ctx.Err()
		}
		return 0, zigoErr
	}
	return result, nil
}

// Capacity calls the Zig function TelemetryHub.capacity.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Capacity() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Capacity receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubCapacity(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Capacity", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Capacity", code), t)
	}
	return result, nil
}

// Len calls the Zig function TelemetryHub.len.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Len() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Len receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubLen(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Len", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Len", code), t)
	}
	return result, nil
}

// IsEmpty calls the Zig function TelemetryHub.isEmpty.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) IsEmpty() (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.IsEmpty receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubIsEmpty(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.IsEmpty", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.IsEmpty", code), t)
	}
	return result != 0, nil
}

// IsFull calls the Zig function TelemetryHub.isFull.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) IsFull() (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.IsFull receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubIsFull(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.IsFull", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.IsFull", code), t)
	}
	return result != 0, nil
}

// Mode calls the Zig function TelemetryHub.mode.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Mode() (Mode, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Mode receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubMode(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Mode", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Mode", code), t)
	}
	return Mode(result), nil
}

// SetMode calls the Zig function TelemetryHub.setMode.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetMode(newMode Mode) (Mode, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetMode receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubSetMode(ptr, uint32(newMode))
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetMode", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetMode", code), t)
	}
	return Mode(result), nil
}

// OverflowPolicy calls the Zig function TelemetryHub.overflowPolicy.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) OverflowPolicy() (OverflowPolicy, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.OverflowPolicy receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubOverflowPolicy(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.OverflowPolicy", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.OverflowPolicy", code), t)
	}
	return OverflowPolicy(result), nil
}

// SetOverflowPolicy calls the Zig function TelemetryHub.setOverflowPolicy.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetOverflowPolicy(newPolicy OverflowPolicy) (OverflowPolicy, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetOverflowPolicy receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubSetOverflowPolicy(ptr, uint32(newPolicy))
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetOverflowPolicy", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetOverflowPolicy", code), t)
	}
	return OverflowPolicy(result), nil
}

// Enabled calls the Zig function TelemetryHub.enabled.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Enabled() (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Enabled receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubEnabled(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Enabled", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Enabled", code), t)
	}
	return result != 0, nil
}

// SetEnabled calls the Zig function TelemetryHub.setEnabled.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetEnabled(newEnabled bool) (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetEnabled receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubSetEnabled(ptr, boolToUint8(newEnabled))
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetEnabled", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetEnabled", code), t)
	}
	return result != 0, nil
}

// Threshold calls the Zig function TelemetryHub.threshold.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Threshold() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Threshold receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubThreshold(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Threshold", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Threshold", code), t)
	}
	return result, nil
}

// SetThreshold calls the Zig function TelemetryHub.setThreshold.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetThreshold(newThreshold float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetThreshold receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubSetThreshold(ptr, newThreshold)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetThreshold", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetThreshold", code), t)
	}
	return nil
}

// ScaleFactor calls the Zig function TelemetryHub.scaleFactor.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ScaleFactor() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ScaleFactor receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubScaleFactor(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ScaleFactor", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.ScaleFactor", code), t)
	}
	return result, nil
}

// SetScaleFactor calls the Zig function TelemetryHub.setScaleFactor.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetScaleFactor(newFactor float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetScaleFactor receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubSetScaleFactor(ptr, newFactor)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetScaleFactor", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetScaleFactor", code), t)
	}
	return nil
}

// Offset calls the Zig function TelemetryHub.offset.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Offset() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Offset receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubOffset(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Offset", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Offset", code), t)
	}
	return result, nil
}

// SetOffset calls the Zig function TelemetryHub.setOffset.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) SetOffset(newOffset float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.SetOffset receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubSetOffset(ptr, newOffset)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.SetOffset", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.SetOffset", code), t)
	}
	return nil
}

// Push calls the Zig function TelemetryHub.push.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Push(id uint64, value float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Push receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubPush(ptr, id, value)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Push", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.Push", code), t)
	}
	return nil
}

// PushWithSeverity calls the Zig function TelemetryHub.pushWithSeverity.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) PushWithSeverity(id uint64, value float64, severity Severity) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.PushWithSeverity receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubPushWithSeverity(ptr, id, value, uint32(severity))
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.PushWithSeverity", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.PushWithSeverity", code), t)
	}
	return nil
}

// PushBatch calls the Zig function TelemetryHub.pushBatch.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) PushBatch(values []float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.PushBatch receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubPushBatch(ptr, values)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.PushBatch", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.PushBatch", code), t)
	}
	return nil
}

// Process calls the Zig function TelemetryHub.process.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Process(limit uint) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Process receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubProcess(ptr, limit)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Process", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Process", code), t)
	}
	return result, nil
}

// ProcessAll calls the Zig function TelemetryHub.processAll.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ProcessAll() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ProcessAll receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubProcessAll(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ProcessAll", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.ProcessAll", code), t)
	}
	return result, nil
}

// Clear calls the Zig function TelemetryHub.clear.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Clear() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Clear receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubClear(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Clear", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Clear", code), t)
	}
	return result, nil
}

// ResetStatistics calls the Zig function TelemetryHub.resetStatistics.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ResetStatistics() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ResetStatistics receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubResetStatistics(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ResetStatistics", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.ResetStatistics", code), t)
	}
	return nil
}

// Accepted calls the Zig function TelemetryHub.accepted.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Accepted() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Accepted receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubAccepted(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Accepted", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Accepted", code), t)
	}
	return result, nil
}

// Rejected calls the Zig function TelemetryHub.rejected.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Rejected() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Rejected receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubRejected(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Rejected", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Rejected", code), t)
	}
	return result, nil
}

// Dropped calls the Zig function TelemetryHub.dropped.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Dropped() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Dropped receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubDropped(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Dropped", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Dropped", code), t)
	}
	return result, nil
}

// Processed calls the Zig function TelemetryHub.processed.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Processed() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Processed receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubProcessed(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Processed", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Processed", code), t)
	}
	return result, nil
}

// Filtered calls the Zig function TelemetryHub.filtered.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Filtered() (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Filtered receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubFiltered(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Filtered", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Filtered", code), t)
	}
	return result, nil
}

// Sum calls the Zig function TelemetryHub.sum.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Sum() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Sum receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubSum(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Sum", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Sum", code), t)
	}
	return result, nil
}

// Minimum calls the Zig function TelemetryHub.minimum.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Minimum() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Minimum receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubMinimum(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Minimum", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Minimum", code), t)
	}
	return result, nil
}

// Maximum calls the Zig function TelemetryHub.maximum.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Maximum() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Maximum receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubMaximum(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Maximum", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Maximum", code), t)
	}
	return result, nil
}

// Average calls the Zig function TelemetryHub.average.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) Average() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.Average receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubAverage(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.Average", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.Average", code), t)
	}
	return result, nil
}

// FirstID calls the Zig function TelemetryHub.firstId.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) FirstID() (uint64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.FirstID receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubFirstID(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.FirstID", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.FirstID", code), t)
	}
	return result, nil
}

// FirstValue calls the Zig function TelemetryHub.firstValue.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) FirstValue() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.FirstValue receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubFirstValue(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.FirstValue", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.FirstValue", code), t)
	}
	return result, nil
}

// LastID calls the Zig function TelemetryHub.lastId.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) LastID() (uint64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.LastID receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubLastID(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.LastID", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.LastID", code), t)
	}
	return result, nil
}

// LastValue calls the Zig function TelemetryHub.lastValue.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) LastValue() (float64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.LastValue receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubLastValue(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.LastValue", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.LastValue", code), t)
	}
	return result, nil
}

// LastSeverity calls the Zig function TelemetryHub.lastSeverity.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) LastSeverity() (Severity, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.LastSeverity receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubLastSeverity(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.LastSeverity", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.LastSeverity", code), t)
	}
	return Severity(result), nil
}

// CountAbove calls the Zig function TelemetryHub.countAbove.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) CountAbove(boundary float64) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.CountAbove receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubCountAbove(ptr, boundary)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.CountAbove", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.CountAbove", code), t)
	}
	return result, nil
}

// CountBelow calls the Zig function TelemetryHub.countBelow.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) CountBelow(boundary float64) (uint, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.CountBelow receiver", t)
	if err != nil {
		return 0, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubCountBelow(ptr, boundary)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.CountBelow", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("TelemetryHub.CountBelow", code), t)
	}
	return result, nil
}

// ContainsAbove calls the Zig function TelemetryHub.containsAbove.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ContainsAbove(boundary float64) (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ContainsAbove receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubContainsAbove(ptr, boundary)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ContainsAbove", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.ContainsAbove", code), t)
	}
	return result != 0, nil
}

// ContainsBelow calls the Zig function TelemetryHub.containsBelow.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ContainsBelow(boundary float64) (bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ContainsBelow receiver", t)
	if err != nil {
		return false, err
	}
	defer t.zigoRelease()
	result, code := raw.TelemetryHubContainsBelow(ptr, boundary)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ContainsBelow", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return false, zigoPoisonAfterPanic(errorForCode("TelemetryHub.ContainsBelow", code), t)
	}
	return result != 0, nil
}

// ScaleValues calls the Zig function TelemetryHub.scaleValues.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ScaleValues(factor float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ScaleValues receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubScaleValues(ptr, factor)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ScaleValues", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.ScaleValues", code), t)
	}
	return nil
}

// OffsetValues calls the Zig function TelemetryHub.offsetValues.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) OffsetValues(delta float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.OffsetValues receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubOffsetValues(ptr, delta)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.OffsetValues", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.OffsetValues", code), t)
	}
	return nil
}

// ClampValues calls the Zig function TelemetryHub.clampValues.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) ClampValues(lower float64, upper float64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.ClampValues receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubClampValues(ptr, lower, upper)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.ClampValues", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.ClampValues", code), t)
	}
	return nil
}

// AbsoluteValues calls the Zig function TelemetryHub.absoluteValues.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) AbsoluteValues() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.AbsoluteValues receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubAbsoluteValues(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.AbsoluteValues", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.AbsoluteValues", code), t)
	}
	return nil
}

// NegateValues calls the Zig function TelemetryHub.negateValues.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func (t *TelemetryHub) NegateValues() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("TelemetryHub.NegateValues receiver", t)
	if err != nil {
		return err
	}
	defer t.zigoRelease()
	code := raw.TelemetryHubNegateValues(ptr)
	if zigoCallbackPanicPending() {
		for slot := range 1 {
			zigoRethrowCallbackPanic("TelemetryHub.NegateValues", t.zigoCallbackHandle(slot))
		}
	}
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("TelemetryHub.NegateValues", code), t)
	}
	return nil
}

// LiveHubs calls the Zig function liveHubs.
func LiveHubs() uint {
	return raw.LiveHubs()
}
