// Code generated by zigo. DO NOT EDIT.

//! The generated call layer between the public API and the native
//! library. Not part of the supported API.

#![allow(dead_code)]

use core::ffi::c_char;

extern "C" {
    pub fn zg_sum(values_ptr: *const i32, values_len: usize) -> i64;
    pub fn zg_measure(text_ptr: *const u8, text_len: usize) -> usize;
    pub fn zg_last_error_message() -> *const c_char;
    pub fn zg_caught_panic_message(code: i32) -> *const c_char;
}

/// The most recent native panic message for this binding.
pub fn last_error_message() -> String {
    unsafe { message_at(zg_last_error_message()) }
}

/// The message of the native panic a status code of -256 or below names.
pub fn panic_message(code: i32) -> String {
    unsafe { message_at(zg_caught_panic_message(code)) }
}

/// Copies a NUL-terminated message the shim owns. A null pointer is an
/// absent message rather than an error: the accessors return one when no
/// panic has been recorded.
///
/// # Safety
///
/// `pointer` must be null or point at a NUL-terminated string that stays
/// valid for the duration of the call.
unsafe fn message_at(pointer: *const c_char) -> String {
    if pointer.is_null() {
        return String::new();
    }
    unsafe { core::ffi::CStr::from_ptr(pointer) }
        .to_string_lossy()
        .into_owned()
}

/// Calls the generated C ABI wrapper for `zg_sum`.
pub fn sum(values: &[i32]) -> i64 {
    unsafe { zg_sum(values.as_ptr(), values.len()) }
}

/// Calls the generated C ABI wrapper for `zg_measure`.
pub fn measure(text: &str) -> usize {
    unsafe { zg_measure(text.as_ptr(), text.len()) }
}
