// Code generated by zigo. DO NOT EDIT.

package callback

import "strconv"

// Level represents the corresponding Zig enum.
type Level int32

const (
	// LevelInfo corresponds to the Zig tag info.
	LevelInfo Level = 0
	// LevelWarn corresponds to the Zig tag warn.
	LevelWarn Level = 1
	// LevelErr corresponds to the Zig tag err.
	LevelErr Level = 2
)

var zigoLevelNames = [3]string{
	0: "info",
	1: "warn",
	2: "err",
}

// String returns the Zig tag name.
func (value Level) String() string {
	if value >= 0 && value <= 2 {
		return zigoLevelNames[uint64(value)]
	}
	return "Level(" + strconv.Itoa(int(value)) + ")"
}
