// Code generated by zigo. DO NOT EDIT.
#include <setjmp.h>
#include <stdatomic.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "zigo_job.h"

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

static _Thread_local jmp_buf zg_panic_env;
static _Thread_local int zg_panic_active;
static _Thread_local char zg_panic_message[1024];

// A panic with nowhere to be reported is what Zig says it is: fatal.
// The message is written out first so the process does not die silent.
_Noreturn static void zg_panic_fatal(void) {
    fputs("zigo: native panic: ", stderr);
    fputs(zg_panic_message, stderr);
    fputc('\n', stderr);
    fflush(stderr);
    abort();
}

void zg_panic_bridge(const uint8_t *message, size_t length) {
    size_t count = length < sizeof(zg_panic_message) - 1 ? length : sizeof(zg_panic_message) - 1;
    memcpy(zg_panic_message, message, count);
    zg_panic_message[count] = '\0';
    if (zg_panic_active) longjmp(zg_panic_env, 1);
    zg_panic_fatal();
}

ZIGO_EXPORT const char *zg_last_error_message(void) { return zg_panic_message; }

#define ZG_PANIC_SLOTS 64u
#define ZG_PANIC_SEQUENCE_MASK 0x7fffffu
static char zg_panic_slots[ZG_PANIC_SLOTS][sizeof(zg_panic_message)];
static atomic_uint zg_panic_sequence;
static atomic_uint zg_panic_slot_sequence[ZG_PANIC_SLOTS];

// Publishes the caught message under a fresh sequence number and returns the
// status code naming it: -(256 + sequence). The slot is reused after
// ZG_PANIC_SLOTS later panics, after which the reader sees an empty message.
static int32_t zg_panic_publish(void) {
    unsigned sequence = (atomic_fetch_add(&zg_panic_sequence, 1u) + 1u) & ZG_PANIC_SEQUENCE_MASK;
    if (sequence == 0u) sequence = (atomic_fetch_add(&zg_panic_sequence, 1u) + 1u) & ZG_PANIC_SEQUENCE_MASK;
    unsigned slot = sequence % ZG_PANIC_SLOTS;
    atomic_store(&zg_panic_slot_sequence[slot], 0u);
    memcpy(zg_panic_slots[slot], zg_panic_message, sizeof(zg_panic_message));
    atomic_store(&zg_panic_slot_sequence[slot], sequence);
    return -(int32_t)(256u + sequence);
}

// The message a panic status code names, or "" once its slot was reused.
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code) {
    if (code > -256) return "";
    unsigned sequence = (unsigned)(-(int64_t)code - 256);
    unsigned slot = sequence % ZG_PANIC_SLOTS;
    if (atomic_load(&zg_panic_slot_sequence[slot]) != sequence) return "";
    return zg_panic_slots[slot];
}

int32_t zg_job_crunch_impl(zg_job * self, uint32_t rounds, const uint32_t * cancel, double * out_result);
ZIGO_EXPORT int32_t zg_job_crunch(zg_job * self, uint32_t rounds, const uint32_t * cancel, double * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return zg_panic_publish();
    }
    int32_t result = zg_job_crunch_impl(self, rounds, cancel, out_result);
    zg_panic_active = 0;
    return result;
}

int32_t zg_job_total_impl(zg_job * self, double * out_result);
ZIGO_EXPORT int32_t zg_job_total(zg_job * self, double * out_result) {
    zg_panic_active = 1;
    if (setjmp(zg_panic_env) != 0) {
        zg_panic_active = 0;
        return zg_panic_publish();
    }
    int32_t result = zg_job_total_impl(self, out_result);
    zg_panic_active = 0;
    return result;
}
