// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_job_H
#define ZIGO_job_H

#include <stddef.h>
#include <stdint.h>

typedef struct zg_job zg_job;
// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT int32_t zg_job_crunch(zg_job * self, uint32_t rounds, const uint32_t * cancel, double * out_result);
ZIGO_EXPORT int32_t zg_job_total(zg_job * self, double * out_result);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_job_H
