const zigo = @import("zigo");
const library = @import("tagged_union");

pub const bindings = zigo.define(.{
    .root = library,
    .types = &.{
        .{ .enumeration = .{ .type = library.Mode } },
        .{ .handle = .{ .type = library.Child } },
        .{ .tagged_union = .{ .type = library.Value } },
        .{ .tagged_union = .{ .type = library.Signal, .access = .snapshot } },
        .{ .value = .{ .type = library.RGB } },
        .{ .value = .{ .type = library.Flags } },
        .{ .value = .{ .type = library.ColorRecord } },
        .{ .handle = .{ .type = library.Palette, .fields = &.{.{ .path = "flags", .set = true }} } },
        .{ .callback = .{ .name = "FlagsObserver", .type = library.FlagsObserver } },
        .{ .tagged_union = .{ .type = library.ScrollViewport, .omit = &.{"unknown"} } },
    },
    .functions = &.{
        .{ .path = "Child.create", .params = &.{.{ .name = "value" }} },
        .{ .path = "Child.get" },
        .{ .path = "Child.deinit" },
        .{ .path = "Value.create", .params = &.{.{ .name = "initial" }} },
        .{ .path = "Value.setNone" },
        .{ .path = "Value.setFlag", .params = &.{.{ .name = "flag" }} },
        .{ .path = "Value.setMode", .params = &.{.{ .name = "mode" }} },
        .{ .path = "Value.usePresetSamples" },
        .{ .path = "Value.useEmptySamples" },
        .{ .path = "Value.useMutableSamples" },
        .{ .path = "Value.setChild", .params = &.{.{ .name = "child" }} },
        .{ .path = "Value.borrow" },
        .{ .path = "Value.deinit" },
        .{ .path = "Signal.create", .params = &.{.{ .name = "initial" }} },
        .{ .path = "Signal.setIdle" },
        .{ .path = "Signal.setTicks", .params = &.{.{ .name = "ticks" }} },
        .{ .path = "Signal.setLevel", .params = &.{.{ .name = "level" }} },
        .{ .path = "Signal.setOffset", .params = &.{.{ .name = "offset" }} },
        .{ .path = "Signal.setMode", .params = &.{.{ .name = "mode" }} },
        .{ .path = "Signal.setActive", .params = &.{.{ .name = "active" }} },
        .{ .path = "Signal.deinit" },
        .{ .path = "root.liveValues" },
        .{ .path = "root.divide", .params = &.{ .{ .name = "numerator" }, .{ .name = "denominator" } } },
        .{ .path = "root.sum", .params = &.{.{ .name = "values" }} },
        .{ .path = "root.scrollAmount", .params = &.{.{ .name = "behavior" }} },
        .{ .path = "root.currentViewport", .params = &.{.{ .name = "kind" }} },
        .{ .path = "root.echoRGB", .params = &.{.{ .name = "value" }} },
        .{ .path = "root.maybeRGB", .params = &.{.{ .name = "present" }} },
        .{ .path = "root.checkedRGB", .params = &.{.{ .name = "valid" }} },
        .{ .path = "root.echoColorRecord", .params = &.{.{ .name = "value" }} },
        .{
            .path = "root.flattenFlags",
            .params = &.{.{ .name = "options", .flatten = &.{"flags"} }},
        },
        .{ .path = "Palette.create", .params = &.{.{ .name = "flags" }} },
        .{ .path = "Palette.deinit" },
        .{ .path = "root.visitFlags", .params = &.{ .{ .name = "callback" }, .{ .name = "userdata" } } },
        .{ .path = "root.panicError" },
    },
});
