const zigo = @import("zigo");
const library = @import("tagged_union");
const json = @import("zigo_json");

const api = zigo.scope(library);

pub const bindings = zigo.define(.{
    .root = library,
    .declarations = &.{
        api.enumeration("Mode", .{}).use(json.plugin, .{}),
        api.handle("Child", .{}),
        api.taggedUnion("Value", .{}),
        api.taggedUnion("Signal", .{ .access = .snapshot }),
        api.value("RGB", .{}).use(json.plugin, .{ .field_names = .zig }),
        api.value("Flags", .{}),
        api.value("ColorRecord", .{}),
        api.handle("Palette", .{ .fields = &.{.{ .path = "flags", .set = true }} }),
        api.callback("FlagsObserver", .{}),
        api.taggedUnion("ScrollViewport", .{ .omit = &.{"unknown"} }),
        api.in("Child").function("create", .{ .params = &.{.{ .index = 0, .go_name = "value" }} }),
        api.in("Child").function("get", .{}),
        api.in("Child").function("deinit", .{}),
        api.in("Value").function("create", .{ .params = &.{.{ .index = 0, .go_name = "initial" }} }),
        api.in("Value").function("setNone", .{}),
        api.in("Value").function("setFlag", .{ .params = &.{.{ .index = 1, .go_name = "flag" }} }),
        api.in("Value").function("setMode", .{ .params = &.{.{ .index = 1, .go_name = "mode" }} }),
        api.in("Value").function("usePresetSamples", .{}),
        api.in("Value").function("useEmptySamples", .{}),
        api.in("Value").function("useMutableSamples", .{}),
        api.in("Value").function("setChild", .{ .params = &.{.{ .index = 1, .go_name = "child" }} }),
        api.in("Value").function("borrow", .{}),
        api.in("Value").function("deinit", .{}),
        api.in("Signal").function("create", .{ .params = &.{.{ .index = 0, .go_name = "initial" }} }),
        api.in("Signal").function("setIdle", .{}),
        api.in("Signal").function("setTicks", .{ .params = &.{.{ .index = 1, .go_name = "ticks" }} }),
        api.in("Signal").function("setLevel", .{ .params = &.{.{ .index = 1, .go_name = "level" }} }),
        api.in("Signal").function("setOffset", .{ .params = &.{.{ .index = 1, .go_name = "offset" }} }),
        api.in("Signal").function("setMode", .{ .params = &.{.{ .index = 1, .go_name = "mode" }} }),
        api.in("Signal").function("setActive", .{ .params = &.{.{ .index = 1, .go_name = "active" }} }),
        api.in("Signal").function("deinit", .{}),
        api.function("liveValues", .{}),
        api.function("divide", .{ .params = &.{ .{ .index = 0, .go_name = "numerator" }, .{ .index = 1, .go_name = "denominator" } } }),
        api.function("sum", .{ .params = &.{.{ .index = 0, .go_name = "values" }} }),
        api.function("scrollAmount", .{ .params = &.{.{ .index = 0, .go_name = "behavior" }} }),
        api.function("currentViewport", .{ .params = &.{.{ .index = 0, .go_name = "kind" }} }),
        api.function("echoRGB", .{ .params = &.{.{ .index = 0, .go_name = "value" }} }),
        api.function("maybeRGB", .{ .params = &.{.{ .index = 0, .go_name = "present" }} }),
        api.function("checkedRGB", .{ .params = &.{.{ .index = 0, .go_name = "valid" }} }),
        api.function("echoColorRecord", .{ .params = &.{.{ .index = 0, .go_name = "value" }} }),
        api.function("flattenFlags", .{ .params = &.{.{ .index = 0, .go_name = "options", .contract = .{ .flatten = &.{"flags"} } }} }),
        api.in("Palette").function("create", .{ .params = &.{.{ .index = 0, .go_name = "flags" }} }),
        api.in("Palette").function("deinit", .{}),
        api.function("visitFlags", .{ .params = &.{ .{ .index = 0, .go_name = "callback" }, .{ .index = 1, .go_name = "userdata" } } }),
        api.function("panicError", .{}),
    },
});
