// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_opaque_H
#define ZIGO_opaque_H

#include <stddef.h>
#include <stdint.h>

typedef int8_t zg_mode;
#define ZG_MODE_FAST 1
#define ZG_MODE_LOW_WATER 2

typedef int8_t zg_level;
#define ZG_LEVEL_LOW -1
#define ZG_LEVEL_HIGH 0

typedef uint8_t zg_signal;
#define ZG_SIGNAL_QUIET 0
#define ZG_SIGNAL_LOUD 7

typedef uint8_t zg_plain;
#define ZG_PLAIN_ONE 1

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT int8_t zg_echo(int8_t mode);
ZIGO_EXPORT int8_t zg_pick_level(int8_t value);
ZIGO_EXPORT uint8_t zg_pick_signal(uint8_t value);
ZIGO_EXPORT uint8_t zg_pick_plain(uint8_t value);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_opaque_H
