// Code generated by zigo. DO NOT EDIT.

//! Rust bindings for `calculator`, generated by zigo.

pub mod raw;

/// Adds two signed 32-bit integers. The sum must fit in i32.
pub fn add(a: i32, b: i32) -> i32 {
    raw::add(a, b)
}
