// Code generated by zigo. DO NOT EDIT.
#ifndef ZIGO_input_H
#define ZIGO_input_H

#include <stddef.h>
#include <stdint.h>

typedef uint8_t zg_key;
#define ZG_KEY_A 0
#define ZG_KEY_ENTER 1

typedef int32_t zg_mode;
#define ZG_MODE_OFF 0
#define ZG_MODE_ON 1

// ELF and Mach-O export every non-static symbol of a shared library;
// COFF exports nothing without an explicit annotation, so a DLL built
// without this would load and then resolve none of its entry points.
#ifndef ZIGO_EXPORT
#if defined(_WIN32)
#define ZIGO_EXPORT __declspec(dllexport)
#else
#define ZIGO_EXPORT
#endif
#endif

ZIGO_EXPORT uint8_t zg_key_printable(uint8_t self);
ZIGO_EXPORT uint32_t zg_key_codepoint(uint8_t self);
ZIGO_EXPORT uint8_t zg_key_combine(uint8_t self, uint8_t other);
ZIGO_EXPORT uint8_t zg_mode_enabled(int32_t self);
ZIGO_EXPORT uint8_t zg_from_ascii(uint8_t ch);
ZIGO_EXPORT const char *zg_last_error_message(void);
ZIGO_EXPORT const char *zg_caught_panic_message(int32_t code);

#endif // ZIGO_input_H
