// Code generated by zigo. DO NOT EDIT.
package pipeline

import (
	"sync"
	"unsafe"

	"example.com/zigo/pipeline/internal/raw"
)

// Pipeline is a caller-owned native handle. Call Close when it is no longer needed.
type Pipeline struct {
	ptr             unsafe.Pointer
	once            sync.Once
	mu              sync.RWMutex
	callbackHandles []zigoCallbackHandle
}

// PipelineRef is a borrowed Pipeline reference that remains valid only while its parent is open.
type PipelineRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (p *Pipeline) zigoPointer() unsafe.Pointer {
	if p == nil {
		return nil
	}
	return p.ptr
}

func (p *PipelineRef) zigoPointer() unsafe.Pointer {
	if p == nil || p.ptr == nil {
		return nil
	}
	if parent := p.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return p.ptr
}

// Close releases the native Pipeline resources. It is safe to call more than once.
// The error result is always nil; it exists so Pipeline satisfies io.Closer.
func (p *Pipeline) Close() error {
	if p == nil {
		return nil
	}
	p.once.Do(func() {
		p.mu.Lock()
		defer p.mu.Unlock()
		if p.ptr != nil {
			raw.PipelineDeinit(p.ptr)
			p.ptr = nil
		}
		for _, handle := range p.callbackHandles {
			deleteCallbackHandle(handle)
		}
		p.callbackHandles = nil
	})
	return nil
}

// IntBatch is a caller-owned native handle. Call Close when it is no longer needed.
type IntBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	mu              sync.RWMutex
	callbackHandles []zigoCallbackHandle
}

// IntBatchRef is a borrowed IntBatch reference that remains valid only while its parent is open.
type IntBatchRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (i *IntBatch) zigoPointer() unsafe.Pointer {
	if i == nil {
		return nil
	}
	return i.ptr
}

func (i *IntBatchRef) zigoPointer() unsafe.Pointer {
	if i == nil || i.ptr == nil {
		return nil
	}
	if parent := i.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return i.ptr
}

// Close releases the native IntBatch resources. It is safe to call more than once.
// The error result is always nil; it exists so IntBatch satisfies io.Closer.
func (i *IntBatch) Close() error {
	if i == nil {
		return nil
	}
	i.once.Do(func() {
		i.mu.Lock()
		defer i.mu.Unlock()
		if i.ptr != nil {
			raw.IntBatchDeinit(i.ptr)
			i.ptr = nil
		}
		for _, handle := range i.callbackHandles {
			deleteCallbackHandle(handle)
		}
		i.callbackHandles = nil
	})
	return nil
}

// FloatBatch is a caller-owned native handle. Call Close when it is no longer needed.
type FloatBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	mu              sync.RWMutex
	callbackHandles []zigoCallbackHandle
}

// FloatBatchRef is a borrowed FloatBatch reference that remains valid only while its parent is open.
type FloatBatchRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (f *FloatBatch) zigoPointer() unsafe.Pointer {
	if f == nil {
		return nil
	}
	return f.ptr
}

func (f *FloatBatchRef) zigoPointer() unsafe.Pointer {
	if f == nil || f.ptr == nil {
		return nil
	}
	if parent := f.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return f.ptr
}

// Close releases the native FloatBatch resources. It is safe to call more than once.
// The error result is always nil; it exists so FloatBatch satisfies io.Closer.
func (f *FloatBatch) Close() error {
	if f == nil {
		return nil
	}
	f.once.Do(func() {
		f.mu.Lock()
		defer f.mu.Unlock()
		if f.ptr != nil {
			raw.FloatBatchDeinit(f.ptr)
			f.ptr = nil
		}
		for _, handle := range f.callbackHandles {
			deleteCallbackHandle(handle)
		}
		f.callbackHandles = nil
	})
	return nil
}
