// Code generated by zigo. DO NOT EDIT.
package pipeline

import (
	"runtime/cgo"
	"sync"
	"unsafe"

	"example.com/zigo/pipeline/internal/raw"
)

type Mode uint32

const ModeSum Mode = 0
const ModeWeighted Mode = 1

func (value Mode) String() string {
	switch value {
	case ModeSum:
		return "sum"
	case ModeWeighted:
		return "weighted"
	default:
		return "Mode(?)"
	}
}

type PipelineCallback func(int32) int32

type Pipeline struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type PipelineRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *Pipeline) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.PipelineDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}

type IntBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type IntBatchRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *IntBatch) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.IntBatchDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}

type FloatBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type FloatBatchRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *FloatBatch) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.FloatBatchDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}
