// Code generated by zigo. DO NOT EDIT.
package pipeline

import (
	"runtime/cgo"
	"sync"
	"unsafe"

	"example.com/zigo/pipeline/internal/raw"
)

type Mode uint32

const ModeSum Mode = 0
const ModeWeighted Mode = 1

func (value Mode) String() string {
	switch value {
	case ModeSum:
		return "sum"
	case ModeWeighted:
		return "weighted"
	default:
		return "Mode(?)"
	}
}

type PipelineCallback func(int32) int32

type Pipeline struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type PipelineRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *Pipeline) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.PipelineDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}

type IntBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type IntBatchRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *IntBatch) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.IntBatchDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}

type FloatBatch struct {
	ptr             unsafe.Pointer
	once            sync.Once
	callbackHandles []cgo.Handle
}

type FloatBatchRef struct {
	ptr    unsafe.Pointer
	parent any
}

func (value *FloatBatch) Close() {
	if value == nil {
		return
	}
	value.once.Do(func() {
		if value.ptr != nil {
			raw.FloatBatchDeinit(value.ptr)
			value.ptr = nil
		}
		for _, handle := range value.callbackHandles {
			deleteCallbackHandle(handle)
		}
		value.callbackHandles = nil
	})
}

func NewIntBatch() (*IntBatch, error) {
	result, code := raw.IntBatchCreate()
	if code != 0 {
		return nil, errorForCode(code)
	}
	return &IntBatch{ptr: result}, nil
}
func (i *IntBatch) Push(value int32) error {
	code := raw.IntBatchPush(i.ptr, value)
	if code != 0 {
		return errorForCode(code)
	}
	return nil
}
func (i *IntBatch) Len() uint {
	return raw.IntBatchLen(i.ptr)
}
func NewFloatBatch() (*FloatBatch, error) {
	result, code := raw.FloatBatchCreate()
	if code != 0 {
		return nil, errorForCode(code)
	}
	return &FloatBatch{ptr: result}, nil
}
func (f *FloatBatch) Push(p0 float64) error {
	code := raw.FloatBatchPush(f.ptr, p0)
	if code != 0 {
		return errorForCode(code)
	}
	return nil
}
func (f *FloatBatch) Len() uint {
	return raw.FloatBatchLen(f.ptr)
}
func NewPipeline(name string, mode Mode, callback PipelineCallback) (*Pipeline, error) {
	callbackHandle := newPipelineCallbackHandle(callback)
	result, code := raw.PipelineCreate([]byte(name), uint32(mode), uintptr(callbackHandle))
	if code != 0 {
		deleteCallbackHandle(callbackHandle)
		return nil, errorForCode(code)
	}
	return &Pipeline{ptr: result, callbackHandles: []cgo.Handle{callbackHandle}}, nil
}
func (p *Pipeline) Process(values []int32) (int64, error) {
	result, code := raw.PipelineProcess(p.ptr, values)
	if code != 0 {
		return 0, errorForCode(code)
	}
	return result, nil
}
func (p *Pipeline) Name() string {
	return string(raw.PipelineName(p.ptr))
}
func (p *Pipeline) Mode() Mode {
	return Mode(raw.PipelineMode(p.ptr))
}
func (p *Pipeline) SetEnabled(enabled bool) bool {
	return raw.PipelineSetEnabled(p.ptr, boolToUint8(enabled)) != 0
}
func (p *Pipeline) Processed() uint {
	return raw.PipelineProcessed(p.ptr)
}
func (p *Pipeline) Total() int64 {
	return raw.PipelineTotal(p.ptr)
}
func LiveBytes() uint {
	return raw.LiveBytes()
}
func CompressionBound(source_len uint) uint {
	return raw.CompressionBound(source_len)
}
