// Code generated by zigo. DO NOT EDIT.

//! Rust bindings for `buffers`, generated by zigo.

pub mod raw;

mod buffer;
pub use buffer::OwnedSlice;

/// Hands over a freshly allocated slice. The caller owns it.
pub fn take_digits(count: u32) -> OwnedSlice<i32> {
    let (result_ptr, result_len) = raw::take_digits(count);
    unsafe { OwnedSlice::from_raw(result_ptr, result_len, raw::zg_free_digits) }
}

/// Hands over a freshly allocated UTF-8 name.
pub fn take_name() -> OwnedSlice<u8> {
    let (result_ptr, result_len) = raw::take_name();
    unsafe { OwnedSlice::from_raw(result_ptr, result_len, raw::zg_free_name) }
}
