// Code generated by zigo. DO NOT EDIT.
package signal

import "example.com/zigo/signal/internal/raw"


// NewSignal creates a caller-owned Signal.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewSignal() (*Signal, error) {
	result, code := raw.SignalCreate()
	if code != 0 {
		return nil, errorForCode("NewSignal", code)
	}
	return &Signal{ptr: result}, nil
}

// SetTicks invokes the bound Zig Signal.setTicks operation.
// It panics with *HandleError if a required handle is nil or closed.
func (s *Signal) SetTicks(ticks uint32) {
	raw.SignalSetTicks(zigoMustPointer("Signal.SetTicks receiver", s), ticks)
}

// SetMode invokes the bound Zig Signal.setMode operation.
// It panics with *HandleError if a required handle is nil or closed.
func (s *Signal) SetMode(mode Mode) {
	raw.SignalSetMode(zigoMustPointer("Signal.SetMode receiver", s), uint8(mode))
}

// SetActive invokes the bound Zig Signal.setActive operation.
// It panics with *HandleError if a required handle is nil or closed.
func (s *Signal) SetActive(active bool) {
	raw.SignalSetActive(zigoMustPointer("Signal.SetActive receiver", s), boolToUint8(active))
}
