// Code generated by zigo. DO NOT EDIT.
package signal

import (
	"unsafe"

	"example.com/zigo/signal/internal/raw"
)

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return zigoCheckedPointer(operation, value)
}

const (
	zigoProjectionMismatch uint8 = iota
	zigoProjectionSuccess
	zigoProjectionInvalidHandle
	zigoProjectionPanic
)

func zigoProjectionError(operation string, status uint8) error {
	switch status {
	case zigoProjectionInvalidHandle:
		return &HandleError{Operation: operation}
	case zigoProjectionPanic:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	default:
		return &StatusError{Operation: operation, Status: status}
	}
}

func zigoMust[T any](value T, err error) T {
	if err != nil {
		panic(err)
	}
	return value
}

func zigoMustMatch[T any](value T, matched bool, err error) (T, bool) {
	if err != nil {
		panic(err)
	}
	return value, matched
}

func boolToUint8(value bool) uint8 {
	if value {
		return 1
	}
	return 0
}
