// Code generated by zigo. DO NOT EDIT.
package signal

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/signal/internal/raw"
)

// Signal is a caller-owned native handle. Call Close when it is no longer needed.
type Signal struct {
	ptr     unsafe.Pointer
	once    sync.Once
	mu      sync.RWMutex
	cleanup runtime.Cleanup
}

// SignalRef is a borrowed Signal reference that remains valid only while its parent is open.
type SignalRef struct {
	ptr    unsafe.Pointer
	parent zigoHandle
}

func (s *Signal) zigoPointer() unsafe.Pointer {
	if s == nil {
		return nil
	}
	return s.ptr
}

func (s *SignalRef) zigoPointer() unsafe.Pointer {
	if s == nil || s.ptr == nil {
		return nil
	}
	if parent := s.parent; parent != nil && parent.zigoPointer() == nil {
		return nil
	}
	return s.ptr
}

type signalCleanupState struct {
	ptr unsafe.Pointer
}

func newSignal(ptr unsafe.Pointer) *Signal {
	value := &Signal{ptr: ptr}
	state := signalCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupSignal, state)
	return value
}

func cleanupSignal(state signalCleanupState) {
	if state.ptr != nil {
		raw.SignalDeinit(state.ptr)
	}
}

// Close releases the native Signal resources. It is safe to call more than once.
// The error result is always nil; it exists so Signal satisfies io.Closer.
func (s *Signal) Close() error {
	if s == nil {
		return nil
	}
	s.once.Do(func() {
		s.mu.Lock()
		defer s.mu.Unlock()
		s.cleanup.Stop()
		cleanupSignal(signalCleanupState{ptr: s.ptr})
		s.ptr = nil
	})
	runtime.KeepAlive(s)
	return nil
}
