// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);

export fn zg_handle_counter_impl(self: *const target.Handle, out_result: *u64) i32 {
    out_result.* = self.counter.load(.seq_cst);
    return 0;
}
export fn zg_handle_set_counter_impl(self: *target.Handle, v: u64) i32 {
    self.counter.store(v, .seq_cst);
    return 0;
}
export fn zg_round_trip_impl(value: u64) u64 {
    return (target.roundTrip(.init(value))).raw;
}
export fn zg_configure_impl(limit: i32) void {
    target.configure(target.Options{ .limit = .init(limit) });
}
export fn zg_echo_record_impl(value: *const target.Record, out_result: *target.Record) void {
    out_result.* = target.echoRecord(value.*);
}
export fn zg_echo_event_impl(value_tag: u8, value_count: u64, out_result: *zg_event_snapshot_t) i32 {
    const result = target.echoEvent(switch (value_tag) {
        0 => target.Event{ .count = .init(value_count) },
        1 => target.Event.none,
        else => @panic("zigo: invalid tag for argument `value`"),
    });
    out_result.* = std.mem.zeroes(zg_event_snapshot_t);
    switch (result) {
        .count => |value| {
            out_result.tag = 0;
            out_result.count = value.raw;
        },
        .none => out_result.tag = 1,
    }
    return 0;
}

const zg_event_snapshot_t = extern struct {
    tag: u8,
    count: u64,
};

/// Fails this compile when a layout zigo reflected on the build host does
/// not describe the compilation target. The usual cause is a C type whose
/// width varies by target -- `c_long` and `c_ulong` are 4 bytes on Windows
/// and 8 bytes on Linux and macOS, and `c_longdouble` varies too. Use a
/// fixed-width type in the binding surface, or generate on the target.
fn zigoAbiGuard(comptime what: []const u8, comptime reflected: usize, comptime actual: usize) void {
    if (reflected != actual) @compileError(std.fmt.comptimePrint(
        "zigo ABI guard: {s} is {d} on this target, but zigo reflected {d} on the build host. " ++
            "The generated C header and Go mirrors use the reflected layout, so this binding " ++
            "cannot be built for this target. A C type whose width varies by target, such as " ++
            "c_long or c_ulong, is the usual cause; replace it with a fixed-width type.",
        .{ what, actual, reflected },
    ));
}

comptime {
    zigoAbiGuard("@sizeOf(Record)", 8, @sizeOf(target.Record));
    zigoAbiGuard("@alignOf(Record)", 8, @alignOf(target.Record));
    zigoAbiGuard("@offsetOf(Record, \"count\")", 0, @offsetOf(target.Record, "count"));
}
