// Code generated by zigo. DO NOT EDIT.

// Package cbbytes provides Go bindings generated by zigo.
package cbbytes

import "example.com/zigo/cbbytes/internal/raw"

// LibraryError reports a native shared-library loading failure.
type LibraryError = raw.LibraryError

// LoadLibrary atomically loads all generated native entry points.
func LoadLibrary(path string) error { return raw.LoadLibrary(path) }

// LibraryLoaded reports whether the native call surface is ready.
func LibraryLoaded() bool { return raw.LibraryLoaded() }

// DefaultLibraryName is the installed shared-library basename for the running platform.
// LoadLibrary falls back to it when no explicit path and no ZIGO_LIBRARY_PATH are set.
var DefaultLibraryName = raw.DefaultLibraryName


// OnLog calls the Zig function onLog.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func OnLog(callback OnLogCallback) {
	callbackHandle := zigoNewOnLogCallbackHandle(callback)
	defer zigoDeleteCallbackHandle(callbackHandle)
	raw.OnLog(raw.CallbackPointer0(), uintptr(callbackHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("OnLog", callbackHandle)
	}
}

// OnChunk calls the Zig function onChunk.
// A panic in a Go callback is rethrown as *CallbackPanicError once the native call returns.
func OnChunk(callback OnChunkCallback) {
	callbackHandle := zigoNewOnChunkCallbackHandle(callback)
	defer zigoDeleteCallbackHandle(callbackHandle)
	raw.OnChunk(raw.CallbackPointer1(), uintptr(callbackHandle))
	if zigoCallbackPanicPending() {
		zigoRethrowCallbackPanic("OnChunk", callbackHandle)
	}
}
