// Code generated by zigo. DO NOT EDIT.

package interfaces

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/interfaces/internal/raw"
)

// IntBatch is a caller-owned native handle. Call Close when it is no longer needed.
type IntBatch struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins i open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (i *IntBatch) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if i == nil {
		return nil, &HandleError{Operation: operation}
	}
	i.mu.Lock()
	defer i.mu.Unlock()
	if i.closed || i.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if i.poison != nil {
		return nil, i.poison.poisoned(operation)
	}
	i.active++
	return i.ptr, nil
}

func (i *IntBatch) zigoRelease() {
	if i == nil {
		return
	}
	i.mu.Lock()
	i.active--
	state, release := i.zigoTakeLocked()
	i.mu.Unlock()
	if release {
		cleanupIntBatch(state)
	}
}

// zigoPoison marks i unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (i *IntBatch) zigoPoison(cause *NativePanicError) {
	if i == nil {
		return
	}
	i.mu.Lock()
	defer i.mu.Unlock()
	if i.poison == nil {
		i.poison = cause
		i.cleanup.Stop()
	}
}

type intBatchCleanupState struct {
	ptr unsafe.Pointer
}

func newIntBatch(ptr unsafe.Pointer) *IntBatch {
	value := &IntBatch{ptr: ptr}
	state := intBatchCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupIntBatch, state)
	return value
}

func cleanupIntBatch(state intBatchCleanupState) {
	if state.ptr != nil {
		raw.IntBatchDeinit(state.ptr)
	}
}

// Close releases the native IntBatch resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native; otherwise the error is nil.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (i *IntBatch) Close() error {
	if i == nil {
		return nil
	}
	i.mu.Lock()
	if i.closed {
		i.mu.Unlock()
		return nil
	}
	if i.active != 0 {
		active := i.active
		i.mu.Unlock()
		return &HandleInUseError{Operation: "IntBatch.Close", Children: active}
	}
	i.closed = true
	i.cleanup.Stop()
	state, release := i.zigoTakeLocked()
	i.mu.Unlock()
	if release {
		cleanupIntBatch(state)
	}
	runtime.KeepAlive(i)
	return nil
}

// zigoTakeLocked hands out what is left to release once i is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (i *IntBatch) zigoTakeLocked() (intBatchCleanupState, bool) {
	if !i.closed || i.active != 0 || i.ptr == nil {
		return intBatchCleanupState{}, false
	}
	state := intBatchCleanupState{ptr: i.ptr}
	i.ptr = nil
	if i.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// FloatBatch is a caller-owned native handle. Call Close when it is no longer needed.
type FloatBatch struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins f open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (f *FloatBatch) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if f == nil {
		return nil, &HandleError{Operation: operation}
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.closed || f.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if f.poison != nil {
		return nil, f.poison.poisoned(operation)
	}
	f.active++
	return f.ptr, nil
}

func (f *FloatBatch) zigoRelease() {
	if f == nil {
		return
	}
	f.mu.Lock()
	f.active--
	state, release := f.zigoTakeLocked()
	f.mu.Unlock()
	if release {
		cleanupFloatBatch(state)
	}
}

// zigoPoison marks f unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (f *FloatBatch) zigoPoison(cause *NativePanicError) {
	if f == nil {
		return
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.poison == nil {
		f.poison = cause
		f.cleanup.Stop()
	}
}

type floatBatchCleanupState struct {
	ptr unsafe.Pointer
}

func newFloatBatch(ptr unsafe.Pointer) *FloatBatch {
	value := &FloatBatch{ptr: ptr}
	state := floatBatchCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, cleanupFloatBatch, state)
	return value
}

func cleanupFloatBatch(state floatBatchCleanupState) {
	if state.ptr != nil {
		raw.FloatBatchDeinit(state.ptr)
	}
}

// Close releases the native FloatBatch resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native; otherwise the error is nil.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (f *FloatBatch) Close() error {
	if f == nil {
		return nil
	}
	f.mu.Lock()
	if f.closed {
		f.mu.Unlock()
		return nil
	}
	f.closed = true
	f.cleanup.Stop()
	state, release := f.zigoTakeLocked()
	f.mu.Unlock()
	if release {
		cleanupFloatBatch(state)
	}
	runtime.KeepAlive(f)
	return nil
}

// zigoTakeLocked hands out what is left to release once f is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (f *FloatBatch) zigoTakeLocked() (floatBatchCleanupState, bool) {
	if !f.closed || f.active != 0 || f.ptr == nil {
		return floatBatchCleanupState{}, false
	}
	state := floatBatchCleanupState{ptr: f.ptr}
	f.ptr = nil
	if f.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Window represents a native Zig handle.
type Window struct {
	ptr    unsafe.Pointer
	mu     sync.Mutex
	active int
	closed bool
	poison *NativePanicError
	owner  zigoHandle
}

func newBorrowedWindow(ptr unsafe.Pointer, owner zigoHandle) *Window {
	return &Window{ptr: ptr, owner: owner}
}

// zigoAcquire pins w and its parent open for one native call.
func (w *Window) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if w == nil {
		return nil, &HandleError{Operation: operation}
	}
	w.mu.Lock()
	parent := w.owner
	w.mu.Unlock()
	if parent != nil {
		if _, err := parent.zigoAcquire(operation); err != nil {
			return nil, err
		}
	}
	w.mu.Lock()
	var err error
	switch {
	case w.closed || w.ptr == nil:
		err = &HandleError{Operation: operation}
	case w.poison != nil:
		err = w.poison.poisoned(operation)
	default:
		w.active++
	}
	ptr := w.ptr
	w.mu.Unlock()
	if err != nil {
		if parent != nil {
			parent.zigoRelease()
		}
		return nil, err
	}
	return ptr, nil
}

func (w *Window) zigoRelease() {
	if w == nil {
		return
	}
	w.mu.Lock()
	w.active--
	parent := w.owner
	w.mu.Unlock()
	if parent != nil { parent.zigoRelease() }
}

// zigoPoison marks w unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (w *Window) zigoPoison(cause *NativePanicError) {
	if w == nil {
		return
	}
	w.mu.Lock()
	parent := w.owner
	if w.poison == nil {
		w.poison = cause
	}
	w.mu.Unlock()
	if parent != nil {
		parent.zigoPoison(cause)
	}
}

// Close detaches this borrowed Window view without releasing native resources.
func (w *Window) Close() error {
	if w == nil { return nil }
	w.mu.Lock()
	if w.closed { w.mu.Unlock(); return nil }
	if w.active != 0 {
		active := w.active
		w.mu.Unlock()
		return &HandleInUseError{Operation: "Window.Close", Children: active}
	}
	w.closed = true
	w.ptr = nil
	w.owner = nil
	w.mu.Unlock()
	return nil
}
