// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

import (
	"errors"
	"fmt"
	"os"
	"runtime"
	"sync"
	"sync/atomic"
	"unsafe"

	"github.com/ebitengine/purego"
)

// DefaultLibraryName is the installed shared-library basename for the running platform.
// It is empty on platforms this backend does not support.
var DefaultLibraryName = map[string]string{"darwin": "libborrowed_return_zigo.dylib", "linux": "libborrowed_return_zigo.so", "windows": "borrowed_return_zigo.dll"}[runtime.GOOS]

// ErrLibraryLoad identifies a shared-library load or symbol resolution failure.
var ErrLibraryLoad = errors.New("zigo: shared library unavailable")

// LibraryError reports a native library loading or symbol resolution failure.
type LibraryError struct {
	Path string
	Symbol string
	Operation string
	Cause error
}

// Error describes the failed loading operation.
func (err *LibraryError) Error() string {
	if err.Symbol != "" { return fmt.Sprintf("zigo: %s %q from %q: %v", err.Operation, err.Symbol, err.Path, err.Cause) }
	if err.Path == "" { return fmt.Sprintf("zigo: %s: %v", err.Operation, err.Cause) }
	return fmt.Sprintf("zigo: %s %q: %v", err.Operation, err.Path, err.Cause)
}
// Is reports ErrLibraryLoad so every generated error classifies the same way.
func (err *LibraryError) Is(target error) bool { return target == ErrLibraryLoad }
// Unwrap returns the platform loader error.
func (err *LibraryError) Unwrap() error { return err.Cause }

type nativeBindings struct {
	lastError func() unsafe.Pointer
	fnNewParent func(*unsafe.Pointer) int32
	fnParentFreeParent func(unsafe.Pointer) int32
	fnParentView func(unsafe.Pointer, *unsafe.Pointer) int32
	fnParentMaybeView func(unsafe.Pointer, *unsafe.Pointer) int32
	fnParentCheckedView func(unsafe.Pointer, *unsafe.Pointer) int32
	fnViewTouch func(unsafe.Pointer, *int32) int32
}

var loadedBindings atomic.Pointer[nativeBindings]
var loadMu sync.Mutex
var successfulLibraryPath string

// LibraryLoaded reports whether every required native symbol was published.
func LibraryLoaded() bool { return loadedBindings.Load() != nil }

// libraryEnvVars are consulted in order when no explicit path is given.
var libraryEnvVars = []string{"ZIGO_BORROWED_RETURN_LIBRARY_PATH", "ZIGO_LIBRARY_PATH"}

// libraryCandidates lists the paths a load attempt tries, in order.
func libraryCandidates(explicit string) []string {
	if explicit != "" { return []string{explicit} }
	candidates := make([]string, 0, 2)
	for _, name := range libraryEnvVars {
		if value := os.Getenv(name); value != "" { candidates = append(candidates, value) }
	}
	if DefaultLibraryName != "" { candidates = append(candidates, DefaultLibraryName) }
	return candidates
}

// LoadLibrary atomically loads and registers every required native symbol.
// An empty path uses the configured candidates. A failed load leaves the
// binding retryable; a successful handle is never unloaded.
func LoadLibrary(path string) error {
	loadMu.Lock()
	defer loadMu.Unlock()
	return loadLibraryLocked(path)
}

func loadLibraryLocked(explicit string) error {
	candidates := libraryCandidates(explicit)
	if len(candidates) == 0 { return &LibraryError{Operation: "load", Cause: errors.New("no shared-library candidate is configured for this platform; pass an explicit path")} }
	if loadedBindings.Load() != nil {
		for _, candidate := range candidates { if candidate == successfulLibraryPath { return nil } }
		return &LibraryError{Path: candidates[0], Operation: "load", Cause: errors.New("a different library is already loaded")}
	}
	attempts := make([]error, 0, len(candidates))
	for _, candidate := range candidates {
		if err := loadCandidate(candidate); err != nil { attempts = append(attempts, err); continue }
		successfulLibraryPath = candidate
		return nil
	}
	// One candidate keeps the precise path and symbol of its own failure.
	if len(attempts) == 1 { return attempts[0] }
	return &LibraryError{Operation: "load", Cause: errors.Join(attempts...)}
}

// loadCandidate publishes the call surface only after every symbol resolves.
func loadCandidate(path string) error {
	handle, err := openLibrary(path)
	if err != nil { return &LibraryError{Path: path, Operation: "open", Cause: err} }
	fail := func(symbol string, cause error) error { closeLibrary(handle); return &LibraryError{Path: path, Symbol: symbol, Operation: "resolve", Cause: cause} }
	addrLastError, err := resolveSymbol(handle, "zg_last_error_message")
	if err != nil { return fail("zg_last_error_message", err) }
	addrNewParent, err := resolveSymbol(handle, "zg_new_parent")
	if err != nil { return fail("zg_new_parent", err) }
	addrParentFreeParent, err := resolveSymbol(handle, "zg_parent_free_parent")
	if err != nil { return fail("zg_parent_free_parent", err) }
	addrParentView, err := resolveSymbol(handle, "zg_parent_view")
	if err != nil { return fail("zg_parent_view", err) }
	addrParentMaybeView, err := resolveSymbol(handle, "zg_parent_maybe_view")
	if err != nil { return fail("zg_parent_maybe_view", err) }
	addrParentCheckedView, err := resolveSymbol(handle, "zg_parent_checked_view")
	if err != nil { return fail("zg_parent_checked_view", err) }
	addrViewTouch, err := resolveSymbol(handle, "zg_view_touch")
	if err != nil { return fail("zg_view_touch", err) }
	var next nativeBindings
	purego.RegisterFunc(&next.lastError, addrLastError)
	purego.RegisterFunc(&next.fnNewParent, addrNewParent)
	purego.RegisterFunc(&next.fnParentFreeParent, addrParentFreeParent)
	purego.RegisterFunc(&next.fnParentView, addrParentView)
	purego.RegisterFunc(&next.fnParentMaybeView, addrParentMaybeView)
	purego.RegisterFunc(&next.fnParentCheckedView, addrParentCheckedView)
	purego.RegisterFunc(&next.fnViewTouch, addrViewTouch)
	loadedBindings.Store(&next)
	return nil
}

func bindings() *nativeBindings {
	value := loadedBindings.Load()
	if value == nil { panic("zigo: native library is not loaded; call LoadLibrary first") }
	return value
}

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string {
	p := bindings().lastError()
	if p == nil { return "" }
	length := 0
	for *(*byte)(unsafe.Add(p, length)) != 0 { length++ }
	return string(unsafe.Slice((*byte)(p), length))
}

// NewParent calls the generated purego ABI wrapper for zg_new_parent.
func NewParent() (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnNewParent(&outResult)
	return outResult, code
}

// ParentFreeParent calls the generated purego ABI wrapper for zg_parent_free_parent.
func ParentFreeParent(self unsafe.Pointer) int32 {
	code := bindings().fnParentFreeParent(self)
	return code
}

// ParentView calls the generated purego ABI wrapper for zg_parent_view.
func ParentView(self unsafe.Pointer) (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnParentView(self, &outResult)
	return outResult, code
}

// ParentMaybeView calls the generated purego ABI wrapper for zg_parent_maybe_view.
func ParentMaybeView(self unsafe.Pointer) (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnParentMaybeView(self, &outResult)
	return outResult, code
}

// ParentCheckedView calls the generated purego ABI wrapper for zg_parent_checked_view.
func ParentCheckedView(self unsafe.Pointer) (unsafe.Pointer, int32) {
	var outResult unsafe.Pointer
	code := bindings().fnParentCheckedView(self, &outResult)
	return outResult, code
}

// ViewTouch calls the generated purego ABI wrapper for zg_view_touch.
func ViewTouch(self unsafe.Pointer) (int32, int32) {
	var outResult int32
	code := bindings().fnViewTouch(self, &outResult)
	return outResult, code
}
