// Code generated by zigo. DO NOT EDIT.

//! Rust bindings for `terminal`, generated by zigo.

pub mod raw;

mod error;
pub use error::{Error, ErrorKind};

mod handle;
pub use handle::*;

mod buffer;
pub use buffer::OwnedSlice;
