// Code generated by zigo. DO NOT EDIT.

// Package packages provides Go bindings generated by zigo.
package packages

import (
	"example.com/zigo/packages/internal/raw"
	zigo_pkg_model "example.com/zigo/packages/packages/model"
)


// UseMode calls the Zig function useMode.
func UseMode(mode zigo_pkg_model.Mode) {
	raw.UseMode(uint8(mode))
}

// InspectPoint calls the Zig function inspectPoint.
func InspectPoint(point zigo_pkg_model.Point) zigo_pkg_model.Point {
	return zigoPointFromRaw(raw.InspectPoint(zigoPointToRaw(point)))
}
