// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);
pub const std_options: std.Options = if (@hasDecl(target, "std_options")) target.std_options else .{};

export fn zg_sum_impl(values_ptr: [*c]const i32, values_len: usize) i64 {
    return target.sum(if (values_len == 0) &.{} else values_ptr[0..values_len]);
}
export fn zg_measure_impl(text_ptr: [*c]const u8, text_len: usize) usize {
    return target.measure(if (text_len == 0) &.{} else text_ptr[0..text_len]);
}
