// Code generated by zigo. DO NOT EDIT.

// Package opaque provides Go bindings generated by zigo.
package opaque

import (
	"runtime"

	"example.com/zigo/opaque/internal/raw"
)

// NewContext creates a caller-owned Context.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewContext() (*Context, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.ContextCreate()
	if code != 0 {
		return nil, errorForCode("NewContext", code)
	}
	return newContext(result), nil
}

// Add calls the Zig function Context.add.
// It returns *HandleError if a required handle is nil or closed.
func (c *Context) Add(value int64) (int64, error) {
	ptr, err := zigoCheckedPointer("Context.Add receiver", c)
	if err != nil {
		return 0, err
	}
	defer c.zigoRelease()
	return raw.ContextAdd(ptr, value), nil
}

// Crash panics inside a method: what leaves a handle poisoned.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (c *Context) Crash() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.Crash receiver", c)
	if err != nil {
		return err
	}
	defer c.zigoRelease()
	code := raw.ContextCrash(ptr)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Context.Crash", code), c)
	}
	return nil
}

// LiveBytes calls the Zig function liveBytes.
func LiveBytes() uint {
	return raw.LiveBytes()
}

// Echo
// Echoes UTF-8 text without changing its bytes.
func Echo(text string) string {
	return string(raw.Echo([]byte(text)))
}

// Fallback calls the Zig function fallback.
func Fallback(p0 int64) int64 {
	return raw.Fallback(p0)
}
