// Code generated by zigo. DO NOT EDIT.

// Package opaque provides Go bindings generated by zigo.
//
// Handles that live in Zig and travel through Go as opaque pointers.
// This block sits in the bindings file, which zigo reads before the library's
// root module: it is the one file the binding's author owns.
package opaque

import (
	"runtime"

	"example.com/zigo/opaque/internal/raw"
)

// NewContext creates a caller-owned Context.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewContext() (*Context, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, code := raw.ContextCreate()
	if code != 0 {
		return nil, errorForCode("NewContext", code)
	}
	return newContext(result), nil
}

// Add calls the Zig function Context.add.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (c *Context) Add(value int64) (int64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.Add receiver", c)
	if err != nil {
		return 0, err
	}
	defer c.zigoRelease()
	result, code := raw.ContextAdd(ptr, value)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Context.Add", code), c)
	}
	return result, nil
}

// MaybeTotal calls the Zig function Context.maybeTotal.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (c *Context) MaybeTotal(present bool) (int64, bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.MaybeTotal receiver", c)
	if err != nil {
		return 0, false, err
	}
	defer c.zigoRelease()
	result, zigoHas, code := raw.ContextMaybeTotal(ptr, boolToUint8(present))
	if code != 0 {
		return 0, false, zigoPoisonAfterPanic(errorForCode("Context.MaybeTotal", code), c)
	}
	return result, zigoHas, nil
}

// SetTotal calls the Zig function Context.setTotal.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (co *Context) SetTotal(c int64) error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.SetTotal receiver", co)
	if err != nil {
		return err
	}
	defer co.zigoRelease()
	code := raw.ContextSetTotal(ptr, c)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Context.SetTotal", code), co)
	}
	return nil
}

// Crash panics inside a method: what leaves a handle poisoned.
// It returns *HandleError if a required handle is nil or closed.
// Native failures are returned as generated error values.
func (c *Context) Crash() error {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.Crash receiver", c)
	if err != nil {
		return err
	}
	defer c.zigoRelease()
	code := raw.ContextCrash(ptr)
	if code != 0 {
		return zigoPoisonAfterPanic(errorForCode("Context.Crash", code), c)
	}
	return nil
}

// CrashInfallible panics from a method that returns no error union.
// Its Go signature still carries an `error` -- the handle check has to
// be reportable -- so the panic reaches the caller through that.
// It returns *HandleError if a required handle is nil or closed.
// A native panic is returned as *NativePanicError.
func (c *Context) CrashInfallible() (int64, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	ptr, err := zigoCheckedPointer("Context.CrashInfallible receiver", c)
	if err != nil {
		return 0, err
	}
	defer c.zigoRelease()
	result, code := raw.ContextCrashInfallible(ptr)
	if code != 0 {
		return 0, zigoPoisonAfterPanic(errorForCode("Context.CrashInfallible", code), c)
	}
	return result, nil
}

// CrashFatal
// A free function with no handle and no promoted integer has no `error` in
// its Go signature, so a panic here has nowhere to be reported. Zig calls
// that fatal, and so does zigo: the message goes to stderr and the process
// aborts.
func CrashFatal() {
	raw.CrashFatal()
}

// LiveBytes calls the Zig function liveBytes.
func LiveBytes() uint {
	return raw.LiveBytes()
}

// Echo
// Echoes UTF-8 text without changing its bytes.
func Echo(text string) string {
	return string(raw.Echo([]byte(text)))
}

// Fallback calls the Zig function fallback.
func Fallback(p0 int64) int64 {
	return raw.Fallback(p0)
}
