// Code generated by zigo. DO NOT EDIT.

// Package raw is the generated call layer between the public package and
// the native library. It is not part of the supported API.
package raw

/*
#cgo CFLAGS: -I${SRCDIR}/../../../zig-out/include
#cgo LDFLAGS: ${SRCDIR}/../../../zig-out/lib/libstore_zigo.a
#include "zigo_store.h"
*/
import "C"
import "unsafe"

// LastErrorMessage returns the most recent native panic message for this binding.
func LastErrorMessage() string { return C.GoString(C.zg_last_error_message()) }

// StoreOpen calls the generated C ABI wrapper for zg_store_open.
func StoreOpen(name string) (unsafe.Pointer, int32) {
	var nameZero C.uint8_t
	namePtr := &nameZero
	if len(name) != 0 {
		namePtr = (*C.uint8_t)(unsafe.Pointer(unsafe.StringData(name)))
	}
	var outResult *C.zg_store
	code := int32(C.zg_store_open(namePtr, C.size_t(len(name)), &outResult))
	return unsafe.Pointer(outResult), code
}
// StoreFlush calls the generated C ABI wrapper for zg_store_flush.
func StoreFlush(self unsafe.Pointer) int32 {
	code := int32(C.zg_store_flush((*C.zg_store)(self)))
	return code
}
// StoreDeinit calls the generated C ABI wrapper for zg_store_deinit.
func StoreDeinit(self unsafe.Pointer) int32 {
	code := int32(C.zg_store_deinit((*C.zg_store)(self)))
	return code
}
// CursorInit calls the generated C ABI wrapper for zg_cursor_init.
func CursorInit(column uint32) (unsafe.Pointer, int32) {
	var outResult *C.zg_cursor
	code := int32(C.zg_cursor_init(C.uint32_t(column), &outResult))
	return unsafe.Pointer(outResult), code
}
// CursorDeinit calls the generated C ABI wrapper for zg_cursor_deinit.
func CursorDeinit(self unsafe.Pointer) int32 {
	code := int32(C.zg_cursor_deinit((*C.zg_cursor)(self)))
	return code
}
