// Code generated by zigo. DO NOT EDIT.

// Package optslice provides Go bindings generated by zigo.
package optslice

import (
	"runtime"

	"example.com/zigo/optslice/internal/raw"
)


// Measure calls the Zig function measure.
func Measure(text *string) uint {
	var textRaw *[]byte
	if text != nil {
		textRawValue := []byte(*text)
		textRaw = &textRawValue
	}
	return raw.Measure(textRaw)
}

// Label calls the Zig function label.
func Label(text *string) uint {
	return raw.Label(text)
}

// Total calls the Zig function total.
func Total(values *[]int32) int32 {
	return raw.Total(values)
}

// Digits calls the Zig function digits.
func Digits(count uint32) ([]int32, bool) {
	zigoResult, zigoHas := raw.Digits(count)
	return zigoResult, zigoHas
}

// Name calls the Zig function name.
func Name(count uint32) (string, bool) {
	zigoResult, zigoHas := raw.Name(count)
	return string(zigoResult), zigoHas
}

// CheckedDigits calls the Zig function checkedDigits.
// Native failures are returned as generated error values.
func CheckedDigits(count uint32) ([]int32, bool, error) {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	result, zigoHas, code := raw.CheckedDigits(count)
	if code != 0 {
		return nil, false, errorForCode("CheckedDigits", code)
	}
	return result, zigoHas, nil
}
