// Code generated by zigo. DO NOT EDIT.

package atomic_value

import "strconv"

// EventTag represents the corresponding Zig enum.
type EventTag uint8

const (
	// EventTagCount corresponds to the Zig tag count.
	EventTagCount EventTag = 0
	// EventTagNone corresponds to the Zig tag none.
	EventTagNone EventTag = 1
)

var zigoEventTagNames = [2]string{
	0: "count",
	1: "none",
}

// String returns the Zig tag name.
func (value EventTag) String() string {
	if value >= 0 && value <= 1 {
		return zigoEventTagNames[uint64(value)]
	}
	return "EventTag(" + strconv.Itoa(int(value)) + ")"
}
