// Code generated by zigo. DO NOT EDIT.
const std = @import("std");
const target = @import("zigo_target");

extern fn zg_panic_bridge(message: [*]const u8, length: usize) callconv(.c) noreturn;
fn panicHandler(message: []const u8, _: ?usize) noreturn {
    zg_panic_bridge(message.ptr, message.len);
}
pub const panic = std.debug.FullPanic(panicHandler);

extern fn zg_on_location_go_callback_callback(p0: i32, p1: usize) callconv(.c) void;
fn zg_on_location_callback_packed_thunk(p0: target.Location, p1: usize) callconv(.c) void {
    zg_on_location_go_callback_callback(@intFromEnum(p0), p1);
}
extern fn zg_on_stream_go_callback_callback(p0: *target.Stream, p1: i32, p2: usize) callconv(.c) void;
fn zg_on_stream_callback_packed_thunk(p0: *target.Stream, p1: target.Location, p2: usize) callconv(.c) void {
    zg_on_stream_go_callback_callback(p0, @intFromEnum(p1), p2);
}
extern fn zg_on_view_go_callback_callback(p0: ?*const target.Stream, p1: usize) callconv(.c) u8;
fn zg_on_view_callback_packed_thunk(p0: ?*const target.Stream, p1: usize) callconv(.c) bool {
    return zg_on_view_go_callback_callback(p0, p1) != 0;
}
extern fn zg_pick_location_go_callback_callback(p0: i32, p1: usize) callconv(.c) i32;
fn zg_pick_location_callback_packed_thunk(p0: i32, p1: usize) callconv(.c) target.Location {
    return @enumFromInt(zg_pick_location_go_callback_callback(p0, p1));
}

export fn zg_on_location_impl(userdata: usize) void {
    target.onLocation(&zg_on_location_callback_packed_thunk, userdata);
}
export fn zg_on_stream_impl(userdata: usize) void {
    target.onStream(&zg_on_stream_callback_packed_thunk, userdata);
}
export fn zg_on_view_impl(userdata: usize) void {
    target.onView(&zg_on_view_callback_packed_thunk, userdata);
}
export fn zg_pick_location_impl(userdata: usize) void {
    target.pickLocation(&zg_pick_location_callback_packed_thunk, userdata);
}
