// Code generated by zigo. DO NOT EDIT.
package callback

import (
	"errors"
	"strconv"

	"example.com/zigo/callback/internal/raw"
)

// ErrInvalidHandle identifies a nil, closed, or invalid borrowed handle.
var ErrInvalidHandle = errors.New("zigo: nil or closed handle")

// ErrNativePanic identifies a Zig panic caught at the native boundary.
var ErrNativePanic = errors.New("zigo: native panic")

// HandleError reports which generated operation received an invalid handle.
type HandleError struct {
	// Operation names the generated operation and offending receiver or parameter.
	Operation string
}

// Error implements error.
func (err *HandleError) Error() string {
	return "zigo: " + err.Operation + ": nil or closed handle"
}

// Unwrap returns ErrInvalidHandle for errors.Is classification.
func (err *HandleError) Unwrap() error { return ErrInvalidHandle }

// NativePanicError reports a Zig panic caught at the native boundary.
type NativePanicError struct {
	// Operation names the generated call or projection.
	Operation string
	// Message is the native panic message when available.
	Message string
}

// Error implements error.
func (err *NativePanicError) Error() string {
	if err.Message == "" {
		return "zigo: " + err.Operation + ": native panic"
	}
	return "zigo: " + err.Operation + ": native panic: " + err.Message
}

// Unwrap returns ErrNativePanic for errors.Is classification.
func (err *NativePanicError) Unwrap() error { return ErrNativePanic }

// Error is a stable Zig error-set value returned by the generated binding.
type Error struct {
	// Code is the stable integer stored in errors.lock.json.
	Code int32
	// Name is the Zig error name, optionally followed by native panic context.
	Name string
}

// Error implements error.
func (err *Error) Error() string { return err.Name }

// Is compares generated errors by stable code.
func (err *Error) Is(target error) bool {
	other, ok := target.(*Error)
	return ok && err.Code == other.Code
}

// ErrOutOfMemory represents Zig error.OutOfMemory.
var ErrOutOfMemory = &Error{Code: 1, Name: "OutOfMemory"}

func errorForCode(operation string, code int32) error {
	switch code {
	case -2:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	case 1:
		return ErrOutOfMemory
	default:
		return &Error{Code: code, Name: "Unknown(" + strconv.FormatInt(int64(code), 10) + ")"}
	}
}
