// Code generated by zigo. DO NOT EDIT.
package callback

import (
	"runtime/cgo"
	"sync/atomic"
	"unsafe"
)

type zigoHandle interface {
	zigoPointer() unsafe.Pointer
}

func zigoCheckedPointer(operation string, value zigoHandle) (unsafe.Pointer, error) {
	ptr := value.zigoPointer()
	if ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	return ptr, nil
}

func zigoOptionalPointer(operation string, absent bool, value zigoHandle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return zigoCheckedPointer(operation, value)
}

// CallbackContextCallback is the Go callback signature accepted by the generated binding.
type CallbackContextCallback func(int32) int32

// ApplyCallback is the Go callback signature accepted by the generated binding.
type ApplyCallback func(int32) int32

var activeCallbackHandles atomic.Int64

type zigoCallbackHandle = cgo.Handle

func newCallbackContextCallbackHandle(value CallbackContextCallback) zigoCallbackHandle {
	stored := (func(int32) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func newApplyCallbackHandle(value ApplyCallback) zigoCallbackHandle {
	stored := (func(int32) int32)(value)
	handle := cgo.NewHandle(stored)
	activeCallbackHandles.Add(1)
	return handle
}

func deleteCallbackHandle(handle zigoCallbackHandle) {
	handle.Delete()
	activeCallbackHandles.Add(-1)
}

func activeCallbackHandleCount() int64 { return activeCallbackHandles.Load() }
