// Code generated by zigo. DO NOT EDIT.
package callback

import (
	"runtime"

	"example.com/zigo/callback/internal/raw"
)

// NewFloatBuffer creates a caller-owned FloatBuffer.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewFloatBuffer() (*FloatBuffer, error) {
	result, code := raw.FloatBufferCreate()
	if code != 0 {
		return nil, errorForCode("NewFloatBuffer", code)
	}
	return newFloatBuffer(result), nil
}

// Push invokes the bound Zig FloatBuffer.push operation.
// It returns *HandleError if a required handle is nil or closed.
func (f *FloatBuffer) Push(value float32) error {
	if f != nil {
		f.mu.RLock()
		defer f.mu.RUnlock()
	}
	defer runtime.KeepAlive(f)
	ptr, err := zigoCheckedPointer("FloatBuffer.Push receiver", f)
	if err != nil {
		return err
	}
	raw.FloatBufferPush(ptr, value)
	return nil
}

// Len invokes the bound Zig FloatBuffer.len operation.
// It returns *HandleError if a required handle is nil or closed.
func (f *FloatBuffer) Len() (uint, error) {
	if f != nil {
		f.mu.RLock()
		defer f.mu.RUnlock()
	}
	defer runtime.KeepAlive(f)
	ptr, err := zigoCheckedPointer("FloatBuffer.Len receiver", f)
	if err != nil {
		return 0, err
	}
	return raw.FloatBufferLen(ptr), nil
}

// NewIntBuffer creates a caller-owned IntBuffer.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewIntBuffer() (*IntBuffer, error) {
	result, code := raw.IntBufferCreate()
	if code != 0 {
		return nil, errorForCode("NewIntBuffer", code)
	}
	return newIntBuffer(result), nil
}

// Push invokes the bound Zig IntBuffer.push operation.
// It returns *HandleError if a required handle is nil or closed.
func (i *IntBuffer) Push(value int32) error {
	if i != nil {
		i.mu.RLock()
		defer i.mu.RUnlock()
	}
	defer runtime.KeepAlive(i)
	ptr, err := zigoCheckedPointer("IntBuffer.Push receiver", i)
	if err != nil {
		return err
	}
	raw.IntBufferPush(ptr, value)
	return nil
}

// Len invokes the bound Zig IntBuffer.len operation.
// It returns *HandleError if a required handle is nil or closed.
func (i *IntBuffer) Len() (uint, error) {
	if i != nil {
		i.mu.RLock()
		defer i.mu.RUnlock()
	}
	defer runtime.KeepAlive(i)
	ptr, err := zigoCheckedPointer("IntBuffer.Len receiver", i)
	if err != nil {
		return 0, err
	}
	return raw.IntBufferLen(ptr), nil
}

// NewCallbackContext creates a caller-owned CallbackContext.
// The caller must call Close on the returned handle.
// Native failures are returned as generated error values.
func NewCallbackContext(callback CallbackContextCallback) (*CallbackContext, error) {
	callbackHandle := newCallbackContextCallbackHandle(callback)
	result, code := raw.CallbackContextCreate(uintptr(callbackHandle))
	if code != 0 {
		deleteCallbackHandle(callbackHandle)
		return nil, errorForCode("NewCallbackContext", code)
	}
	return newCallbackContext(result, []zigoCallbackHandle{callbackHandle}), nil
}

// Run invokes the bound Zig CallbackContext.run operation.
// It returns *HandleError if a required handle is nil or closed.
func (c *CallbackContext) Run(value int32) (int32, error) {
	if c != nil {
		c.mu.RLock()
		defer c.mu.RUnlock()
	}
	defer runtime.KeepAlive(c)
	ptr, err := zigoCheckedPointer("CallbackContext.Run receiver", c)
	if err != nil {
		return 0, err
	}
	return raw.CallbackContextRun(ptr, value), nil
}

// PanicNow invokes the bound Zig panicNow operation.
// Native failures are returned as generated error values.
func PanicNow() error {
	code := raw.PanicNow()
	if code != 0 {
		return errorForCode("PanicNow", code)
	}
	return nil
}

// CompressionBound invokes the bound Zig compressionBound operation.
func CompressionBound(sourceLen uint) uint {
	return raw.CompressionBound(sourceLen)
}

// Apply invokes the bound Zig apply operation.
func Apply(value int32, callback ApplyCallback) int32 {
	callbackHandle := newApplyCallbackHandle(callback)
	defer deleteCallbackHandle(callbackHandle)
	return raw.Apply(value, uintptr(callbackHandle))
}
