// Code generated by zigo. DO NOT EDIT.

// Package lifecycle contains the runtime state shared by generated public packages.
package lifecycle

import (
	"errors"
	"fmt"
	"strconv"
	"unsafe"
)

var (
	ErrInvalidHandle  = errors.New("zigo: nil or closed handle")
	ErrHandleInUse    = errors.New("zigo: handle has open children")
	ErrNativePanic    = errors.New("zigo: native panic")
	ErrNativeStatus   = errors.New("zigo: unrecognized native status")
	ErrCallbackPanic  = errors.New("zigo: callback panic")
	ErrCallbackFailed = errors.New("zigo: callback failed")
	ErrOutOfRange     = errors.New("zigo: argument out of range")
	ErrNilStream      = errors.New("zigo: nil stream argument")
)

type Handle interface {
	ZigoAcquire(operation string) (unsafe.Pointer, error)
	ZigoRelease()
	ZigoPoison(cause *NativePanicError)
}

type ChildHandle interface {
	Handle
	ZigoAcquireChild(operation string) (unsafe.Pointer, ChildHandle, error)
	ZigoDropChild()
}

func CheckedPointer(operation string, value Handle) (unsafe.Pointer, error) {
	return value.ZigoAcquire(operation)
}
func OptionalPointer(operation string, absent bool, value Handle) (unsafe.Pointer, error) {
	if absent {
		return nil, nil
	}
	return CheckedPointer(operation, value)
}
func PoisonAfterPanic(err error, handles ...Handle) error {
	if cause, ok := err.(*NativePanicError); ok {
		for _, handle := range handles {
			handle.ZigoPoison(cause)
		}
	}
	return err
}

func Release(handle Handle) { handle.ZigoRelease() }

type HandleError struct{ Operation string }

func (err *HandleError) Error() string { return "zigo: " + err.Operation + ": nil or closed handle" }
func (err *HandleError) Unwrap() error { return ErrInvalidHandle }

type HandleInUseError struct {
	Operation string
	Children  int
}

func (err *HandleInUseError) Error() string {
	return "zigo: " + err.Operation + ": handle has open children: " + strconv.Itoa(err.Children)
}
func (err *HandleInUseError) Unwrap() error { return ErrHandleInUse }

type NativePanicError struct{ Operation, Message string }

func (err *NativePanicError) Error() string {
	if err.Message == "" {
		return "zigo: " + err.Operation + ": native panic"
	}
	return "zigo: " + err.Operation + ": native panic: " + err.Message
}
func (err *NativePanicError) Unwrap() error { return ErrNativePanic }
func (err *NativePanicError) Poisoned(operation string) error {
	message := "handle unusable after a native panic in " + err.Operation
	if err.Message != "" {
		message += ": " + err.Message
	}
	return &NativePanicError{Operation: operation, Message: message}
}

type RangeError struct{ Operation, Parameter, Type string }

func (err *RangeError) Error() string {
	return "zigo: " + err.Operation + ": argument " + err.Parameter + " is out of range for " + err.Type
}
func (err *RangeError) Unwrap() error { return ErrOutOfRange }

type StreamError struct {
	Operation, Parameter string
	Err                  error
}

func (err *StreamError) Error() string {
	return "zigo: " + err.Operation + ": stream " + err.Parameter + ": " + err.Err.Error()
}
func (err *StreamError) Unwrap() error { return err.Err }

type CallbackError struct {
	Operation, Callback string
	Err                 error
}

func (err *CallbackError) Error() string {
	return "zigo: " + err.Operation + ": callback " + err.Callback + ": " + err.Err.Error()
}
func (err *CallbackError) Is(target error) bool { return target == ErrCallbackFailed }
func (err *CallbackError) Unwrap() error        { return err.Err }

type StatusError struct {
	Operation string
	Status    uint8
}

func (err *StatusError) Error() string {
	return "zigo: " + err.Operation + ": unrecognized native status"
}
func (err *StatusError) Unwrap() error { return ErrNativeStatus }

type CallbackPanicError struct {
	Operation string
	Value     any
	Stack     []byte
}

func (err *CallbackPanicError) Error() string {
	return "zigo: " + err.Operation + ": callback panic: " + fmt.Sprint(err.Value)
}
func (err *CallbackPanicError) Is(target error) bool { return target == ErrCallbackPanic }
func (err *CallbackPanicError) Unwrap() error {
	if cause, ok := err.Value.(error); ok {
		return cause
	}
	return nil
}

type Error struct {
	Code            int32
	Name, Operation string
}

func (err *Error) Error() string {
	if err.Operation == "" {
		return err.Name
	}
	return "zigo: " + err.Operation + ": " + err.Name
}
func (err *Error) Is(target error) bool {
	other, ok := target.(*Error)
	return ok && err.Code == other.Code
}
