// Code generated by zigo. DO NOT EDIT.

package streams

import (
	"errors"
	"fmt"
	"strconv"

	"example.com/zigo/streams/internal/raw"
)

// ErrInvalidHandle identifies a nil, closed, or invalid borrowed handle.
var ErrInvalidHandle = errors.New("zigo: nil or closed handle")

// ErrNativePanic identifies a Zig panic caught at the native boundary.
var ErrNativePanic = errors.New("zigo: native panic")

// ErrCallbackPanic identifies a panic raised by a Go callback inside a native call.
var ErrCallbackPanic = errors.New("zigo: callback panic")

// ErrOutOfRange identifies an argument outside the range of the Zig integer that carries it.
var ErrOutOfRange = errors.New("zigo: argument out of range")

// ErrNilStream identifies a nil io.Writer or io.Reader argument.
var ErrNilStream = errors.New("zigo: nil stream argument")

// HandleError reports which generated operation received an invalid handle.
type HandleError struct {
	// Operation names the generated operation and offending receiver or parameter.
	Operation string
}

// Error implements error.
func (err *HandleError) Error() string {
	return "zigo: " + err.Operation + ": nil or closed handle"
}

// Unwrap returns ErrInvalidHandle for errors.Is classification.
func (err *HandleError) Unwrap() error { return ErrInvalidHandle }

// NativePanicError reports a Zig panic caught at the native boundary.
type NativePanicError struct {
	// Operation names the generated call or projection.
	Operation string
	// Message is the native panic message when available.
	Message string
}

// Error implements error.
func (err *NativePanicError) Error() string {
	if err.Message == "" {
		return "zigo: " + err.Operation + ": native panic"
	}
	return "zigo: " + err.Operation + ": native panic: " + err.Message
}

// Unwrap returns ErrNativePanic for errors.Is classification.
func (err *NativePanicError) Unwrap() error { return ErrNativePanic }

// poisoned is what a handle answers once err has left the native state behind
// it unknown: the same kind of error, naming the call that was refused.
func (err *NativePanicError) poisoned(operation string) error {
	message := "handle unusable after a native panic in " + err.Operation
	if err.Message != "" {
		message += ": " + err.Message
	}
	return &NativePanicError{Operation: operation, Message: message}
}

// RangeError reports an argument the narrower Zig integer behind a parameter
// cannot represent. The check runs in Go, so the native library is never
// called with the value.
type RangeError struct {
	// Operation names the generated call.
	Operation string
	// Parameter names the offending Go parameter.
	Parameter string
	// Type is how Zig spells the integer the value has to fit, such as "u21".
	Type string
}

// Error implements error.
func (err *RangeError) Error() string {
	return "zigo: " + err.Operation + ": argument " + err.Parameter + " is out of range for " + err.Type
}

// Unwrap returns ErrOutOfRange for errors.Is classification.
func (err *RangeError) Unwrap() error { return ErrOutOfRange }

// StreamError reports a failure from the Go io.Writer or io.Reader a native
// call streamed through. It outranks the native result: the library may have
// reported success for work whose output never arrived.
type StreamError struct {
	// Operation names the generated call.
	Operation string
	// Parameter names the Go stream parameter that failed.
	Parameter string
	// Err is the error the stream returned, or ErrNilStream for a nil argument.
	Err error
}

// Error implements error.
func (err *StreamError) Error() string {
	return "zigo: " + err.Operation + ": stream " + err.Parameter + ": " + err.Err.Error()
}

// Unwrap returns the stream's own error for errors.Is and errors.As.
func (err *StreamError) Unwrap() error { return err.Err }

// CallbackPanicError is what a generated call panics with after a Go callback
// panicked inside it. The trampoline recovers the panic so the native frames
// can unwind, and the call rethrows it once the native code has returned.
type CallbackPanicError struct {
	// Operation names the generated call the callback was running under.
	Operation string
	// Value is the original panic value.
	Value any
	// Stack is the callback goroutine's stack where the panic was recovered.
	Stack []byte
}

// Error implements error.
func (err *CallbackPanicError) Error() string {
	return "zigo: " + err.Operation + ": callback panic: " + fmt.Sprint(err.Value)
}

// Is reports ErrCallbackPanic for errors.Is classification.
func (err *CallbackPanicError) Is(target error) bool { return target == ErrCallbackPanic }

// Unwrap returns the original panic value when it is an error, so errors.Is and errors.As reach it.
func (err *CallbackPanicError) Unwrap() error {
	if cause, ok := err.Value.(error); ok {
		return cause
	}
	return nil
}

// Error is a stable Zig error-set value returned by the generated binding.
// Classify it with errors.Is against the Err* sentinels; a returned value
// also names the operation it came from.
type Error struct {
	// Code is the stable integer stored in errors.lock.json.
	Code int32
	// Name is the Zig error name.
	Name string
	// Operation names the generated call that returned the error. It is
	// empty on the package-level sentinels.
	Operation string
}

// Error implements error.
func (err *Error) Error() string {
	if err.Operation == "" {
		return err.Name
	}
	return "zigo: " + err.Operation + ": " + err.Name
}

// Is compares generated errors by stable code.
func (err *Error) Is(target error) bool {
	other, ok := target.(*Error)
	return ok && err.Code == other.Code
}

// ErrOutOfMemory represents Zig error.OutOfMemory.
var ErrOutOfMemory = &Error{Code: 1, Name: "OutOfMemory"}

// ErrWriteFailed represents Zig error.WriteFailed.
var ErrWriteFailed = &Error{Code: 2, Name: "WriteFailed"}

// ErrReadFailed represents Zig error.ReadFailed.
var ErrReadFailed = &Error{Code: 3, Name: "ReadFailed"}

// ErrTooLarge represents Zig error.TooLarge.
var ErrTooLarge = &Error{Code: 4, Name: "TooLarge"}

func errorForCode(operation string, code int32) error {
	switch code {
	case -2:
		return &NativePanicError{Operation: operation, Message: raw.LastErrorMessage()}
	case 1:
		return &Error{Code: 1, Name: "OutOfMemory", Operation: operation}
	case 2:
		return &Error{Code: 2, Name: "WriteFailed", Operation: operation}
	case 3:
		return &Error{Code: 3, Name: "ReadFailed", Operation: operation}
	case 4:
		return &Error{Code: 4, Name: "TooLarge", Operation: operation}
	default:
		return &Error{Code: code, Name: "Unknown(" + strconv.Itoa(int(code)) + ")", Operation: operation}
	}
}
