// Code generated by zigo. DO NOT EDIT.

package streams

import (
	"runtime"
	"sync"
	"unsafe"

	"example.com/zigo/streams/internal/raw"
)

// Document is a caller-owned native handle. Call Close when it is no longer needed.
type Document struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins d open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (d *Document) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if d == nil {
		return nil, &HandleError{Operation: operation}
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.closed || d.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if d.poison != nil {
		return nil, d.poison.poisoned(operation)
	}
	d.active++
	return d.ptr, nil
}

func (d *Document) zigoRelease() {
	if d == nil {
		return
	}
	d.mu.Lock()
	d.active--
	state, release := d.zigoTakeLocked()
	d.mu.Unlock()
	if release {
		zigoCleanupDocument(state)
	}
}

// zigoPoison marks d unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (d *Document) zigoPoison(cause *NativePanicError) {
	if d == nil {
		return
	}
	d.mu.Lock()
	defer d.mu.Unlock()
	if d.poison == nil {
		d.poison = cause
		d.cleanup.Stop()
	}
}

type zigoDocumentCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewDocument(ptr unsafe.Pointer) *Document {
	value := &Document{ptr: ptr}
	state := zigoDocumentCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupDocument, state)
	return value
}

func zigoCleanupDocument(state zigoDocumentCleanupState) {
	if state.ptr != nil {
		raw.DocumentDeinit(state.ptr)
	}
}

// Close releases the native Document resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native; otherwise the error is nil.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (d *Document) Close() error {
	if d == nil {
		return nil
	}
	d.mu.Lock()
	if d.closed {
		d.mu.Unlock()
		return nil
	}
	d.closed = true
	d.cleanup.Stop()
	state, release := d.zigoTakeLocked()
	d.mu.Unlock()
	if release {
		zigoCleanupDocument(state)
	}
	runtime.KeepAlive(d)
	return nil
}

// zigoTakeLocked hands out what is left to release once d is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (d *Document) zigoTakeLocked() (zigoDocumentCleanupState, bool) {
	if !d.closed || d.active != 0 || d.ptr == nil {
		return zigoDocumentCleanupState{}, false
	}
	state := zigoDocumentCleanupState{ptr: d.ptr}
	d.ptr = nil
	if d.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Sink is a caller-owned native handle. Call Close when it is no longer needed.
type Sink struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins s open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (s *Sink) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed || s.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if s.poison != nil {
		return nil, s.poison.poisoned(operation)
	}
	s.active++
	return s.ptr, nil
}

func (s *Sink) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSink(state)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Sink) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
}

type zigoSinkCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewSink(ptr unsafe.Pointer) *Sink {
	value := &Sink{ptr: ptr}
	state := zigoSinkCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSink, state)
	return value
}

func zigoCleanupSink(state zigoSinkCleanupState) {
	if state.ptr != nil {
		raw.SinkDeinit(state.ptr)
	}
}

// Close releases the native Sink resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native; otherwise the error is nil.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Sink) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSink(state)
	}
	runtime.KeepAlive(s)
	return nil
}

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Sink) zigoTakeLocked() (zigoSinkCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSinkCleanupState{}, false
	}
	state := zigoSinkCleanupState{ptr: s.ptr}
	s.ptr = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}

// Source is a caller-owned native handle. Call Close when it is no longer needed.
type Source struct {
	ptr     unsafe.Pointer
	mu      sync.Mutex
	active  int
	closed  bool
	poison  *NativePanicError
	cleanup runtime.Cleanup
}

// zigoAcquire pins s open for one native call and hands back its pointer;
// the call ends with zigoRelease. A nil, closed, or poisoned handle is the error.
func (s *Source) zigoAcquire(operation string) (unsafe.Pointer, error) {
	if s == nil {
		return nil, &HandleError{Operation: operation}
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed || s.ptr == nil {
		return nil, &HandleError{Operation: operation}
	}
	if s.poison != nil {
		return nil, s.poison.poisoned(operation)
	}
	s.active++
	return s.ptr, nil
}

func (s *Source) zigoRelease() {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.active--
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSource(state)
	}
}

// zigoPoison marks s unusable: a Zig panic unwound through native frames
// without running their defers, so the state behind it is unknown.
func (s *Source) zigoPoison(cause *NativePanicError) {
	if s == nil {
		return
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.poison == nil {
		s.poison = cause
		s.cleanup.Stop()
	}
}

type zigoSourceCleanupState struct {
	ptr unsafe.Pointer
}

func zigoNewSource(ptr unsafe.Pointer) *Source {
	value := &Source{ptr: ptr}
	state := zigoSourceCleanupState{ptr: ptr}
	value.cleanup = runtime.AddCleanup(value, zigoCleanupSource, state)
	return value
}

func zigoCleanupSource(state zigoSourceCleanupState) {
	if state.ptr != nil {
		raw.SourceDeinit(state.ptr)
	}
}

// Close releases the native Source resources. It is safe to call more than once.
// It returns *HandleInUseError while a call is still inside native; otherwise the error is nil.
// Close does not wait: a call still inside native keeps the resources until it
// returns, and every call made after Close fails with *HandleError.
func (s *Source) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return nil
	}
	s.closed = true
	s.cleanup.Stop()
	state, release := s.zigoTakeLocked()
	s.mu.Unlock()
	if release {
		zigoCleanupSource(state)
	}
	runtime.KeepAlive(s)
	return nil
}

// zigoTakeLocked hands out what is left to release once s is closed and no
// call is inside native; mu must be held. A poisoned handle keeps its native
// object: releasing state a panic left half-changed could fault, so it leaks.
func (s *Source) zigoTakeLocked() (zigoSourceCleanupState, bool) {
	if !s.closed || s.active != 0 || s.ptr == nil {
		return zigoSourceCleanupState{}, false
	}
	state := zigoSourceCleanupState{ptr: s.ptr}
	s.ptr = nil
	if s.poison != nil {
		state.ptr = nil
	}
	return state, true
}
